// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module canny_Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write,
        p_kernel_val_0_V_1_read,
        p_kernel_val_0_V_2_read,
        p_kernel_val_1_V_0_read,
        p_kernel_val_1_V_2_read,
        p_kernel_val_2_V_0_read,
        p_kernel_val_2_V_1_read
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 7'b1;
parameter    ap_ST_st2_fsm_1 = 7'b10;
parameter    ap_ST_st3_fsm_2 = 7'b100;
parameter    ap_ST_st4_fsm_3 = 7'b1000;
parameter    ap_ST_st5_fsm_4 = 7'b10000;
parameter    ap_ST_pp0_stg0_fsm_5 = 7'b100000;
parameter    ap_ST_st19_fsm_6 = 7'b1000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv11_402 = 11'b10000000010;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv11_400 = 11'b10000000000;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv11_7FE = 11'b11111111110;
parameter    ap_const_lv11_7FD = 11'b11111111101;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv12_7FE = 12'b11111111110;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;
input  [1:0] p_kernel_val_0_V_1_read;
input  [1:0] p_kernel_val_0_V_2_read;
input  [2:0] p_kernel_val_1_V_0_read;
input  [3:0] p_kernel_val_1_V_2_read;
input  [1:0] p_kernel_val_2_V_0_read;
input  [2:0] p_kernel_val_2_V_1_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm = 7'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_25;
reg   [10:0] p_027_0_i_reg_292;
wire   [0:0] tmp_38_fu_303_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_68;
wire  signed [9:0] OP2_V_0_1_cast_fu_309_p1;
reg  signed [9:0] OP2_V_0_1_cast_reg_1300;
wire   [0:0] tmp_s_phi_fu_274_p4;
wire  signed [9:0] OP2_V_0_2_cast_fu_312_p1;
reg  signed [9:0] OP2_V_0_2_cast_reg_1305;
wire  signed [10:0] OP2_V_1_cast_fu_315_p1;
reg  signed [10:0] OP2_V_1_cast_reg_1310;
wire   [11:0] OP2_V_1_2_cast_fu_318_p1;
reg   [11:0] OP2_V_1_2_cast_reg_1315;
wire  signed [9:0] OP2_V_2_cast_fu_321_p1;
reg  signed [9:0] OP2_V_2_cast_reg_1320;
wire   [10:0] OP2_V_2_1_cast_fu_324_p1;
reg   [10:0] OP2_V_2_1_cast_reg_1325;
wire   [10:0] i_V_fu_337_p2;
reg   [10:0] i_V_reg_1333;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_93;
reg   [0:0] tmp_reg_1338;
wire   [0:0] exitcond1_fu_331_p2;
reg   [0:0] tmp_114_reg_1342;
wire   [0:0] icmp_fu_369_p2;
reg   [0:0] icmp_reg_1347;
wire   [0:0] tmp_43_fu_375_p2;
reg   [0:0] tmp_43_reg_1352;
wire   [0:0] tmp_208_1_fu_381_p2;
reg   [0:0] tmp_208_1_reg_1356;
wire   [0:0] tmp_44_fu_387_p2;
reg   [0:0] tmp_44_reg_1360;
reg   [0:0] tmp_117_reg_1367;
wire   [0:0] icmp4_fu_417_p2;
reg   [0:0] icmp4_reg_1372;
reg   [1:0] tmp_120_reg_1377;
wire   [1:0] tmp_121_fu_459_p1;
reg   [1:0] tmp_121_reg_1382;
reg   [0:0] tmp_122_reg_1387;
reg   [0:0] tmp_125_reg_1392;
wire   [1:0] tmp_128_fu_515_p1;
reg   [1:0] tmp_128_reg_1397;
wire   [1:0] tmp_129_fu_519_p1;
reg   [1:0] tmp_129_reg_1402;
wire   [1:0] tmp_132_fu_523_p1;
reg   [1:0] tmp_132_reg_1407;
wire   [1:0] tmp_134_fu_533_p3;
reg   [1:0] tmp_134_reg_1412;
wire   [1:0] tmp_135_fu_541_p1;
reg   [1:0] tmp_135_reg_1417;
wire   [1:0] tmp_137_fu_551_p3;
reg   [1:0] tmp_137_reg_1422;
wire   [1:0] tmp_106_fu_586_p3;
reg   [1:0] tmp_106_reg_1427;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_141;
wire   [1:0] tmp_107_fu_593_p3;
reg   [1:0] tmp_107_reg_1432;
wire   [1:0] tmp_108_fu_598_p3;
reg   [1:0] tmp_108_reg_1437;
wire   [1:0] row_assign_s_fu_603_p2;
reg   [1:0] row_assign_s_reg_1442;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_157;
wire   [1:0] row_assign_10_1_t_fu_608_p2;
reg   [1:0] row_assign_10_1_t_reg_1447;
wire   [1:0] row_assign_10_2_t_fu_613_p2;
reg   [1:0] row_assign_10_2_t_reg_1452;
wire   [0:0] exitcond_fu_622_p2;
reg   [0:0] exitcond_reg_1457;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_5;
reg    ap_sig_bdd_171;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1457_pp0_it2;
reg   [0:0] or_cond_i_i_reg_1499;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2;
reg    ap_sig_bdd_196;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg    ap_reg_ppiten_pp0_it8 = 1'b0;
reg    ap_reg_ppiten_pp0_it9 = 1'b0;
reg    ap_reg_ppiten_pp0_it10 = 1'b0;
reg    ap_reg_ppiten_pp0_it11 = 1'b0;
reg   [0:0] or_cond_i_reg_1495;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1495_pp0_it11;
reg    ap_sig_bdd_222;
reg    ap_reg_ppiten_pp0_it12 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1457_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1457_pp0_it3;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1457_pp0_it4;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1457_pp0_it5;
wire   [10:0] j_V_fu_628_p2;
wire   [11:0] ImagLoc_x_fu_650_p2;
reg   [11:0] ImagLoc_x_reg_1466;
reg   [0:0] tmp_139_reg_1471;
wire   [0:0] icmp7_fu_674_p2;
reg   [0:0] icmp7_reg_1477;
wire   [11:0] p_p2_i_i_fu_698_p3;
reg   [11:0] p_p2_i_i_reg_1484;
reg   [11:0] ap_reg_ppstg_p_p2_i_i_reg_1484_pp0_it1;
reg   [1:0] tmp_142_reg_1490;
wire   [0:0] or_cond_i_fu_716_p2;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1495_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1495_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1495_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1495_pp0_it4;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1495_pp0_it5;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1495_pp0_it6;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1495_pp0_it7;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1495_pp0_it8;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1495_pp0_it9;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1495_pp0_it10;
wire   [0:0] or_cond_i_i_fu_729_p2;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3;
wire   [12:0] sel_tmp_fu_748_p3;
reg   [12:0] sel_tmp_reg_1503;
wire   [0:0] sel_tmp8_fu_766_p2;
reg   [0:0] sel_tmp8_reg_1508;
wire   [0:0] brmerge_fu_772_p2;
reg   [0:0] brmerge_reg_1513;
reg   [0:0] ap_reg_ppstg_brmerge_reg_1513_pp0_it2;
wire   [1:0] tmp_143_fu_789_p1;
reg   [1:0] tmp_143_reg_1520;
reg   [9:0] k_buf_0_val_3_addr_reg_1525;
reg   [9:0] k_buf_0_val_4_addr_reg_1531;
reg   [9:0] ap_reg_ppstg_k_buf_0_val_4_addr_reg_1531_pp0_it3;
reg   [9:0] k_buf_0_val_5_addr_reg_1537;
reg   [9:0] ap_reg_ppstg_k_buf_0_val_5_addr_reg_1537_pp0_it3;
wire   [7:0] k_buf_0_val_3_q0;
reg   [7:0] k_buf_0_val_3_load_reg_1543;
wire   [7:0] col_buf_0_val_0_0_fu_835_p3;
reg   [7:0] col_buf_0_val_0_0_reg_1548;
wire   [7:0] k_buf_0_val_4_q0;
reg   [7:0] k_buf_0_val_4_load_reg_1556;
wire   [7:0] col_buf_0_val_1_0_fu_854_p3;
reg   [7:0] col_buf_0_val_1_0_reg_1561;
wire   [7:0] col_buf_0_val_2_0_fu_873_p3;
reg   [7:0] col_buf_0_val_2_0_reg_1569;
reg   [7:0] tmp_149_reg_1577;
wire   [7:0] src_kernel_win_0_val_0_0_fu_924_p3;
reg   [7:0] src_kernel_win_0_val_0_0_reg_1583;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1583_pp0_it5;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1583_pp0_it6;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1583_pp0_it7;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1583_pp0_it8;
wire   [7:0] src_kernel_win_0_val_1_0_fu_938_p3;
reg   [7:0] src_kernel_win_0_val_1_0_reg_1589;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1589_pp0_it5;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1589_pp0_it6;
wire   [7:0] src_kernel_win_0_val_2_0_fu_952_p3;
reg   [7:0] src_kernel_win_0_val_2_0_reg_1595;
reg   [7:0] src_kernel_win_0_val_2_1_lo_2_reg_1611;
reg   [7:0] src_kernel_win_0_val_2_1_2_s_reg_1616;
wire   [8:0] p_Val2_s_fu_1055_p2;
reg   [8:0] p_Val2_s_reg_1636;
wire   [9:0] grp_fu_965_p2;
reg   [9:0] p_Val2_0_1_reg_1641;
wire   [9:0] grp_fu_973_p2;
reg   [9:0] p_Val2_0_2_reg_1646;
wire   [10:0] p_Val2_13_0_2_fu_1084_p2;
reg   [10:0] p_Val2_13_0_2_reg_1656;
wire   [10:0] grp_fu_1001_p2;
reg   [10:0] p_Val2_1_reg_1661;
wire   [9:0] grp_fu_1010_p2;
reg   [9:0] p_Val2_2_reg_1666;
wire   [10:0] grp_fu_1019_p2;
reg   [10:0] p_Val2_2_1_reg_1671;
wire   [11:0] p_Val2_13_1_1_fu_1096_p2;
reg   [11:0] p_Val2_13_1_1_reg_1676;
wire   [11:0] grp_fu_1064_p2;
reg   [11:0] p_Val2_1_2_reg_1681;
wire   [10:0] tmp3_fu_1114_p2;
reg   [10:0] tmp3_reg_1686;
reg   [0:0] isneg_reg_1691;
reg   [0:0] ap_reg_ppstg_isneg_reg_1691_pp0_it11;
wire   [7:0] p_Val2_5_fu_1140_p1;
reg   [7:0] p_Val2_5_reg_1697;
reg   [7:0] ap_reg_ppstg_p_Val2_5_reg_1697_pp0_it11;
reg   [3:0] tmp_70_reg_1702;
wire   [0:0] tmp_i_i_fu_1154_p2;
reg   [0:0] tmp_i_i_reg_1707;
wire   [0:0] overflow_fu_1164_p2;
reg   [0:0] overflow_reg_1712;
wire   [9:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [9:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [7:0] k_buf_0_val_3_d1;
wire   [9:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [9:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [9:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [9:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
reg   [0:0] tmp_s_reg_270;
reg   [10:0] p_014_0_i_reg_281;
reg    ap_sig_cseq_ST_st19_fsm_6;
reg    ap_sig_bdd_460;
wire   [63:0] tmp_60_fu_793_p1;
reg   [7:0] src_kernel_win_0_val_0_1_fu_130;
reg   [7:0] src_kernel_win_0_val_0_1_2_fu_134;
reg   [7:0] src_kernel_win_0_val_1_1_fu_138;
reg   [7:0] src_kernel_win_0_val_1_1_2_fu_142;
reg   [7:0] src_kernel_win_0_val_2_1_fu_146;
reg   [7:0] src_kernel_win_0_val_2_1_2_fu_150;
reg   [7:0] right_border_buf_0_val_0_1_fu_154;
reg   [7:0] right_border_buf_0_val_0_1_2_fu_158;
reg   [7:0] right_border_buf_0_val_2_1_fu_162;
reg   [7:0] right_border_buf_0_val_1_1_fu_166;
reg   [7:0] right_border_buf_0_val_1_1_2_fu_170;
reg   [7:0] right_border_buf_0_val_2_1_3_fu_174;
wire   [9:0] tmp_115_fu_359_p4;
wire   [11:0] tmp_50_cast_cast_fu_327_p1;
wire   [11:0] tmp_45_fu_393_p2;
wire   [1:0] tmp_118_fu_407_p4;
wire   [10:0] p_assign_7_fu_431_p2;
wire   [0:0] tmp_119_fu_423_p3;
wire  signed [11:0] p_assign_7_cast_fu_437_p1;
wire   [11:0] p_p2_i423_i_fu_441_p3;
wire   [10:0] p_assign_6_1_fu_463_p2;
wire   [10:0] p_assign_6_2_fu_489_p2;
wire   [1:0] tmp_124_fu_485_p1;
wire   [0:0] tmp_123_fu_477_p3;
wire   [1:0] tmp_133_fu_527_p2;
wire   [1:0] tmp_127_fu_511_p1;
wire   [0:0] tmp_126_fu_503_p3;
wire   [1:0] tmp_136_fu_545_p2;
wire   [0:0] rev_fu_559_p2;
wire   [0:0] icmp5_fu_569_p2;
wire   [1:0] tmp_130_fu_574_p2;
wire   [0:0] or_cond_i422_i_fu_564_p2;
wire   [1:0] tmp_131_fu_579_p3;
wire   [9:0] tmp_138_fu_634_p4;
wire   [11:0] tmp_53_cast_cast_fu_618_p1;
wire   [1:0] tmp_140_fu_664_p4;
wire   [10:0] p_assign_1_fu_688_p2;
wire   [0:0] tmp_141_fu_680_p3;
wire  signed [11:0] p_assign_1_cast_fu_694_p1;
wire   [0:0] icmp6_fu_644_p2;
wire   [0:0] rev7_fu_724_p2;
wire   [11:0] p_assign_2_fu_739_p2;
wire  signed [12:0] ImagLoc_x_cast_fu_721_p1;
wire   [12:0] p_assign_2_cast_fu_744_p1;
wire   [0:0] icmp54_not_fu_756_p2;
wire   [0:0] icmp8_fu_734_p2;
wire   [0:0] sel_tmp7_fu_761_p2;
wire  signed [12:0] p_p2_i_i_cast_cast8_fu_776_p1;
wire   [12:0] x_fu_779_p3;
wire  signed [31:0] col_assign_cast_fu_785_p1;
wire   [1:0] col_assign_3_t_fu_818_p2;
wire   [7:0] tmp_61_fu_823_p5;
wire   [7:0] tmp_62_fu_842_p5;
wire   [7:0] tmp_63_fu_861_p5;
wire   [7:0] tmp_65_fu_916_p5;
wire   [7:0] tmp_67_fu_930_p5;
wire   [7:0] tmp_69_fu_944_p5;
wire  signed [1:0] grp_fu_965_p0;
wire   [7:0] grp_fu_965_p1;
wire  signed [1:0] grp_fu_973_p0;
wire   [7:0] grp_fu_973_p1;
wire  signed [2:0] grp_fu_1001_p0;
wire   [7:0] grp_fu_1001_p1;
wire  signed [1:0] grp_fu_1010_p0;
wire   [7:0] grp_fu_1010_p1;
wire   [2:0] grp_fu_1019_p0;
wire   [7:0] grp_fu_1019_p1;
wire   [8:0] OP1_V_0_cast_fu_1052_p1;
wire   [3:0] grp_fu_1064_p0;
wire   [7:0] grp_fu_1064_p1;
wire  signed [10:0] tmp_252_0_cast_fu_1069_p1;
wire  signed [10:0] tmp_252_0_1_cast_fu_1072_p1;
wire  signed [10:0] tmp_252_0_2_cast_cast_fu_1081_p1;
wire   [10:0] p_Val2_13_0_1_fu_1075_p2;
wire  signed [11:0] tmp_252_1_cast_cast_fu_1093_p1;
wire  signed [11:0] p_Val2_13_0_2_cast6_fu_1090_p1;
wire   [9:0] tmp_252_2_2_cast_cast_cast_fu_1102_p1;
wire   [9:0] tmp4_fu_1105_p2;
wire  signed [10:0] tmp4_cast_fu_1110_p1;
wire   [11:0] tmp2_fu_1119_p2;
wire  signed [11:0] tmp3_cast_fu_1123_p1;
wire   [11:0] p_Val2_4_fu_1126_p2;
wire   [0:0] not_i_i_i_fu_1159_p2;
wire   [0:0] tmp_i_i_78_fu_1177_p2;
wire   [7:0] p_mux_i_i_cast_fu_1170_p3;
reg    grp_fu_965_ce;
reg    grp_fu_973_ce;
reg    grp_fu_1001_ce;
reg    grp_fu_1010_ce;
reg    grp_fu_1019_ce;
reg    grp_fu_1064_ce;
reg   [6:0] ap_NS_fsm;
wire   [10:0] grp_fu_1001_p10;
wire   [9:0] grp_fu_1010_p10;
wire   [10:0] grp_fu_1019_p10;
wire   [11:0] grp_fu_1064_p10;
wire   [9:0] grp_fu_965_p10;
wire   [9:0] grp_fu_973_p10;
reg    ap_sig_bdd_1118;
reg    ap_sig_bdd_1120;
reg    ap_sig_bdd_1117;
reg    ap_sig_bdd_1123;


canny_Filter2D_1_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
k_buf_0_val_3_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_3_address0 ),
    .ce0( k_buf_0_val_3_ce0 ),
    .q0( k_buf_0_val_3_q0 ),
    .address1( k_buf_0_val_3_address1 ),
    .ce1( k_buf_0_val_3_ce1 ),
    .we1( k_buf_0_val_3_we1 ),
    .d1( k_buf_0_val_3_d1 )
);

canny_Filter2D_1_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
k_buf_0_val_4_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_4_address0 ),
    .ce0( k_buf_0_val_4_ce0 ),
    .q0( k_buf_0_val_4_q0 ),
    .address1( k_buf_0_val_4_address1 ),
    .ce1( k_buf_0_val_4_ce1 ),
    .we1( k_buf_0_val_4_we1 ),
    .d1( k_buf_0_val_4_d1 )
);

canny_Filter2D_1_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
k_buf_0_val_5_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_5_address0 ),
    .ce0( k_buf_0_val_5_ce0 ),
    .q0( k_buf_0_val_5_q0 ),
    .address1( k_buf_0_val_5_address1 ),
    .ce1( k_buf_0_val_5_ce1 ),
    .we1( k_buf_0_val_5_we1 ),
    .d1( k_buf_0_val_5_d1 )
);

canny_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
canny_mux_3to1_sel2_8_1_U41(
    .din1( right_border_buf_0_val_0_1_fu_154 ),
    .din2( right_border_buf_0_val_0_1_2_fu_158 ),
    .din3( ap_const_lv8_0 ),
    .din4( col_assign_3_t_fu_818_p2 ),
    .dout( tmp_61_fu_823_p5 )
);

canny_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
canny_mux_3to1_sel2_8_1_U42(
    .din1( right_border_buf_0_val_1_1_fu_166 ),
    .din2( right_border_buf_0_val_1_1_2_fu_170 ),
    .din3( ap_const_lv8_0 ),
    .din4( col_assign_3_t_fu_818_p2 ),
    .dout( tmp_62_fu_842_p5 )
);

canny_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
canny_mux_3to1_sel2_8_1_U43(
    .din1( right_border_buf_0_val_2_1_3_fu_174 ),
    .din2( right_border_buf_0_val_2_1_fu_162 ),
    .din3( ap_const_lv8_0 ),
    .din4( col_assign_3_t_fu_818_p2 ),
    .dout( tmp_63_fu_861_p5 )
);

canny_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
canny_mux_3to1_sel2_8_1_U44(
    .din1( col_buf_0_val_0_0_reg_1548 ),
    .din2( col_buf_0_val_1_0_reg_1561 ),
    .din3( col_buf_0_val_2_0_reg_1569 ),
    .din4( row_assign_s_reg_1442 ),
    .dout( tmp_65_fu_916_p5 )
);

canny_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
canny_mux_3to1_sel2_8_1_U45(
    .din1( col_buf_0_val_0_0_reg_1548 ),
    .din2( col_buf_0_val_1_0_reg_1561 ),
    .din3( col_buf_0_val_2_0_reg_1569 ),
    .din4( row_assign_10_1_t_reg_1447 ),
    .dout( tmp_67_fu_930_p5 )
);

canny_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
canny_mux_3to1_sel2_8_1_U46(
    .din1( col_buf_0_val_0_0_reg_1548 ),
    .din2( col_buf_0_val_1_0_reg_1561 ),
    .din3( col_buf_0_val_2_0_reg_1569 ),
    .din4( row_assign_10_2_t_reg_1452 ),
    .dout( tmp_69_fu_944_p5 )
);

canny_mul_2s_8ns_10_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
canny_mul_2s_8ns_10_3_U47(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_965_p0 ),
    .din1( grp_fu_965_p1 ),
    .ce( grp_fu_965_ce ),
    .dout( grp_fu_965_p2 )
);

canny_mul_2s_8ns_10_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
canny_mul_2s_8ns_10_3_U48(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_973_p0 ),
    .din1( grp_fu_973_p1 ),
    .ce( grp_fu_973_ce ),
    .dout( grp_fu_973_p2 )
);

canny_mul_3s_8ns_11_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
canny_mul_3s_8ns_11_3_U49(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1001_p0 ),
    .din1( grp_fu_1001_p1 ),
    .ce( grp_fu_1001_ce ),
    .dout( grp_fu_1001_p2 )
);

canny_mul_2s_8ns_10_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
canny_mul_2s_8ns_10_3_U50(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1010_p0 ),
    .din1( grp_fu_1010_p1 ),
    .ce( grp_fu_1010_ce ),
    .dout( grp_fu_1010_p2 )
);

canny_mul_3ns_8ns_11_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
canny_mul_3ns_8ns_11_3_U51(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1019_p0 ),
    .din1( grp_fu_1019_p1 ),
    .ce( grp_fu_1019_ce ),
    .dout( grp_fu_1019_p2 )
);

canny_mul_4ns_8ns_12_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 12 ))
canny_mul_4ns_8ns_12_3_U52(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1064_p0 ),
    .din1( grp_fu_1064_p1 ),
    .ce( grp_fu_1064_ce ),
    .dout( grp_fu_1064_p2 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == exitcond_fu_622_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it10
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it10 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it10 <= ap_reg_ppiten_pp0_it9;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it11
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it11 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it11 <= ap_reg_ppiten_pp0_it10;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it12
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it12 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it12 <= ap_reg_ppiten_pp0_it11;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
            ap_reg_ppiten_pp0_it12 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            if (~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) begin
                ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) begin
                ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
            end
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it8
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it9
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it9 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it9 <= ap_reg_ppiten_pp0_it8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_6)) begin
        p_014_0_i_reg_281 <= i_V_reg_1333;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_s_phi_fu_274_p4 == ap_const_lv1_0))) begin
        p_014_0_i_reg_281 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == exitcond_fu_622_p2))) begin
        p_027_0_i_reg_292 <= j_V_fu_628_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        p_027_0_i_reg_292 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        tmp_s_reg_270 <= ap_const_lv1_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_s_phi_fu_274_p4 == ap_const_lv1_0))) begin
        tmp_s_reg_270 <= tmp_38_fu_303_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == exitcond_fu_622_p2))) begin
        ImagLoc_x_reg_1466 <= ImagLoc_x_fu_650_p2;
        icmp7_reg_1477 <= icmp7_fu_674_p2;
        or_cond_i_reg_1495 <= or_cond_i_fu_716_p2;
        p_p2_i_i_reg_1484 <= p_p2_i_i_fu_698_p3;
        tmp_139_reg_1471 <= ImagLoc_x_fu_650_p2[ap_const_lv32_B];
        tmp_142_reg_1490 <= {{p_p2_i_i_fu_698_p3[ap_const_lv32_B : ap_const_lv32_A]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_s_phi_fu_274_p4 == ap_const_lv1_0))) begin
        OP2_V_0_1_cast_reg_1300 <= OP2_V_0_1_cast_fu_309_p1;
        OP2_V_0_2_cast_reg_1305 <= OP2_V_0_2_cast_fu_312_p1;
        OP2_V_1_2_cast_reg_1315[3 : 0] <= OP2_V_1_2_cast_fu_318_p1[3 : 0];
        OP2_V_1_cast_reg_1310 <= OP2_V_1_cast_fu_315_p1;
        OP2_V_2_1_cast_reg_1325[2 : 0] <= OP2_V_2_1_cast_fu_324_p1[2 : 0];
        OP2_V_2_cast_reg_1320 <= OP2_V_2_cast_fu_321_p1;
    end
end

always @ (posedge ap_clk) begin
    if (~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
        ap_reg_ppstg_brmerge_reg_1513_pp0_it2 <= brmerge_reg_1513;
        ap_reg_ppstg_exitcond_reg_1457_pp0_it2 <= ap_reg_ppstg_exitcond_reg_1457_pp0_it1;
        ap_reg_ppstg_exitcond_reg_1457_pp0_it3 <= ap_reg_ppstg_exitcond_reg_1457_pp0_it2;
        ap_reg_ppstg_exitcond_reg_1457_pp0_it4 <= ap_reg_ppstg_exitcond_reg_1457_pp0_it3;
        ap_reg_ppstg_exitcond_reg_1457_pp0_it5 <= ap_reg_ppstg_exitcond_reg_1457_pp0_it4;
        ap_reg_ppstg_isneg_reg_1691_pp0_it11 <= isneg_reg_1691;
        ap_reg_ppstg_k_buf_0_val_4_addr_reg_1531_pp0_it3 <= k_buf_0_val_4_addr_reg_1531;
        ap_reg_ppstg_k_buf_0_val_5_addr_reg_1537_pp0_it3 <= k_buf_0_val_5_addr_reg_1537;
        ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2 <= or_cond_i_i_reg_1499;
        ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3 <= ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2;
        ap_reg_ppstg_or_cond_i_reg_1495_pp0_it10 <= ap_reg_ppstg_or_cond_i_reg_1495_pp0_it9;
        ap_reg_ppstg_or_cond_i_reg_1495_pp0_it11 <= ap_reg_ppstg_or_cond_i_reg_1495_pp0_it10;
        ap_reg_ppstg_or_cond_i_reg_1495_pp0_it2 <= ap_reg_ppstg_or_cond_i_reg_1495_pp0_it1;
        ap_reg_ppstg_or_cond_i_reg_1495_pp0_it3 <= ap_reg_ppstg_or_cond_i_reg_1495_pp0_it2;
        ap_reg_ppstg_or_cond_i_reg_1495_pp0_it4 <= ap_reg_ppstg_or_cond_i_reg_1495_pp0_it3;
        ap_reg_ppstg_or_cond_i_reg_1495_pp0_it5 <= ap_reg_ppstg_or_cond_i_reg_1495_pp0_it4;
        ap_reg_ppstg_or_cond_i_reg_1495_pp0_it6 <= ap_reg_ppstg_or_cond_i_reg_1495_pp0_it5;
        ap_reg_ppstg_or_cond_i_reg_1495_pp0_it7 <= ap_reg_ppstg_or_cond_i_reg_1495_pp0_it6;
        ap_reg_ppstg_or_cond_i_reg_1495_pp0_it8 <= ap_reg_ppstg_or_cond_i_reg_1495_pp0_it7;
        ap_reg_ppstg_or_cond_i_reg_1495_pp0_it9 <= ap_reg_ppstg_or_cond_i_reg_1495_pp0_it8;
        ap_reg_ppstg_p_Val2_5_reg_1697_pp0_it11 <= p_Val2_5_reg_1697;
        ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1583_pp0_it5 <= src_kernel_win_0_val_0_0_reg_1583;
        ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1583_pp0_it6 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1583_pp0_it5;
        ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1583_pp0_it7 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1583_pp0_it6;
        ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1583_pp0_it8 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1583_pp0_it7;
        ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1589_pp0_it5 <= src_kernel_win_0_val_1_0_reg_1589;
        ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1589_pp0_it6 <= ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1589_pp0_it5;
        src_kernel_win_0_val_0_0_reg_1583 <= src_kernel_win_0_val_0_0_fu_924_p3;
        src_kernel_win_0_val_1_0_reg_1589 <= src_kernel_win_0_val_1_0_fu_938_p3;
        src_kernel_win_0_val_2_0_reg_1595 <= src_kernel_win_0_val_2_0_fu_952_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        ap_reg_ppstg_exitcond_reg_1457_pp0_it1 <= exitcond_reg_1457;
        ap_reg_ppstg_or_cond_i_reg_1495_pp0_it1 <= or_cond_i_reg_1495;
        ap_reg_ppstg_p_p2_i_i_reg_1484_pp0_it1 <= p_p2_i_i_reg_1484;
        exitcond_reg_1457 <= exitcond_fu_622_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == exitcond_reg_1457))) begin
        brmerge_reg_1513 <= brmerge_fu_772_p2;
        or_cond_i_i_reg_1499 <= or_cond_i_i_fu_729_p2;
        sel_tmp8_reg_1508 <= sel_tmp8_fu_766_p2;
        sel_tmp_reg_1503 <= sel_tmp_fu_748_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it2) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        col_buf_0_val_0_0_reg_1548 <= col_buf_0_val_0_0_fu_835_p3;
        col_buf_0_val_1_0_reg_1561 <= col_buf_0_val_1_0_fu_854_p3;
        col_buf_0_val_2_0_reg_1569 <= col_buf_0_val_2_0_fu_873_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        i_V_reg_1333 <= i_V_fu_337_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_331_p2))) begin
        icmp4_reg_1372 <= icmp4_fu_417_p2;
        icmp_reg_1347 <= icmp_fu_369_p2;
        tmp_114_reg_1342 <= p_014_0_i_reg_281[ap_const_lv32_A];
        tmp_117_reg_1367 <= tmp_45_fu_393_p2[ap_const_lv32_B];
        tmp_120_reg_1377 <= {{p_p2_i423_i_fu_441_p3[ap_const_lv32_B : ap_const_lv32_A]}};
        tmp_121_reg_1382 <= tmp_121_fu_459_p1;
        tmp_122_reg_1387 <= p_assign_6_1_fu_463_p2[ap_const_lv32_A];
        tmp_125_reg_1392 <= p_assign_6_2_fu_489_p2[ap_const_lv32_A];
        tmp_128_reg_1397 <= tmp_128_fu_515_p1;
        tmp_129_reg_1402 <= tmp_129_fu_519_p1;
        tmp_132_reg_1407 <= tmp_132_fu_523_p1;
        tmp_134_reg_1412 <= tmp_134_fu_533_p3;
        tmp_135_reg_1417 <= tmp_135_fu_541_p1;
        tmp_137_reg_1422 <= tmp_137_fu_551_p3;
        tmp_208_1_reg_1356 <= tmp_208_1_fu_381_p2;
        tmp_43_reg_1352 <= tmp_43_fu_375_p2;
        tmp_44_reg_1360 <= tmp_44_fu_387_p2;
        tmp_reg_1338 <= p_014_0_i_reg_281[ap_const_lv32_A];
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_reg_1495_pp0_it9))) begin
        isneg_reg_1691 <= p_Val2_4_fu_1126_p2[ap_const_lv32_B];
        p_Val2_5_reg_1697 <= p_Val2_5_fu_1140_p1;
        tmp_70_reg_1702 <= {{p_Val2_4_fu_1126_p2[ap_const_lv32_B : ap_const_lv32_8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it1))) begin
        k_buf_0_val_3_addr_reg_1525 <= tmp_60_fu_793_p1;
        k_buf_0_val_4_addr_reg_1531 <= tmp_60_fu_793_p1;
        k_buf_0_val_5_addr_reg_1537 <= tmp_60_fu_793_p1;
        tmp_143_reg_1520 <= tmp_143_fu_789_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        k_buf_0_val_3_load_reg_1543 <= k_buf_0_val_3_q0;
        k_buf_0_val_4_load_reg_1556 <= k_buf_0_val_4_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_reg_1495_pp0_it10))) begin
        overflow_reg_1712 <= overflow_fu_1164_p2;
        tmp_i_i_reg_1707 <= tmp_i_i_fu_1154_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_reg_1495_pp0_it6))) begin
        p_Val2_0_1_reg_1641 <= grp_fu_965_p2;
        p_Val2_0_2_reg_1646 <= grp_fu_973_p2;
        p_Val2_s_reg_1636 <= p_Val2_s_fu_1055_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_reg_1495_pp0_it7))) begin
        p_Val2_13_0_2_reg_1656 <= p_Val2_13_0_2_fu_1084_p2;
        p_Val2_1_reg_1661 <= grp_fu_1001_p2;
        p_Val2_2_1_reg_1671 <= grp_fu_1019_p2;
        p_Val2_2_reg_1666 <= grp_fu_1010_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_reg_1495_pp0_it8))) begin
        p_Val2_13_1_1_reg_1676 <= p_Val2_13_1_1_fu_1096_p2;
        p_Val2_1_2_reg_1681 <= grp_fu_1064_p2;
        tmp3_reg_1686 <= tmp3_fu_1114_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2) & ~(ap_const_lv1_0 == icmp_reg_1347) & (ap_const_lv1_0 == tmp_reg_1338) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        right_border_buf_0_val_0_1_2_fu_158 <= right_border_buf_0_val_0_1_fu_154;
        right_border_buf_0_val_0_1_fu_154 <= col_buf_0_val_0_0_fu_835_p3;
        right_border_buf_0_val_1_1_2_fu_170 <= right_border_buf_0_val_1_1_fu_166;
        right_border_buf_0_val_1_1_fu_166 <= col_buf_0_val_1_0_fu_854_p3;
        right_border_buf_0_val_2_1_3_fu_174 <= col_buf_0_val_2_0_fu_873_p3;
        right_border_buf_0_val_2_1_fu_162 <= right_border_buf_0_val_2_1_3_fu_174;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_const_lv1_0 == tmp_44_reg_1360) & (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4))) begin
        row_assign_10_1_t_reg_1447 <= row_assign_10_1_t_fu_608_p2;
        row_assign_10_2_t_reg_1452 <= row_assign_10_2_t_fu_613_p2;
        row_assign_s_reg_1442 <= row_assign_s_fu_603_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it5))) begin
        src_kernel_win_0_val_0_1_2_fu_134 <= src_kernel_win_0_val_0_1_fu_130;
        src_kernel_win_0_val_0_1_fu_130 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1583_pp0_it5;
        src_kernel_win_0_val_1_1_2_fu_142 <= src_kernel_win_0_val_1_1_fu_138;
        src_kernel_win_0_val_1_1_fu_138 <= ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1589_pp0_it5;
        src_kernel_win_0_val_2_1_2_fu_150 <= src_kernel_win_0_val_2_1_lo_2_reg_1611;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_reg_1495_pp0_it5))) begin
        src_kernel_win_0_val_2_1_2_s_reg_1616 <= src_kernel_win_0_val_2_1_2_fu_150;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it4))) begin
        src_kernel_win_0_val_2_1_fu_146 <= src_kernel_win_0_val_2_0_reg_1595;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it4))) begin
        src_kernel_win_0_val_2_1_lo_2_reg_1611 <= src_kernel_win_0_val_2_1_fu_146;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_lv1_0 == tmp_44_reg_1360))) begin
        tmp_106_reg_1427 <= tmp_106_fu_586_p3;
        tmp_107_reg_1432 <= tmp_107_fu_593_p3;
        tmp_108_reg_1437 <= tmp_108_fu_598_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2) & (ap_const_lv1_0 == icmp_reg_1347) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        tmp_149_reg_1577 <= p_src_data_stream_V_dout;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st3_fsm_2 or exitcond1_fu_331_p2) begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == exitcond1_fu_331_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st3_fsm_2 or exitcond1_fu_331_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == exitcond1_fu_331_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_171) begin
    if (ap_sig_bdd_171) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_5 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_460) begin
    if (ap_sig_bdd_460) begin
        ap_sig_cseq_ST_st19_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st19_fsm_6 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_25) begin
    if (ap_sig_bdd_25) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_68) begin
    if (ap_sig_bdd_68) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_93) begin
    if (ap_sig_bdd_93) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_141) begin
    if (ap_sig_bdd_141) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_157) begin
    if (ap_sig_bdd_157) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_5 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        grp_fu_1001_ce = ap_const_logic_1;
    end else begin
        grp_fu_1001_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_5 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        grp_fu_1010_ce = ap_const_logic_1;
    end else begin
        grp_fu_1010_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_5 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        grp_fu_1019_ce = ap_const_logic_1;
    end else begin
        grp_fu_1019_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_5 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        grp_fu_1064_ce = ap_const_logic_1;
    end else begin
        grp_fu_1064_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_5 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        grp_fu_965_ce = ap_const_logic_1;
    end else begin
        grp_fu_965_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_5 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        grp_fu_973_ce = ap_const_logic_1;
    end else begin
        grp_fu_973_ce = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it2 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        k_buf_0_val_3_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_3_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_reg_1338 or icmp_reg_1347 or tmp_43_reg_1352 or ap_reg_ppstg_exitcond_reg_1457_pp0_it2 or ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12) begin
    if ((((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2) & ~(ap_const_lv1_0 == icmp_reg_1347) & (ap_const_lv1_0 == tmp_reg_1338) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2) & (ap_const_lv1_0 == icmp_reg_1347) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == tmp_43_reg_1352)))) begin
        k_buf_0_val_3_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_3_ce1 = ap_const_logic_0;
    end
end

always @ (tmp_reg_1338 or icmp_reg_1347 or tmp_43_reg_1352 or ap_reg_ppstg_exitcond_reg_1457_pp0_it2 or ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12) begin
    if ((((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2) & ~(ap_const_lv1_0 == icmp_reg_1347) & (ap_const_lv1_0 == tmp_reg_1338) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2) & (ap_const_lv1_0 == icmp_reg_1347) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == tmp_43_reg_1352)))) begin
        k_buf_0_val_3_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_3_we1 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it2 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        k_buf_0_val_4_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_4_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_reg_1338 or icmp_reg_1347 or tmp_208_1_reg_1356 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3) begin
    if ((((ap_const_lv1_0 == icmp_reg_1347) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3) & ~(ap_const_lv1_0 == tmp_208_1_reg_1356)) | (~(ap_const_lv1_0 == icmp_reg_1347) & (ap_const_lv1_0 == tmp_reg_1338) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3)))) begin
        k_buf_0_val_4_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_4_ce1 = ap_const_logic_0;
    end
end

always @ (k_buf_0_val_3_load_reg_1543 or tmp_149_reg_1577 or ap_sig_bdd_1118 or ap_sig_bdd_1120 or ap_sig_bdd_1117) begin
    if (ap_sig_bdd_1117) begin
        if (ap_sig_bdd_1120) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_load_reg_1543;
        end else if (ap_sig_bdd_1118) begin
            k_buf_0_val_4_d1 = tmp_149_reg_1577;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (tmp_reg_1338 or icmp_reg_1347 or tmp_208_1_reg_1356 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3) begin
    if ((((ap_const_lv1_0 == icmp_reg_1347) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3) & ~(ap_const_lv1_0 == tmp_208_1_reg_1356)) | (~(ap_const_lv1_0 == icmp_reg_1347) & (ap_const_lv1_0 == tmp_reg_1338) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3)))) begin
        k_buf_0_val_4_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_4_we1 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it2 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        k_buf_0_val_5_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_5_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_reg_1338 or icmp_reg_1347 or tmp_43_reg_1352 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3) begin
    if (((~(ap_const_lv1_0 == icmp_reg_1347) & (ap_const_lv1_0 == tmp_reg_1338) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3)) | ((ap_const_lv1_0 == icmp_reg_1347) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == tmp_43_reg_1352) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3)))) begin
        k_buf_0_val_5_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_5_ce1 = ap_const_logic_0;
    end
end

always @ (k_buf_0_val_4_load_reg_1556 or tmp_149_reg_1577 or ap_sig_bdd_1120 or ap_sig_bdd_1117 or ap_sig_bdd_1123) begin
    if (ap_sig_bdd_1117) begin
        if (ap_sig_bdd_1120) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_load_reg_1556;
        end else if (ap_sig_bdd_1123) begin
            k_buf_0_val_5_d1 = tmp_149_reg_1577;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (tmp_reg_1338 or icmp_reg_1347 or tmp_43_reg_1352 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3) begin
    if (((~(ap_const_lv1_0 == icmp_reg_1347) & (ap_const_lv1_0 == tmp_reg_1338) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3)) | ((ap_const_lv1_0 == icmp_reg_1347) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == tmp_43_reg_1352) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3)))) begin
        k_buf_0_val_5_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_5_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_reg_ppstg_or_cond_i_reg_1495_pp0_it11 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12) begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_reg_1495_pp0_it11) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        p_dst_data_stream_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_V_write = ap_const_logic_0;
    end
end

always @ (tmp_reg_1338 or icmp_reg_1347 or ap_reg_ppstg_exitcond_reg_1457_pp0_it2 or ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12) begin
    if ((((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2) & (ap_const_lv1_0 == icmp_reg_1347) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2) & ~(ap_const_lv1_0 == icmp_reg_1347) & (ap_const_lv1_0 == tmp_reg_1338) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))))) begin
        p_src_data_stream_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_V_read = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or tmp_s_phi_fu_274_p4 or exitcond1_fu_331_p2 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_196 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it11 or ap_sig_bdd_222 or ap_reg_ppiten_pp0_it12) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((tmp_s_phi_fu_274_p4 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            if (~(ap_const_lv1_0 == exitcond1_fu_331_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_5;
        end
        ap_ST_pp0_stg0_fsm_5 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it12) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it11)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_5;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it12) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it11)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_196 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_222 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
                ap_NS_fsm = ap_ST_st19_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_5;
            end
        end
        ap_ST_st19_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign ImagLoc_x_cast_fu_721_p1 = $signed(ImagLoc_x_reg_1466);

assign ImagLoc_x_fu_650_p2 = ($signed(ap_const_lv12_FFF) + $signed(tmp_53_cast_cast_fu_618_p1));

assign OP1_V_0_cast_fu_1052_p1 = src_kernel_win_0_val_2_1_2_s_reg_1616;

assign OP2_V_0_1_cast_fu_309_p1 = $signed(p_kernel_val_0_V_1_read);

assign OP2_V_0_2_cast_fu_312_p1 = $signed(p_kernel_val_0_V_2_read);

assign OP2_V_1_2_cast_fu_318_p1 = p_kernel_val_1_V_2_read;

assign OP2_V_1_cast_fu_315_p1 = $signed(p_kernel_val_1_V_0_read);

assign OP2_V_2_1_cast_fu_324_p1 = p_kernel_val_2_V_1_read;

assign OP2_V_2_cast_fu_321_p1 = $signed(p_kernel_val_2_V_0_read);


always @ (ap_reg_ppiten_pp0_it4 or ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3) begin
    ap_sig_bdd_1117 = ((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it3));
end


always @ (icmp_reg_1347 or tmp_208_1_reg_1356) begin
    ap_sig_bdd_1118 = ((ap_const_lv1_0 == icmp_reg_1347) & ~(ap_const_lv1_0 == tmp_208_1_reg_1356));
end


always @ (tmp_reg_1338 or icmp_reg_1347) begin
    ap_sig_bdd_1120 = (~(ap_const_lv1_0 == icmp_reg_1347) & (ap_const_lv1_0 == tmp_reg_1338));
end


always @ (icmp_reg_1347 or tmp_43_reg_1352) begin
    ap_sig_bdd_1123 = ((ap_const_lv1_0 == icmp_reg_1347) & ~(ap_const_lv1_0 == tmp_43_reg_1352));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_141 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_157 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_171 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end


always @ (p_src_data_stream_V_empty_n or tmp_reg_1338 or icmp_reg_1347 or ap_reg_ppstg_exitcond_reg_1457_pp0_it2 or ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2) begin
    ap_sig_bdd_196 = (((p_src_data_stream_V_empty_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2) & (ap_const_lv1_0 == icmp_reg_1347)) | ((p_src_data_stream_V_empty_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1457_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1499_pp0_it2) & ~(ap_const_lv1_0 == icmp_reg_1347) & (ap_const_lv1_0 == tmp_reg_1338)));
end


always @ (p_dst_data_stream_V_full_n or ap_reg_ppstg_or_cond_i_reg_1495_pp0_it11) begin
    ap_sig_bdd_222 = ((p_dst_data_stream_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_reg_1495_pp0_it11));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_25 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_460 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_68 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_93 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

assign brmerge_fu_772_p2 = (tmp_114_reg_1342 | icmp7_reg_1477);

assign col_assign_3_t_fu_818_p2 = (tmp_143_reg_1520 ^ ap_const_lv2_3);

assign col_assign_cast_fu_785_p1 = $signed(x_fu_779_p3);

assign col_buf_0_val_0_0_fu_835_p3 = ((ap_reg_ppstg_brmerge_reg_1513_pp0_it2[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_61_fu_823_p5);

assign col_buf_0_val_1_0_fu_854_p3 = ((ap_reg_ppstg_brmerge_reg_1513_pp0_it2[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_62_fu_842_p5);

assign col_buf_0_val_2_0_fu_873_p3 = ((ap_reg_ppstg_brmerge_reg_1513_pp0_it2[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_63_fu_861_p5);

assign exitcond1_fu_331_p2 = (p_014_0_i_reg_281 == ap_const_lv11_402? 1'b1: 1'b0);

assign exitcond_fu_622_p2 = (p_027_0_i_reg_292 == ap_const_lv11_402? 1'b1: 1'b0);

assign grp_fu_1001_p0 = OP2_V_1_cast_reg_1310;

assign grp_fu_1001_p1 = grp_fu_1001_p10;

assign grp_fu_1001_p10 = src_kernel_win_0_val_1_1_2_fu_142;

assign grp_fu_1010_p0 = OP2_V_2_cast_reg_1320;

assign grp_fu_1010_p1 = grp_fu_1010_p10;

assign grp_fu_1010_p10 = src_kernel_win_0_val_0_1_2_fu_134;

assign grp_fu_1019_p0 = OP2_V_2_1_cast_reg_1325;

assign grp_fu_1019_p1 = grp_fu_1019_p10;

assign grp_fu_1019_p10 = src_kernel_win_0_val_0_1_fu_130;

assign grp_fu_1064_p0 = OP2_V_1_2_cast_reg_1315;

assign grp_fu_1064_p1 = grp_fu_1064_p10;

assign grp_fu_1064_p10 = ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1589_pp0_it6;

assign grp_fu_965_p0 = OP2_V_0_1_cast_reg_1300;

assign grp_fu_965_p1 = grp_fu_965_p10;

assign grp_fu_965_p10 = src_kernel_win_0_val_2_1_fu_146;

assign grp_fu_973_p0 = OP2_V_0_2_cast_reg_1305;

assign grp_fu_973_p1 = grp_fu_973_p10;

assign grp_fu_973_p10 = src_kernel_win_0_val_2_0_reg_1595;

assign i_V_fu_337_p2 = (p_014_0_i_reg_281 + ap_const_lv11_1);

assign icmp4_fu_417_p2 = (tmp_118_fu_407_p4 != ap_const_lv2_1? 1'b1: 1'b0);

assign icmp54_not_fu_756_p2 = (icmp7_reg_1477 ^ ap_const_lv1_1);

assign icmp5_fu_569_p2 = (tmp_120_reg_1377 != ap_const_lv2_1? 1'b1: 1'b0);

assign icmp6_fu_644_p2 = (tmp_138_fu_634_p4 != ap_const_lv10_0? 1'b1: 1'b0);

assign icmp7_fu_674_p2 = (tmp_140_fu_664_p4 != ap_const_lv2_1? 1'b1: 1'b0);

assign icmp8_fu_734_p2 = (tmp_142_reg_1490 != ap_const_lv2_1? 1'b1: 1'b0);

assign icmp_fu_369_p2 = (tmp_115_fu_359_p4 != ap_const_lv10_0? 1'b1: 1'b0);

assign j_V_fu_628_p2 = (p_027_0_i_reg_292 + ap_const_lv11_1);

assign k_buf_0_val_3_address0 = tmp_60_fu_793_p1;

assign k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_1525;

assign k_buf_0_val_3_d1 = p_src_data_stream_V_dout;

assign k_buf_0_val_4_address0 = tmp_60_fu_793_p1;

assign k_buf_0_val_4_address1 = ap_reg_ppstg_k_buf_0_val_4_addr_reg_1531_pp0_it3;

assign k_buf_0_val_5_address0 = tmp_60_fu_793_p1;

assign k_buf_0_val_5_address1 = ap_reg_ppstg_k_buf_0_val_5_addr_reg_1537_pp0_it3;

assign not_i_i_i_fu_1159_p2 = (tmp_70_reg_1702 != ap_const_lv4_0? 1'b1: 1'b0);

assign or_cond_i422_i_fu_564_p2 = (icmp4_reg_1372 & rev_fu_559_p2);

assign or_cond_i_fu_716_p2 = (icmp_reg_1347 & icmp6_fu_644_p2);

assign or_cond_i_i_fu_729_p2 = (icmp7_reg_1477 & rev7_fu_724_p2);

assign overflow_fu_1164_p2 = (not_i_i_i_fu_1159_p2 & tmp_i_i_fu_1154_p2);

assign p_Val2_13_0_1_fu_1075_p2 = ($signed(tmp_252_0_cast_fu_1069_p1) + $signed(tmp_252_0_1_cast_fu_1072_p1));

assign p_Val2_13_0_2_cast6_fu_1090_p1 = $signed(p_Val2_13_0_2_reg_1656);

assign p_Val2_13_0_2_fu_1084_p2 = ($signed(tmp_252_0_2_cast_cast_fu_1081_p1) + $signed(p_Val2_13_0_1_fu_1075_p2));

assign p_Val2_13_1_1_fu_1096_p2 = ($signed(tmp_252_1_cast_cast_fu_1093_p1) + $signed(p_Val2_13_0_2_cast6_fu_1090_p1));

assign p_Val2_4_fu_1126_p2 = ($signed(tmp2_fu_1119_p2) + $signed(tmp3_cast_fu_1123_p1));

assign p_Val2_5_fu_1140_p1 = p_Val2_4_fu_1126_p2[7:0];

assign p_Val2_s_fu_1055_p2 = (ap_const_lv9_0 - OP1_V_0_cast_fu_1052_p1);

assign p_assign_1_cast_fu_694_p1 = $signed(p_assign_1_fu_688_p2);

assign p_assign_1_fu_688_p2 = (ap_const_lv11_1 - p_027_0_i_reg_292);

assign p_assign_2_cast_fu_744_p1 = p_assign_2_fu_739_p2;

assign p_assign_2_fu_739_p2 = (ap_const_lv12_7FE - p_p2_i_i_reg_1484);

assign p_assign_6_1_fu_463_p2 = ($signed(ap_const_lv11_7FE) + $signed(p_014_0_i_reg_281));

assign p_assign_6_2_fu_489_p2 = ($signed(ap_const_lv11_7FD) + $signed(p_014_0_i_reg_281));

assign p_assign_7_cast_fu_437_p1 = $signed(p_assign_7_fu_431_p2);

assign p_assign_7_fu_431_p2 = (ap_const_lv11_1 - p_014_0_i_reg_281);

assign p_dst_data_stream_V_din = ((tmp_i_i_78_fu_1177_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_1170_p3 : ap_reg_ppstg_p_Val2_5_reg_1697_pp0_it11);

assign p_mux_i_i_cast_fu_1170_p3 = ((tmp_i_i_reg_1707[0:0] === 1'b1) ? ap_const_lv8_FF : ap_const_lv8_0);

assign p_p2_i423_i_fu_441_p3 = ((tmp_119_fu_423_p3[0:0] === 1'b1) ? p_assign_7_cast_fu_437_p1 : tmp_45_fu_393_p2);

assign p_p2_i_i_cast_cast8_fu_776_p1 = $signed(ap_reg_ppstg_p_p2_i_i_reg_1484_pp0_it1);

assign p_p2_i_i_fu_698_p3 = ((tmp_141_fu_680_p3[0:0] === 1'b1) ? p_assign_1_cast_fu_694_p1 : ImagLoc_x_fu_650_p2);

assign rev7_fu_724_p2 = (tmp_139_reg_1471 ^ ap_const_lv1_1);

assign rev_fu_559_p2 = (tmp_117_reg_1367 ^ ap_const_lv1_1);

assign row_assign_10_1_t_fu_608_p2 = (tmp_107_reg_1432 ^ ap_const_lv2_3);

assign row_assign_10_2_t_fu_613_p2 = (tmp_108_reg_1437 ^ ap_const_lv2_3);

assign row_assign_s_fu_603_p2 = (tmp_106_reg_1427 ^ ap_const_lv2_3);

assign sel_tmp7_fu_761_p2 = (tmp_139_reg_1471 | icmp54_not_fu_756_p2);

assign sel_tmp8_fu_766_p2 = (icmp8_fu_734_p2 & sel_tmp7_fu_761_p2);

assign sel_tmp_fu_748_p3 = ((or_cond_i_i_fu_729_p2[0:0] === 1'b1) ? ImagLoc_x_cast_fu_721_p1 : p_assign_2_cast_fu_744_p1);

assign src_kernel_win_0_val_0_0_fu_924_p3 = ((tmp_44_reg_1360[0:0] === 1'b1) ? tmp_65_fu_916_p5 : col_buf_0_val_0_0_reg_1548);

assign src_kernel_win_0_val_1_0_fu_938_p3 = ((tmp_44_reg_1360[0:0] === 1'b1) ? tmp_67_fu_930_p5 : col_buf_0_val_1_0_reg_1561);

assign src_kernel_win_0_val_2_0_fu_952_p3 = ((tmp_44_reg_1360[0:0] === 1'b1) ? tmp_69_fu_944_p5 : col_buf_0_val_2_0_reg_1569);

assign tmp2_fu_1119_p2 = (p_Val2_1_2_reg_1681 + p_Val2_13_1_1_reg_1676);

assign tmp3_cast_fu_1123_p1 = $signed(tmp3_reg_1686);

assign tmp3_fu_1114_p2 = ($signed(p_Val2_2_1_reg_1671) + $signed(tmp4_cast_fu_1110_p1));

assign tmp4_cast_fu_1110_p1 = $signed(tmp4_fu_1105_p2);

assign tmp4_fu_1105_p2 = (tmp_252_2_2_cast_cast_cast_fu_1102_p1 + p_Val2_2_reg_1666);

assign tmp_106_fu_586_p3 = ((or_cond_i422_i_fu_564_p2[0:0] === 1'b1) ? tmp_128_reg_1397 : tmp_131_fu_579_p3);

assign tmp_107_fu_593_p3 = ((tmp_122_reg_1387[0:0] === 1'b1) ? tmp_134_reg_1412 : tmp_132_reg_1407);

assign tmp_108_fu_598_p3 = ((tmp_125_reg_1392[0:0] === 1'b1) ? tmp_137_reg_1422 : tmp_135_reg_1417);

assign tmp_115_fu_359_p4 = {{p_014_0_i_reg_281[ap_const_lv32_A : ap_const_lv32_1]}};

assign tmp_118_fu_407_p4 = {{tmp_45_fu_393_p2[ap_const_lv32_B : ap_const_lv32_A]}};

assign tmp_119_fu_423_p3 = tmp_45_fu_393_p2[ap_const_lv32_B];

assign tmp_121_fu_459_p1 = p_p2_i423_i_fu_441_p3[1:0];

assign tmp_123_fu_477_p3 = p_assign_6_1_fu_463_p2[ap_const_lv32_A];

assign tmp_124_fu_485_p1 = p_014_0_i_reg_281[1:0];

assign tmp_126_fu_503_p3 = p_assign_6_2_fu_489_p2[ap_const_lv32_A];

assign tmp_127_fu_511_p1 = p_014_0_i_reg_281[1:0];

assign tmp_128_fu_515_p1 = tmp_45_fu_393_p2[1:0];

assign tmp_129_fu_519_p1 = p_p2_i423_i_fu_441_p3[1:0];

assign tmp_130_fu_574_p2 = ($signed(ap_const_lv2_2) - $signed(tmp_121_reg_1382));

assign tmp_131_fu_579_p3 = ((icmp5_fu_569_p2[0:0] === 1'b1) ? tmp_129_reg_1402 : tmp_130_fu_574_p2);

assign tmp_132_fu_523_p1 = p_assign_6_1_fu_463_p2[1:0];

assign tmp_133_fu_527_p2 = ($signed(ap_const_lv2_2) - $signed(tmp_124_fu_485_p1));

assign tmp_134_fu_533_p3 = ((tmp_123_fu_477_p3[0:0] === 1'b1) ? tmp_133_fu_527_p2 : tmp_132_fu_523_p1);

assign tmp_135_fu_541_p1 = p_assign_6_2_fu_489_p2[1:0];

assign tmp_136_fu_545_p2 = (tmp_127_fu_511_p1 ^ ap_const_lv2_3);

assign tmp_137_fu_551_p3 = ((tmp_126_fu_503_p3[0:0] === 1'b1) ? tmp_136_fu_545_p2 : tmp_135_fu_541_p1);

assign tmp_138_fu_634_p4 = {{p_027_0_i_reg_292[ap_const_lv32_A : ap_const_lv32_1]}};

assign tmp_140_fu_664_p4 = {{ImagLoc_x_fu_650_p2[ap_const_lv32_B : ap_const_lv32_A]}};

assign tmp_141_fu_680_p3 = ImagLoc_x_fu_650_p2[ap_const_lv32_B];

assign tmp_143_fu_789_p1 = x_fu_779_p3[1:0];

assign tmp_208_1_fu_381_p2 = (p_014_0_i_reg_281 == ap_const_lv11_0? 1'b1: 1'b0);

assign tmp_252_0_1_cast_fu_1072_p1 = $signed(p_Val2_0_1_reg_1641);

assign tmp_252_0_2_cast_cast_fu_1081_p1 = $signed(p_Val2_0_2_reg_1646);

assign tmp_252_0_cast_fu_1069_p1 = $signed(p_Val2_s_reg_1636);

assign tmp_252_1_cast_cast_fu_1093_p1 = $signed(p_Val2_1_reg_1661);

assign tmp_252_2_2_cast_cast_cast_fu_1102_p1 = ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1583_pp0_it8;

assign tmp_38_fu_303_p2 = (tmp_s_reg_270 ^ ap_const_lv1_1);

assign tmp_43_fu_375_p2 = (p_014_0_i_reg_281 == ap_const_lv11_1? 1'b1: 1'b0);

assign tmp_44_fu_387_p2 = (p_014_0_i_reg_281 > ap_const_lv11_400? 1'b1: 1'b0);

assign tmp_45_fu_393_p2 = ($signed(ap_const_lv12_FFF) + $signed(tmp_50_cast_cast_fu_327_p1));

assign tmp_50_cast_cast_fu_327_p1 = p_014_0_i_reg_281;

assign tmp_53_cast_cast_fu_618_p1 = p_027_0_i_reg_292;

assign tmp_60_fu_793_p1 = $unsigned(col_assign_cast_fu_785_p1);

assign tmp_i_i_78_fu_1177_p2 = (ap_reg_ppstg_isneg_reg_1691_pp0_it11 | overflow_reg_1712);

assign tmp_i_i_fu_1154_p2 = (isneg_reg_1691 ^ ap_const_lv1_1);

assign tmp_s_phi_fu_274_p4 = tmp_s_reg_270;

assign x_fu_779_p3 = ((sel_tmp8_reg_1508[0:0] === 1'b1) ? p_p2_i_i_cast_cast8_fu_776_p1 : sel_tmp_reg_1503);
always @ (posedge ap_clk) begin
    OP2_V_1_2_cast_reg_1315[11:4] <= 8'b00000000;
    OP2_V_2_1_cast_reg_1325[10:3] <= 8'b00000000;
end



endmodule //canny_Filter2D

