// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="canny,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.368000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=13,HLS_SYN_DSP=21,HLS_SYN_FF=2724,HLS_SYN_LUT=2677}" *)

module canny (
        input_stream_TDATA,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TUSER,
        input_stream_TLAST,
        input_stream_TID,
        input_stream_TDEST,
        output_stream_TDATA,
        output_stream_TKEEP,
        output_stream_TSTRB,
        output_stream_TUSER,
        output_stream_TLAST,
        output_stream_TID,
        output_stream_TDEST,
        ap_clk,
        ap_rst_n,
        ap_start,
        input_stream_TVALID,
        input_stream_TREADY,
        output_stream_TVALID,
        output_stream_TREADY,
        ap_done,
        ap_idle,
        ap_ready
);

parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_true = 1'b1;

input  [7:0] input_stream_TDATA;
input  [0:0] input_stream_TKEEP;
input  [0:0] input_stream_TSTRB;
input  [0:0] input_stream_TUSER;
input  [0:0] input_stream_TLAST;
input  [0:0] input_stream_TID;
input  [0:0] input_stream_TDEST;
output  [7:0] output_stream_TDATA;
output  [0:0] output_stream_TKEEP;
output  [0:0] output_stream_TSTRB;
output  [0:0] output_stream_TUSER;
output  [0:0] output_stream_TLAST;
output  [0:0] output_stream_TID;
output  [0:0] output_stream_TDEST;
input   ap_clk;
input   ap_rst_n;
input   ap_start;
input   input_stream_TVALID;
output   input_stream_TREADY;
output   output_stream_TVALID;
input   output_stream_TREADY;
output   ap_done;
output   ap_idle;
output   ap_ready;

reg ap_idle;
reg    ap_rst_n_inv;
wire    canny_Block_proc_U0_ap_start;
wire    canny_Block_proc_U0_ap_done;
wire    canny_Block_proc_U0_ap_continue;
wire    canny_Block_proc_U0_ap_idle;
wire    canny_Block_proc_U0_ap_ready;
wire   [11:0] canny_Block_proc_U0_img_0_rows_V_out_din;
wire    canny_Block_proc_U0_img_0_rows_V_out_full_n;
wire    canny_Block_proc_U0_img_0_rows_V_out_write;
wire   [11:0] canny_Block_proc_U0_img_0_cols_V_out_din;
wire    canny_Block_proc_U0_img_0_cols_V_out_full_n;
wire    canny_Block_proc_U0_img_0_cols_V_out_write;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_start;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_done;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_continue;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_idle;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_ready;
wire   [7:0] canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TDATA;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TVALID;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TREADY;
wire   [0:0] canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TKEEP;
wire   [0:0] canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TSTRB;
wire   [0:0] canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TUSER;
wire   [0:0] canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TLAST;
wire   [0:0] canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TID;
wire   [0:0] canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TDEST;
wire   [11:0] canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_dout;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_empty_n;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_read;
wire   [11:0] canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_dout;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_empty_n;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_read;
wire   [7:0] canny_AXIvideo2Mat_8_1024_1024_0_U0_img_data_stream_V_din;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_img_data_stream_V_full_n;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_img_data_stream_V_write;
wire   [11:0] canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_out_din;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_out_full_n;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_out_write;
wire   [11:0] canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_out_din;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_out_full_n;
wire    canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_out_write;
reg    canny_GaussianBlur_U0_ap_start = 1'b0;
wire    canny_GaussianBlur_U0_ap_done;
wire    canny_GaussianBlur_U0_ap_continue;
wire    canny_GaussianBlur_U0_ap_idle;
wire    canny_GaussianBlur_U0_ap_ready;
wire   [11:0] canny_GaussianBlur_U0_p_src_rows_V_dout;
wire    canny_GaussianBlur_U0_p_src_rows_V_empty_n;
wire    canny_GaussianBlur_U0_p_src_rows_V_read;
wire   [11:0] canny_GaussianBlur_U0_p_src_cols_V_dout;
wire    canny_GaussianBlur_U0_p_src_cols_V_empty_n;
wire    canny_GaussianBlur_U0_p_src_cols_V_read;
wire   [7:0] canny_GaussianBlur_U0_p_src_data_stream_V_dout;
wire    canny_GaussianBlur_U0_p_src_data_stream_V_empty_n;
wire    canny_GaussianBlur_U0_p_src_data_stream_V_read;
wire   [7:0] canny_GaussianBlur_U0_p_dst_data_stream_V_din;
wire    canny_GaussianBlur_U0_p_dst_data_stream_V_full_n;
wire    canny_GaussianBlur_U0_p_dst_data_stream_V_write;
reg    canny_Duplicate_1024_1024_0_0_U0_ap_start = 1'b0;
wire    canny_Duplicate_1024_1024_0_0_U0_ap_done;
wire    canny_Duplicate_1024_1024_0_0_U0_ap_continue;
wire    canny_Duplicate_1024_1024_0_0_U0_ap_idle;
wire    canny_Duplicate_1024_1024_0_0_U0_ap_ready;
wire   [7:0] canny_Duplicate_1024_1024_0_0_U0_src_data_stream_V_dout;
wire    canny_Duplicate_1024_1024_0_0_U0_src_data_stream_V_empty_n;
wire    canny_Duplicate_1024_1024_0_0_U0_src_data_stream_V_read;
wire   [7:0] canny_Duplicate_1024_1024_0_0_U0_dst1_data_stream_V_din;
wire    canny_Duplicate_1024_1024_0_0_U0_dst1_data_stream_V_full_n;
wire    canny_Duplicate_1024_1024_0_0_U0_dst1_data_stream_V_write;
wire   [7:0] canny_Duplicate_1024_1024_0_0_U0_dst2_data_stream_V_din;
wire    canny_Duplicate_1024_1024_0_0_U0_dst2_data_stream_V_full_n;
wire    canny_Duplicate_1024_1024_0_0_U0_dst2_data_stream_V_write;
reg    canny_Sobel_U0_ap_start = 1'b0;
wire    canny_Sobel_U0_ap_done;
wire    canny_Sobel_U0_ap_continue;
wire    canny_Sobel_U0_ap_idle;
wire    canny_Sobel_U0_ap_ready;
wire   [7:0] canny_Sobel_U0_p_src_data_stream_V_dout;
wire    canny_Sobel_U0_p_src_data_stream_V_empty_n;
wire    canny_Sobel_U0_p_src_data_stream_V_read;
wire   [7:0] canny_Sobel_U0_p_dst_data_stream_V_din;
wire    canny_Sobel_U0_p_dst_data_stream_V_full_n;
wire    canny_Sobel_U0_p_dst_data_stream_V_write;
reg    canny_Sobel_1_U0_ap_start = 1'b0;
wire    canny_Sobel_1_U0_ap_done;
wire    canny_Sobel_1_U0_ap_continue;
wire    canny_Sobel_1_U0_ap_idle;
wire    canny_Sobel_1_U0_ap_ready;
wire   [7:0] canny_Sobel_1_U0_p_src_data_stream_V_dout;
wire    canny_Sobel_1_U0_p_src_data_stream_V_empty_n;
wire    canny_Sobel_1_U0_p_src_data_stream_V_read;
wire   [7:0] canny_Sobel_1_U0_p_dst_data_stream_V_din;
wire    canny_Sobel_1_U0_p_dst_data_stream_V_full_n;
wire    canny_Sobel_1_U0_p_dst_data_stream_V_write;
reg    canny_grad_computation_U0_ap_start = 1'b0;
wire    canny_grad_computation_U0_ap_done;
wire    canny_grad_computation_U0_ap_continue;
wire    canny_grad_computation_U0_ap_idle;
wire    canny_grad_computation_U0_ap_ready;
wire   [7:0] canny_grad_computation_U0_grad_x_data_stream_V_dout;
wire    canny_grad_computation_U0_grad_x_data_stream_V_empty_n;
wire    canny_grad_computation_U0_grad_x_data_stream_V_read;
wire   [7:0] canny_grad_computation_U0_grad_y_data_stream_V_dout;
wire    canny_grad_computation_U0_grad_y_data_stream_V_empty_n;
wire    canny_grad_computation_U0_grad_y_data_stream_V_read;
wire   [15:0] canny_grad_computation_U0_grad_out_data_stream_V_din;
wire    canny_grad_computation_U0_grad_out_data_stream_V_full_n;
wire    canny_grad_computation_U0_grad_out_data_stream_V_write;
reg    canny_nonmax_supression_U0_ap_start = 1'b0;
wire    canny_nonmax_supression_U0_ap_done;
wire    canny_nonmax_supression_U0_ap_continue;
wire    canny_nonmax_supression_U0_ap_idle;
wire    canny_nonmax_supression_U0_ap_ready;
wire   [15:0] canny_nonmax_supression_U0_grad_out_data_stream_V_dout;
wire    canny_nonmax_supression_U0_grad_out_data_stream_V_empty_n;
wire    canny_nonmax_supression_U0_grad_out_data_stream_V_read;
wire   [7:0] canny_nonmax_supression_U0_supressed_data_stream_V_din;
wire    canny_nonmax_supression_U0_supressed_data_stream_V_full_n;
wire    canny_nonmax_supression_U0_supressed_data_stream_V_write;
reg    canny_hysterisis_U0_ap_start = 1'b0;
wire    canny_hysterisis_U0_ap_done;
wire    canny_hysterisis_U0_ap_continue;
wire    canny_hysterisis_U0_ap_idle;
wire    canny_hysterisis_U0_ap_ready;
wire   [7:0] canny_hysterisis_U0_supressed_data_stream_V_dout;
wire    canny_hysterisis_U0_supressed_data_stream_V_empty_n;
wire    canny_hysterisis_U0_supressed_data_stream_V_read;
wire   [7:0] canny_hysterisis_U0_hysterisis_Image_data_stream_V_din;
wire    canny_hysterisis_U0_hysterisis_Image_data_stream_V_full_n;
wire    canny_hysterisis_U0_hysterisis_Image_data_stream_V_write;
reg    canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_start = 1'b0;
wire    canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_done;
wire    canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_continue;
wire    canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_idle;
wire    canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_ready;
wire   [7:0] canny_Mat2AXIvideo_8_1022_1022_0_U0_img_data_stream_V_dout;
wire    canny_Mat2AXIvideo_8_1022_1022_0_U0_img_data_stream_V_empty_n;
wire    canny_Mat2AXIvideo_8_1022_1022_0_U0_img_data_stream_V_read;
wire   [7:0] canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TDATA;
wire    canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TVALID;
wire    canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TREADY;
wire   [0:0] canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TKEEP;
wire   [0:0] canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TSTRB;
wire   [0:0] canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TUSER;
wire   [0:0] canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TLAST;
wire   [0:0] canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TID;
wire   [0:0] canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TDEST;
wire    ap_sig_hs_continue;
wire    img_0_rows_V_channel_U_ap_dummy_ce;
wire   [11:0] img_0_rows_V_channel_din;
wire    img_0_rows_V_channel_full_n;
wire    img_0_rows_V_channel_write;
wire   [11:0] img_0_rows_V_channel_dout;
wire    img_0_rows_V_channel_empty_n;
wire    img_0_rows_V_channel_read;
wire    img_0_cols_V_channel_U_ap_dummy_ce;
wire   [11:0] img_0_cols_V_channel_din;
wire    img_0_cols_V_channel_full_n;
wire    img_0_cols_V_channel_write;
wire   [11:0] img_0_cols_V_channel_dout;
wire    img_0_cols_V_channel_empty_n;
wire    img_0_cols_V_channel_read;
wire    img_0_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_0_data_stream_0_V_din;
wire    img_0_data_stream_0_V_full_n;
wire    img_0_data_stream_0_V_write;
wire   [7:0] img_0_data_stream_0_V_dout;
wire    img_0_data_stream_0_V_empty_n;
wire    img_0_data_stream_0_V_read;
wire    img_0_rows_V_channel19_U_ap_dummy_ce;
wire   [11:0] img_0_rows_V_channel19_din;
wire    img_0_rows_V_channel19_full_n;
wire    img_0_rows_V_channel19_write;
wire   [11:0] img_0_rows_V_channel19_dout;
wire    img_0_rows_V_channel19_empty_n;
wire    img_0_rows_V_channel19_read;
wire    img_0_cols_V_channel20_U_ap_dummy_ce;
wire   [11:0] img_0_cols_V_channel20_din;
wire    img_0_cols_V_channel20_full_n;
wire    img_0_cols_V_channel20_write;
wire   [11:0] img_0_cols_V_channel20_dout;
wire    img_0_cols_V_channel20_empty_n;
wire    img_0_cols_V_channel20_read;
wire    img_1_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_1_data_stream_0_V_din;
wire    img_1_data_stream_0_V_full_n;
wire    img_1_data_stream_0_V_write;
wire   [7:0] img_1_data_stream_0_V_dout;
wire    img_1_data_stream_0_V_empty_n;
wire    img_1_data_stream_0_V_read;
wire    img_2_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_2_data_stream_0_V_din;
wire    img_2_data_stream_0_V_full_n;
wire    img_2_data_stream_0_V_write;
wire   [7:0] img_2_data_stream_0_V_dout;
wire    img_2_data_stream_0_V_empty_n;
wire    img_2_data_stream_0_V_read;
wire    img_3_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_3_data_stream_0_V_din;
wire    img_3_data_stream_0_V_full_n;
wire    img_3_data_stream_0_V_write;
wire   [7:0] img_3_data_stream_0_V_dout;
wire    img_3_data_stream_0_V_empty_n;
wire    img_3_data_stream_0_V_read;
wire    grad_x_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] grad_x_data_stream_0_V_din;
wire    grad_x_data_stream_0_V_full_n;
wire    grad_x_data_stream_0_V_write;
wire   [7:0] grad_x_data_stream_0_V_dout;
wire    grad_x_data_stream_0_V_empty_n;
wire    grad_x_data_stream_0_V_read;
wire    grad_y_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] grad_y_data_stream_0_V_din;
wire    grad_y_data_stream_0_V_full_n;
wire    grad_y_data_stream_0_V_write;
wire   [7:0] grad_y_data_stream_0_V_dout;
wire    grad_y_data_stream_0_V_empty_n;
wire    grad_y_data_stream_0_V_read;
wire    grad_out_data_stream_0_V_U_ap_dummy_ce;
wire   [15:0] grad_out_data_stream_0_V_din;
wire    grad_out_data_stream_0_V_full_n;
wire    grad_out_data_stream_0_V_write;
wire   [15:0] grad_out_data_stream_0_V_dout;
wire    grad_out_data_stream_0_V_empty_n;
wire    grad_out_data_stream_0_V_read;
wire    supressed_Image_data_stream_0_U_ap_dummy_ce;
wire   [7:0] supressed_Image_data_stream_0_din;
wire    supressed_Image_data_stream_0_full_n;
wire    supressed_Image_data_stream_0_write;
wire   [7:0] supressed_Image_data_stream_0_dout;
wire    supressed_Image_data_stream_0_empty_n;
wire    supressed_Image_data_stream_0_read;
wire    hysterisis_Image_data_stream_0_U_ap_dummy_ce;
wire   [7:0] hysterisis_Image_data_stream_0_din;
wire    hysterisis_Image_data_stream_0_full_n;
wire    hysterisis_Image_data_stream_0_write;
wire   [7:0] hysterisis_Image_data_stream_0_dout;
wire    hysterisis_Image_data_stream_0_empty_n;
wire    hysterisis_Image_data_stream_0_read;
reg    ap_reg_procdone_canny_Block_proc_U0 = 1'b0;
reg    ap_sig_hs_done;
reg    ap_reg_procdone_canny_AXIvideo2Mat_8_1024_1024_0_U0 = 1'b0;
reg    ap_reg_procdone_canny_GaussianBlur_U0 = 1'b0;
reg    ap_reg_procdone_canny_Duplicate_1024_1024_0_0_U0 = 1'b0;
reg    ap_reg_procdone_canny_Sobel_U0 = 1'b0;
reg    ap_reg_procdone_canny_Sobel_1_U0 = 1'b0;
reg    ap_reg_procdone_canny_grad_computation_U0 = 1'b0;
reg    ap_reg_procdone_canny_nonmax_supression_U0 = 1'b0;
reg    ap_reg_procdone_canny_hysterisis_U0 = 1'b0;
reg    ap_reg_procdone_canny_Mat2AXIvideo_8_1022_1022_0_U0 = 1'b0;
reg    ap_CS;
wire    ap_sig_top_allready;


canny_Block_proc canny_Block_proc_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( canny_Block_proc_U0_ap_start ),
    .ap_done( canny_Block_proc_U0_ap_done ),
    .ap_continue( canny_Block_proc_U0_ap_continue ),
    .ap_idle( canny_Block_proc_U0_ap_idle ),
    .ap_ready( canny_Block_proc_U0_ap_ready ),
    .img_0_rows_V_out_din( canny_Block_proc_U0_img_0_rows_V_out_din ),
    .img_0_rows_V_out_full_n( canny_Block_proc_U0_img_0_rows_V_out_full_n ),
    .img_0_rows_V_out_write( canny_Block_proc_U0_img_0_rows_V_out_write ),
    .img_0_cols_V_out_din( canny_Block_proc_U0_img_0_cols_V_out_din ),
    .img_0_cols_V_out_full_n( canny_Block_proc_U0_img_0_cols_V_out_full_n ),
    .img_0_cols_V_out_write( canny_Block_proc_U0_img_0_cols_V_out_write )
);

canny_AXIvideo2Mat_8_1024_1024_0_s canny_AXIvideo2Mat_8_1024_1024_0_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_start ),
    .ap_done( canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_done ),
    .ap_continue( canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_continue ),
    .ap_idle( canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_idle ),
    .ap_ready( canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_ready ),
    .input_stream_TDATA( canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TDATA ),
    .input_stream_TVALID( canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TVALID ),
    .input_stream_TREADY( canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TREADY ),
    .input_stream_TKEEP( canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TKEEP ),
    .input_stream_TSTRB( canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TSTRB ),
    .input_stream_TUSER( canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TUSER ),
    .input_stream_TLAST( canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TLAST ),
    .input_stream_TID( canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TID ),
    .input_stream_TDEST( canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TDEST ),
    .img_rows_V_dout( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_dout ),
    .img_rows_V_empty_n( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_empty_n ),
    .img_rows_V_read( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_read ),
    .img_cols_V_dout( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_dout ),
    .img_cols_V_empty_n( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_empty_n ),
    .img_cols_V_read( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_read ),
    .img_data_stream_V_din( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_data_stream_V_din ),
    .img_data_stream_V_full_n( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_data_stream_V_full_n ),
    .img_data_stream_V_write( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_data_stream_V_write ),
    .img_rows_V_out_din( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_out_din ),
    .img_rows_V_out_full_n( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_out_full_n ),
    .img_rows_V_out_write( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_out_write ),
    .img_cols_V_out_din( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_out_din ),
    .img_cols_V_out_full_n( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_out_full_n ),
    .img_cols_V_out_write( canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_out_write )
);

canny_GaussianBlur canny_GaussianBlur_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( canny_GaussianBlur_U0_ap_start ),
    .ap_done( canny_GaussianBlur_U0_ap_done ),
    .ap_continue( canny_GaussianBlur_U0_ap_continue ),
    .ap_idle( canny_GaussianBlur_U0_ap_idle ),
    .ap_ready( canny_GaussianBlur_U0_ap_ready ),
    .p_src_rows_V_dout( canny_GaussianBlur_U0_p_src_rows_V_dout ),
    .p_src_rows_V_empty_n( canny_GaussianBlur_U0_p_src_rows_V_empty_n ),
    .p_src_rows_V_read( canny_GaussianBlur_U0_p_src_rows_V_read ),
    .p_src_cols_V_dout( canny_GaussianBlur_U0_p_src_cols_V_dout ),
    .p_src_cols_V_empty_n( canny_GaussianBlur_U0_p_src_cols_V_empty_n ),
    .p_src_cols_V_read( canny_GaussianBlur_U0_p_src_cols_V_read ),
    .p_src_data_stream_V_dout( canny_GaussianBlur_U0_p_src_data_stream_V_dout ),
    .p_src_data_stream_V_empty_n( canny_GaussianBlur_U0_p_src_data_stream_V_empty_n ),
    .p_src_data_stream_V_read( canny_GaussianBlur_U0_p_src_data_stream_V_read ),
    .p_dst_data_stream_V_din( canny_GaussianBlur_U0_p_dst_data_stream_V_din ),
    .p_dst_data_stream_V_full_n( canny_GaussianBlur_U0_p_dst_data_stream_V_full_n ),
    .p_dst_data_stream_V_write( canny_GaussianBlur_U0_p_dst_data_stream_V_write )
);

canny_Duplicate_1024_1024_0_0_s canny_Duplicate_1024_1024_0_0_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( canny_Duplicate_1024_1024_0_0_U0_ap_start ),
    .ap_done( canny_Duplicate_1024_1024_0_0_U0_ap_done ),
    .ap_continue( canny_Duplicate_1024_1024_0_0_U0_ap_continue ),
    .ap_idle( canny_Duplicate_1024_1024_0_0_U0_ap_idle ),
    .ap_ready( canny_Duplicate_1024_1024_0_0_U0_ap_ready ),
    .src_data_stream_V_dout( canny_Duplicate_1024_1024_0_0_U0_src_data_stream_V_dout ),
    .src_data_stream_V_empty_n( canny_Duplicate_1024_1024_0_0_U0_src_data_stream_V_empty_n ),
    .src_data_stream_V_read( canny_Duplicate_1024_1024_0_0_U0_src_data_stream_V_read ),
    .dst1_data_stream_V_din( canny_Duplicate_1024_1024_0_0_U0_dst1_data_stream_V_din ),
    .dst1_data_stream_V_full_n( canny_Duplicate_1024_1024_0_0_U0_dst1_data_stream_V_full_n ),
    .dst1_data_stream_V_write( canny_Duplicate_1024_1024_0_0_U0_dst1_data_stream_V_write ),
    .dst2_data_stream_V_din( canny_Duplicate_1024_1024_0_0_U0_dst2_data_stream_V_din ),
    .dst2_data_stream_V_full_n( canny_Duplicate_1024_1024_0_0_U0_dst2_data_stream_V_full_n ),
    .dst2_data_stream_V_write( canny_Duplicate_1024_1024_0_0_U0_dst2_data_stream_V_write )
);

canny_Sobel canny_Sobel_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( canny_Sobel_U0_ap_start ),
    .ap_done( canny_Sobel_U0_ap_done ),
    .ap_continue( canny_Sobel_U0_ap_continue ),
    .ap_idle( canny_Sobel_U0_ap_idle ),
    .ap_ready( canny_Sobel_U0_ap_ready ),
    .p_src_data_stream_V_dout( canny_Sobel_U0_p_src_data_stream_V_dout ),
    .p_src_data_stream_V_empty_n( canny_Sobel_U0_p_src_data_stream_V_empty_n ),
    .p_src_data_stream_V_read( canny_Sobel_U0_p_src_data_stream_V_read ),
    .p_dst_data_stream_V_din( canny_Sobel_U0_p_dst_data_stream_V_din ),
    .p_dst_data_stream_V_full_n( canny_Sobel_U0_p_dst_data_stream_V_full_n ),
    .p_dst_data_stream_V_write( canny_Sobel_U0_p_dst_data_stream_V_write )
);

canny_Sobel_1 canny_Sobel_1_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( canny_Sobel_1_U0_ap_start ),
    .ap_done( canny_Sobel_1_U0_ap_done ),
    .ap_continue( canny_Sobel_1_U0_ap_continue ),
    .ap_idle( canny_Sobel_1_U0_ap_idle ),
    .ap_ready( canny_Sobel_1_U0_ap_ready ),
    .p_src_data_stream_V_dout( canny_Sobel_1_U0_p_src_data_stream_V_dout ),
    .p_src_data_stream_V_empty_n( canny_Sobel_1_U0_p_src_data_stream_V_empty_n ),
    .p_src_data_stream_V_read( canny_Sobel_1_U0_p_src_data_stream_V_read ),
    .p_dst_data_stream_V_din( canny_Sobel_1_U0_p_dst_data_stream_V_din ),
    .p_dst_data_stream_V_full_n( canny_Sobel_1_U0_p_dst_data_stream_V_full_n ),
    .p_dst_data_stream_V_write( canny_Sobel_1_U0_p_dst_data_stream_V_write )
);

canny_grad_computation canny_grad_computation_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( canny_grad_computation_U0_ap_start ),
    .ap_done( canny_grad_computation_U0_ap_done ),
    .ap_continue( canny_grad_computation_U0_ap_continue ),
    .ap_idle( canny_grad_computation_U0_ap_idle ),
    .ap_ready( canny_grad_computation_U0_ap_ready ),
    .grad_x_data_stream_V_dout( canny_grad_computation_U0_grad_x_data_stream_V_dout ),
    .grad_x_data_stream_V_empty_n( canny_grad_computation_U0_grad_x_data_stream_V_empty_n ),
    .grad_x_data_stream_V_read( canny_grad_computation_U0_grad_x_data_stream_V_read ),
    .grad_y_data_stream_V_dout( canny_grad_computation_U0_grad_y_data_stream_V_dout ),
    .grad_y_data_stream_V_empty_n( canny_grad_computation_U0_grad_y_data_stream_V_empty_n ),
    .grad_y_data_stream_V_read( canny_grad_computation_U0_grad_y_data_stream_V_read ),
    .grad_out_data_stream_V_din( canny_grad_computation_U0_grad_out_data_stream_V_din ),
    .grad_out_data_stream_V_full_n( canny_grad_computation_U0_grad_out_data_stream_V_full_n ),
    .grad_out_data_stream_V_write( canny_grad_computation_U0_grad_out_data_stream_V_write )
);

canny_nonmax_supression canny_nonmax_supression_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( canny_nonmax_supression_U0_ap_start ),
    .ap_done( canny_nonmax_supression_U0_ap_done ),
    .ap_continue( canny_nonmax_supression_U0_ap_continue ),
    .ap_idle( canny_nonmax_supression_U0_ap_idle ),
    .ap_ready( canny_nonmax_supression_U0_ap_ready ),
    .grad_out_data_stream_V_dout( canny_nonmax_supression_U0_grad_out_data_stream_V_dout ),
    .grad_out_data_stream_V_empty_n( canny_nonmax_supression_U0_grad_out_data_stream_V_empty_n ),
    .grad_out_data_stream_V_read( canny_nonmax_supression_U0_grad_out_data_stream_V_read ),
    .supressed_data_stream_V_din( canny_nonmax_supression_U0_supressed_data_stream_V_din ),
    .supressed_data_stream_V_full_n( canny_nonmax_supression_U0_supressed_data_stream_V_full_n ),
    .supressed_data_stream_V_write( canny_nonmax_supression_U0_supressed_data_stream_V_write )
);

canny_hysterisis canny_hysterisis_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( canny_hysterisis_U0_ap_start ),
    .ap_done( canny_hysterisis_U0_ap_done ),
    .ap_continue( canny_hysterisis_U0_ap_continue ),
    .ap_idle( canny_hysterisis_U0_ap_idle ),
    .ap_ready( canny_hysterisis_U0_ap_ready ),
    .supressed_data_stream_V_dout( canny_hysterisis_U0_supressed_data_stream_V_dout ),
    .supressed_data_stream_V_empty_n( canny_hysterisis_U0_supressed_data_stream_V_empty_n ),
    .supressed_data_stream_V_read( canny_hysterisis_U0_supressed_data_stream_V_read ),
    .hysterisis_Image_data_stream_V_din( canny_hysterisis_U0_hysterisis_Image_data_stream_V_din ),
    .hysterisis_Image_data_stream_V_full_n( canny_hysterisis_U0_hysterisis_Image_data_stream_V_full_n ),
    .hysterisis_Image_data_stream_V_write( canny_hysterisis_U0_hysterisis_Image_data_stream_V_write )
);

canny_Mat2AXIvideo_8_1022_1022_0_s canny_Mat2AXIvideo_8_1022_1022_0_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_start ),
    .ap_done( canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_done ),
    .ap_continue( canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_continue ),
    .ap_idle( canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_idle ),
    .ap_ready( canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_ready ),
    .img_data_stream_V_dout( canny_Mat2AXIvideo_8_1022_1022_0_U0_img_data_stream_V_dout ),
    .img_data_stream_V_empty_n( canny_Mat2AXIvideo_8_1022_1022_0_U0_img_data_stream_V_empty_n ),
    .img_data_stream_V_read( canny_Mat2AXIvideo_8_1022_1022_0_U0_img_data_stream_V_read ),
    .output_stream_TDATA( canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TDATA ),
    .output_stream_TVALID( canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TVALID ),
    .output_stream_TREADY( canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TREADY ),
    .output_stream_TKEEP( canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TKEEP ),
    .output_stream_TSTRB( canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TSTRB ),
    .output_stream_TUSER( canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TUSER ),
    .output_stream_TLAST( canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TLAST ),
    .output_stream_TID( canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TID ),
    .output_stream_TDEST( canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TDEST )
);

FIFO_canny_img_0_rows_V_channel img_0_rows_V_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_rows_V_channel_U_ap_dummy_ce ),
    .if_write_ce( img_0_rows_V_channel_U_ap_dummy_ce ),
    .if_din( img_0_rows_V_channel_din ),
    .if_full_n( img_0_rows_V_channel_full_n ),
    .if_write( img_0_rows_V_channel_write ),
    .if_dout( img_0_rows_V_channel_dout ),
    .if_empty_n( img_0_rows_V_channel_empty_n ),
    .if_read( img_0_rows_V_channel_read )
);

FIFO_canny_img_0_cols_V_channel img_0_cols_V_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_cols_V_channel_U_ap_dummy_ce ),
    .if_write_ce( img_0_cols_V_channel_U_ap_dummy_ce ),
    .if_din( img_0_cols_V_channel_din ),
    .if_full_n( img_0_cols_V_channel_full_n ),
    .if_write( img_0_cols_V_channel_write ),
    .if_dout( img_0_cols_V_channel_dout ),
    .if_empty_n( img_0_cols_V_channel_empty_n ),
    .if_read( img_0_cols_V_channel_read )
);

FIFO_canny_img_0_data_stream_0_V img_0_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_0_V_din ),
    .if_full_n( img_0_data_stream_0_V_full_n ),
    .if_write( img_0_data_stream_0_V_write ),
    .if_dout( img_0_data_stream_0_V_dout ),
    .if_empty_n( img_0_data_stream_0_V_empty_n ),
    .if_read( img_0_data_stream_0_V_read )
);

FIFO_canny_img_0_rows_V_channel19 img_0_rows_V_channel19_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_rows_V_channel19_U_ap_dummy_ce ),
    .if_write_ce( img_0_rows_V_channel19_U_ap_dummy_ce ),
    .if_din( img_0_rows_V_channel19_din ),
    .if_full_n( img_0_rows_V_channel19_full_n ),
    .if_write( img_0_rows_V_channel19_write ),
    .if_dout( img_0_rows_V_channel19_dout ),
    .if_empty_n( img_0_rows_V_channel19_empty_n ),
    .if_read( img_0_rows_V_channel19_read )
);

FIFO_canny_img_0_cols_V_channel20 img_0_cols_V_channel20_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_cols_V_channel20_U_ap_dummy_ce ),
    .if_write_ce( img_0_cols_V_channel20_U_ap_dummy_ce ),
    .if_din( img_0_cols_V_channel20_din ),
    .if_full_n( img_0_cols_V_channel20_full_n ),
    .if_write( img_0_cols_V_channel20_write ),
    .if_dout( img_0_cols_V_channel20_dout ),
    .if_empty_n( img_0_cols_V_channel20_empty_n ),
    .if_read( img_0_cols_V_channel20_read )
);

FIFO_canny_img_1_data_stream_0_V img_1_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_1_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_1_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_1_data_stream_0_V_din ),
    .if_full_n( img_1_data_stream_0_V_full_n ),
    .if_write( img_1_data_stream_0_V_write ),
    .if_dout( img_1_data_stream_0_V_dout ),
    .if_empty_n( img_1_data_stream_0_V_empty_n ),
    .if_read( img_1_data_stream_0_V_read )
);

FIFO_canny_img_2_data_stream_0_V img_2_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_2_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_2_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_2_data_stream_0_V_din ),
    .if_full_n( img_2_data_stream_0_V_full_n ),
    .if_write( img_2_data_stream_0_V_write ),
    .if_dout( img_2_data_stream_0_V_dout ),
    .if_empty_n( img_2_data_stream_0_V_empty_n ),
    .if_read( img_2_data_stream_0_V_read )
);

FIFO_canny_img_3_data_stream_0_V img_3_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_3_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_3_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_3_data_stream_0_V_din ),
    .if_full_n( img_3_data_stream_0_V_full_n ),
    .if_write( img_3_data_stream_0_V_write ),
    .if_dout( img_3_data_stream_0_V_dout ),
    .if_empty_n( img_3_data_stream_0_V_empty_n ),
    .if_read( img_3_data_stream_0_V_read )
);

FIFO_canny_grad_x_data_stream_0_V grad_x_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( grad_x_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( grad_x_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( grad_x_data_stream_0_V_din ),
    .if_full_n( grad_x_data_stream_0_V_full_n ),
    .if_write( grad_x_data_stream_0_V_write ),
    .if_dout( grad_x_data_stream_0_V_dout ),
    .if_empty_n( grad_x_data_stream_0_V_empty_n ),
    .if_read( grad_x_data_stream_0_V_read )
);

FIFO_canny_grad_y_data_stream_0_V grad_y_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( grad_y_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( grad_y_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( grad_y_data_stream_0_V_din ),
    .if_full_n( grad_y_data_stream_0_V_full_n ),
    .if_write( grad_y_data_stream_0_V_write ),
    .if_dout( grad_y_data_stream_0_V_dout ),
    .if_empty_n( grad_y_data_stream_0_V_empty_n ),
    .if_read( grad_y_data_stream_0_V_read )
);

FIFO_canny_grad_out_data_stream_0_V grad_out_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( grad_out_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( grad_out_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( grad_out_data_stream_0_V_din ),
    .if_full_n( grad_out_data_stream_0_V_full_n ),
    .if_write( grad_out_data_stream_0_V_write ),
    .if_dout( grad_out_data_stream_0_V_dout ),
    .if_empty_n( grad_out_data_stream_0_V_empty_n ),
    .if_read( grad_out_data_stream_0_V_read )
);

FIFO_canny_supressed_Image_data_stream_0 supressed_Image_data_stream_0_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( supressed_Image_data_stream_0_U_ap_dummy_ce ),
    .if_write_ce( supressed_Image_data_stream_0_U_ap_dummy_ce ),
    .if_din( supressed_Image_data_stream_0_din ),
    .if_full_n( supressed_Image_data_stream_0_full_n ),
    .if_write( supressed_Image_data_stream_0_write ),
    .if_dout( supressed_Image_data_stream_0_dout ),
    .if_empty_n( supressed_Image_data_stream_0_empty_n ),
    .if_read( supressed_Image_data_stream_0_read )
);

FIFO_canny_hysterisis_Image_data_stream_0 hysterisis_Image_data_stream_0_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( hysterisis_Image_data_stream_0_U_ap_dummy_ce ),
    .if_write_ce( hysterisis_Image_data_stream_0_U_ap_dummy_ce ),
    .if_din( hysterisis_Image_data_stream_0_din ),
    .if_full_n( hysterisis_Image_data_stream_0_full_n ),
    .if_write( hysterisis_Image_data_stream_0_write ),
    .if_dout( hysterisis_Image_data_stream_0_dout ),
    .if_empty_n( hysterisis_Image_data_stream_0_empty_n ),
    .if_read( hysterisis_Image_data_stream_0_read )
);



always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_canny_AXIvideo2Mat_8_1024_1024_0_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_canny_AXIvideo2Mat_8_1024_1024_0_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_canny_AXIvideo2Mat_8_1024_1024_0_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_done)) begin
            ap_reg_procdone_canny_AXIvideo2Mat_8_1024_1024_0_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_canny_Block_proc_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_canny_Block_proc_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_canny_Block_proc_U0 <= ap_const_logic_0;
        end else if ((canny_Block_proc_U0_ap_done == ap_const_logic_1)) begin
            ap_reg_procdone_canny_Block_proc_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_canny_Duplicate_1024_1024_0_0_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_canny_Duplicate_1024_1024_0_0_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_canny_Duplicate_1024_1024_0_0_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == canny_Duplicate_1024_1024_0_0_U0_ap_done)) begin
            ap_reg_procdone_canny_Duplicate_1024_1024_0_0_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_canny_GaussianBlur_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_canny_GaussianBlur_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_canny_GaussianBlur_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == canny_GaussianBlur_U0_ap_done)) begin
            ap_reg_procdone_canny_GaussianBlur_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_canny_Mat2AXIvideo_8_1022_1022_0_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_canny_Mat2AXIvideo_8_1022_1022_0_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_canny_Mat2AXIvideo_8_1022_1022_0_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_done)) begin
            ap_reg_procdone_canny_Mat2AXIvideo_8_1022_1022_0_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_canny_Sobel_1_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_canny_Sobel_1_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_canny_Sobel_1_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == canny_Sobel_1_U0_ap_done)) begin
            ap_reg_procdone_canny_Sobel_1_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_canny_Sobel_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_canny_Sobel_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_canny_Sobel_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == canny_Sobel_U0_ap_done)) begin
            ap_reg_procdone_canny_Sobel_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_canny_grad_computation_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_canny_grad_computation_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_canny_grad_computation_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == canny_grad_computation_U0_ap_done)) begin
            ap_reg_procdone_canny_grad_computation_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_canny_hysterisis_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_canny_hysterisis_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_canny_hysterisis_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == canny_hysterisis_U0_ap_done)) begin
            ap_reg_procdone_canny_hysterisis_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_canny_nonmax_supression_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_canny_nonmax_supression_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_canny_nonmax_supression_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == canny_nonmax_supression_U0_ap_done)) begin
            ap_reg_procdone_canny_nonmax_supression_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_canny_Duplicate_1024_1024_0_0_U0_ap_start
    if (ap_rst_n_inv == 1'b1) begin
        canny_Duplicate_1024_1024_0_0_U0_ap_start <= ap_const_logic_0;
    end else begin
        canny_Duplicate_1024_1024_0_0_U0_ap_start <= ap_const_logic_1;
    end
end

always @ (posedge ap_clk) begin : ap_ret_canny_GaussianBlur_U0_ap_start
    if (ap_rst_n_inv == 1'b1) begin
        canny_GaussianBlur_U0_ap_start <= ap_const_logic_0;
    end else begin
        canny_GaussianBlur_U0_ap_start <= ap_const_logic_1;
    end
end

always @ (posedge ap_clk) begin : ap_ret_canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_start
    if (ap_rst_n_inv == 1'b1) begin
        canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_start <= ap_const_logic_0;
    end else begin
        canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_start <= ap_const_logic_1;
    end
end

always @ (posedge ap_clk) begin : ap_ret_canny_Sobel_1_U0_ap_start
    if (ap_rst_n_inv == 1'b1) begin
        canny_Sobel_1_U0_ap_start <= ap_const_logic_0;
    end else begin
        canny_Sobel_1_U0_ap_start <= ap_const_logic_1;
    end
end

always @ (posedge ap_clk) begin : ap_ret_canny_Sobel_U0_ap_start
    if (ap_rst_n_inv == 1'b1) begin
        canny_Sobel_U0_ap_start <= ap_const_logic_0;
    end else begin
        canny_Sobel_U0_ap_start <= ap_const_logic_1;
    end
end

always @ (posedge ap_clk) begin : ap_ret_canny_grad_computation_U0_ap_start
    if (ap_rst_n_inv == 1'b1) begin
        canny_grad_computation_U0_ap_start <= ap_const_logic_0;
    end else begin
        canny_grad_computation_U0_ap_start <= ap_const_logic_1;
    end
end

always @ (posedge ap_clk) begin : ap_ret_canny_hysterisis_U0_ap_start
    if (ap_rst_n_inv == 1'b1) begin
        canny_hysterisis_U0_ap_start <= ap_const_logic_0;
    end else begin
        canny_hysterisis_U0_ap_start <= ap_const_logic_1;
    end
end

always @ (posedge ap_clk) begin : ap_ret_canny_nonmax_supression_U0_ap_start
    if (ap_rst_n_inv == 1'b1) begin
        canny_nonmax_supression_U0_ap_start <= ap_const_logic_0;
    end else begin
        canny_nonmax_supression_U0_ap_start <= ap_const_logic_1;
    end
end

always @ (posedge ap_clk) begin
    ap_CS <= ap_const_logic_0;
end

always @ (canny_Block_proc_U0_ap_idle or canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_idle or canny_GaussianBlur_U0_ap_idle or canny_Duplicate_1024_1024_0_0_U0_ap_idle or canny_Sobel_U0_ap_idle or canny_Sobel_1_U0_ap_idle or canny_grad_computation_U0_ap_idle or canny_nonmax_supression_U0_ap_idle or canny_hysterisis_U0_ap_idle or canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_idle) begin
    if (((canny_Block_proc_U0_ap_idle == ap_const_logic_1) & (ap_const_logic_1 == canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_idle) & (ap_const_logic_1 == canny_GaussianBlur_U0_ap_idle) & (ap_const_logic_1 == canny_Duplicate_1024_1024_0_0_U0_ap_idle) & (ap_const_logic_1 == canny_Sobel_U0_ap_idle) & (ap_const_logic_1 == canny_Sobel_1_U0_ap_idle) & (ap_const_logic_1 == canny_grad_computation_U0_ap_idle) & (ap_const_logic_1 == canny_nonmax_supression_U0_ap_idle) & (ap_const_logic_1 == canny_hysterisis_U0_ap_idle) & (ap_const_logic_1 == canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_idle))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_done) begin
    if ((ap_const_logic_1 == canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_done)) begin
        ap_sig_hs_done = ap_const_logic_1;
    end else begin
        ap_sig_hs_done = ap_const_logic_0;
    end
end

assign ap_done = ap_sig_hs_done;

assign ap_ready = ap_sig_top_allready;


always @ (ap_rst_n) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sig_hs_continue = ap_const_logic_1;

assign ap_sig_top_allready = canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_ready;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_continue = ap_const_logic_1;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_ap_start = ap_start;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_dout = img_0_cols_V_channel_dout;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_empty_n = img_0_cols_V_channel_empty_n;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_out_full_n = img_0_cols_V_channel20_full_n;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_img_data_stream_V_full_n = img_0_data_stream_0_V_full_n;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_dout = img_0_rows_V_channel_dout;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_empty_n = img_0_rows_V_channel_empty_n;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_out_full_n = img_0_rows_V_channel19_full_n;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TDATA = input_stream_TDATA;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TDEST = input_stream_TDEST;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TID = input_stream_TID;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TKEEP = input_stream_TKEEP;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TLAST = input_stream_TLAST;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TSTRB = input_stream_TSTRB;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TUSER = input_stream_TUSER;

assign canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TVALID = input_stream_TVALID;

assign canny_Block_proc_U0_ap_continue = ap_const_logic_1;

assign canny_Block_proc_U0_ap_start = ap_start;

assign canny_Block_proc_U0_img_0_cols_V_out_full_n = img_0_cols_V_channel_full_n;

assign canny_Block_proc_U0_img_0_rows_V_out_full_n = img_0_rows_V_channel_full_n;

assign canny_Duplicate_1024_1024_0_0_U0_ap_continue = ap_const_logic_1;

assign canny_Duplicate_1024_1024_0_0_U0_dst1_data_stream_V_full_n = img_2_data_stream_0_V_full_n;

assign canny_Duplicate_1024_1024_0_0_U0_dst2_data_stream_V_full_n = img_3_data_stream_0_V_full_n;

assign canny_Duplicate_1024_1024_0_0_U0_src_data_stream_V_dout = img_1_data_stream_0_V_dout;

assign canny_Duplicate_1024_1024_0_0_U0_src_data_stream_V_empty_n = img_1_data_stream_0_V_empty_n;

assign canny_GaussianBlur_U0_ap_continue = ap_const_logic_1;

assign canny_GaussianBlur_U0_p_dst_data_stream_V_full_n = img_1_data_stream_0_V_full_n;

assign canny_GaussianBlur_U0_p_src_cols_V_dout = img_0_cols_V_channel20_dout;

assign canny_GaussianBlur_U0_p_src_cols_V_empty_n = img_0_cols_V_channel20_empty_n;

assign canny_GaussianBlur_U0_p_src_data_stream_V_dout = img_0_data_stream_0_V_dout;

assign canny_GaussianBlur_U0_p_src_data_stream_V_empty_n = img_0_data_stream_0_V_empty_n;

assign canny_GaussianBlur_U0_p_src_rows_V_dout = img_0_rows_V_channel19_dout;

assign canny_GaussianBlur_U0_p_src_rows_V_empty_n = img_0_rows_V_channel19_empty_n;

assign canny_Mat2AXIvideo_8_1022_1022_0_U0_ap_continue = ap_sig_hs_continue;

assign canny_Mat2AXIvideo_8_1022_1022_0_U0_img_data_stream_V_dout = hysterisis_Image_data_stream_0_dout;

assign canny_Mat2AXIvideo_8_1022_1022_0_U0_img_data_stream_V_empty_n = hysterisis_Image_data_stream_0_empty_n;

assign canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TREADY = output_stream_TREADY;

assign canny_Sobel_1_U0_ap_continue = ap_const_logic_1;

assign canny_Sobel_1_U0_p_dst_data_stream_V_full_n = grad_y_data_stream_0_V_full_n;

assign canny_Sobel_1_U0_p_src_data_stream_V_dout = img_3_data_stream_0_V_dout;

assign canny_Sobel_1_U0_p_src_data_stream_V_empty_n = img_3_data_stream_0_V_empty_n;

assign canny_Sobel_U0_ap_continue = ap_const_logic_1;

assign canny_Sobel_U0_p_dst_data_stream_V_full_n = grad_x_data_stream_0_V_full_n;

assign canny_Sobel_U0_p_src_data_stream_V_dout = img_2_data_stream_0_V_dout;

assign canny_Sobel_U0_p_src_data_stream_V_empty_n = img_2_data_stream_0_V_empty_n;

assign canny_grad_computation_U0_ap_continue = ap_const_logic_1;

assign canny_grad_computation_U0_grad_out_data_stream_V_full_n = grad_out_data_stream_0_V_full_n;

assign canny_grad_computation_U0_grad_x_data_stream_V_dout = grad_x_data_stream_0_V_dout;

assign canny_grad_computation_U0_grad_x_data_stream_V_empty_n = grad_x_data_stream_0_V_empty_n;

assign canny_grad_computation_U0_grad_y_data_stream_V_dout = grad_y_data_stream_0_V_dout;

assign canny_grad_computation_U0_grad_y_data_stream_V_empty_n = grad_y_data_stream_0_V_empty_n;

assign canny_hysterisis_U0_ap_continue = ap_const_logic_1;

assign canny_hysterisis_U0_hysterisis_Image_data_stream_V_full_n = hysterisis_Image_data_stream_0_full_n;

assign canny_hysterisis_U0_supressed_data_stream_V_dout = supressed_Image_data_stream_0_dout;

assign canny_hysterisis_U0_supressed_data_stream_V_empty_n = supressed_Image_data_stream_0_empty_n;

assign canny_nonmax_supression_U0_ap_continue = ap_const_logic_1;

assign canny_nonmax_supression_U0_grad_out_data_stream_V_dout = grad_out_data_stream_0_V_dout;

assign canny_nonmax_supression_U0_grad_out_data_stream_V_empty_n = grad_out_data_stream_0_V_empty_n;

assign canny_nonmax_supression_U0_supressed_data_stream_V_full_n = supressed_Image_data_stream_0_full_n;

assign grad_out_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign grad_out_data_stream_0_V_din = canny_grad_computation_U0_grad_out_data_stream_V_din;

assign grad_out_data_stream_0_V_read = canny_nonmax_supression_U0_grad_out_data_stream_V_read;

assign grad_out_data_stream_0_V_write = canny_grad_computation_U0_grad_out_data_stream_V_write;

assign grad_x_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign grad_x_data_stream_0_V_din = canny_Sobel_U0_p_dst_data_stream_V_din;

assign grad_x_data_stream_0_V_read = canny_grad_computation_U0_grad_x_data_stream_V_read;

assign grad_x_data_stream_0_V_write = canny_Sobel_U0_p_dst_data_stream_V_write;

assign grad_y_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign grad_y_data_stream_0_V_din = canny_Sobel_1_U0_p_dst_data_stream_V_din;

assign grad_y_data_stream_0_V_read = canny_grad_computation_U0_grad_y_data_stream_V_read;

assign grad_y_data_stream_0_V_write = canny_Sobel_1_U0_p_dst_data_stream_V_write;

assign hysterisis_Image_data_stream_0_U_ap_dummy_ce = ap_const_logic_1;

assign hysterisis_Image_data_stream_0_din = canny_hysterisis_U0_hysterisis_Image_data_stream_V_din;

assign hysterisis_Image_data_stream_0_read = canny_Mat2AXIvideo_8_1022_1022_0_U0_img_data_stream_V_read;

assign hysterisis_Image_data_stream_0_write = canny_hysterisis_U0_hysterisis_Image_data_stream_V_write;

assign img_0_cols_V_channel20_U_ap_dummy_ce = ap_const_logic_1;

assign img_0_cols_V_channel20_din = canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_out_din;

assign img_0_cols_V_channel20_read = canny_GaussianBlur_U0_p_src_cols_V_read;

assign img_0_cols_V_channel20_write = canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_out_write;

assign img_0_cols_V_channel_U_ap_dummy_ce = ap_const_logic_1;

assign img_0_cols_V_channel_din = canny_Block_proc_U0_img_0_cols_V_out_din;

assign img_0_cols_V_channel_read = canny_AXIvideo2Mat_8_1024_1024_0_U0_img_cols_V_read;

assign img_0_cols_V_channel_write = canny_Block_proc_U0_img_0_cols_V_out_write;

assign img_0_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_0_data_stream_0_V_din = canny_AXIvideo2Mat_8_1024_1024_0_U0_img_data_stream_V_din;

assign img_0_data_stream_0_V_read = canny_GaussianBlur_U0_p_src_data_stream_V_read;

assign img_0_data_stream_0_V_write = canny_AXIvideo2Mat_8_1024_1024_0_U0_img_data_stream_V_write;

assign img_0_rows_V_channel19_U_ap_dummy_ce = ap_const_logic_1;

assign img_0_rows_V_channel19_din = canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_out_din;

assign img_0_rows_V_channel19_read = canny_GaussianBlur_U0_p_src_rows_V_read;

assign img_0_rows_V_channel19_write = canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_out_write;

assign img_0_rows_V_channel_U_ap_dummy_ce = ap_const_logic_1;

assign img_0_rows_V_channel_din = canny_Block_proc_U0_img_0_rows_V_out_din;

assign img_0_rows_V_channel_read = canny_AXIvideo2Mat_8_1024_1024_0_U0_img_rows_V_read;

assign img_0_rows_V_channel_write = canny_Block_proc_U0_img_0_rows_V_out_write;

assign img_1_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_1_data_stream_0_V_din = canny_GaussianBlur_U0_p_dst_data_stream_V_din;

assign img_1_data_stream_0_V_read = canny_Duplicate_1024_1024_0_0_U0_src_data_stream_V_read;

assign img_1_data_stream_0_V_write = canny_GaussianBlur_U0_p_dst_data_stream_V_write;

assign img_2_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_2_data_stream_0_V_din = canny_Duplicate_1024_1024_0_0_U0_dst1_data_stream_V_din;

assign img_2_data_stream_0_V_read = canny_Sobel_U0_p_src_data_stream_V_read;

assign img_2_data_stream_0_V_write = canny_Duplicate_1024_1024_0_0_U0_dst1_data_stream_V_write;

assign img_3_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_3_data_stream_0_V_din = canny_Duplicate_1024_1024_0_0_U0_dst2_data_stream_V_din;

assign img_3_data_stream_0_V_read = canny_Sobel_1_U0_p_src_data_stream_V_read;

assign img_3_data_stream_0_V_write = canny_Duplicate_1024_1024_0_0_U0_dst2_data_stream_V_write;

assign input_stream_TREADY = canny_AXIvideo2Mat_8_1024_1024_0_U0_input_stream_TREADY;

assign output_stream_TDATA = canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TDATA;

assign output_stream_TDEST = canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TDEST;

assign output_stream_TID = canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TID;

assign output_stream_TKEEP = canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TKEEP;

assign output_stream_TLAST = canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TLAST;

assign output_stream_TSTRB = canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TSTRB;

assign output_stream_TUSER = canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TUSER;

assign output_stream_TVALID = canny_Mat2AXIvideo_8_1022_1022_0_U0_output_stream_TVALID;

assign supressed_Image_data_stream_0_U_ap_dummy_ce = ap_const_logic_1;

assign supressed_Image_data_stream_0_din = canny_nonmax_supression_U0_supressed_data_stream_V_din;

assign supressed_Image_data_stream_0_read = canny_hysterisis_U0_supressed_data_stream_V_read;

assign supressed_Image_data_stream_0_write = canny_nonmax_supression_U0_supressed_data_stream_V_write;


endmodule //canny

