// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module canny_nonmax_supression (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        grad_out_data_stream_V_dout,
        grad_out_data_stream_V_empty_n,
        grad_out_data_stream_V_read,
        supressed_data_stream_V_din,
        supressed_data_stream_V_full_n,
        supressed_data_stream_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 3'b1;
parameter    ap_ST_st2_fsm_1 = 3'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 3'b100;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv11_401 = 11'b10000000001;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] grad_out_data_stream_V_dout;
input   grad_out_data_stream_V_empty_n;
output   grad_out_data_stream_V_read;
output  [7:0] supressed_data_stream_V_din;
input   supressed_data_stream_V_full_n;
output   supressed_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg grad_out_data_stream_V_read;
reg supressed_data_stream_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm = 3'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_22;
reg   [10:0] p_1_reg_180;
reg   [10:0] ap_reg_ppstg_p_1_reg_180_pp0_it1;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_bdd_45;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg   [0:0] tmp_3_reg_704;
reg    ap_sig_bdd_54;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg   [0:0] or_cond4_reg_736;
reg   [0:0] ap_reg_ppstg_or_cond4_reg_736_pp0_it4;
reg    ap_sig_bdd_69;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
wire   [0:0] exitcond1_fu_192_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_83;
wire   [10:0] i_V_fu_198_p2;
reg   [10:0] i_V_reg_680;
wire   [0:0] icmp_fu_214_p2;
reg   [0:0] icmp_reg_685;
wire   [0:0] tmp_2_fu_220_p2;
reg   [0:0] tmp_2_reg_690;
wire   [0:0] exitcond_fu_226_p2;
reg   [0:0] exitcond_reg_695;
reg   [0:0] ap_reg_ppstg_exitcond_reg_695_pp0_it1;
wire   [10:0] j_V_fu_232_p2;
reg   [10:0] j_V_reg_699;
reg   [0:0] ap_reg_ppstg_tmp_3_reg_704_pp0_it1;
wire   [0:0] tmp_7_fu_252_p3;
reg   [0:0] tmp_7_reg_708;
reg   [0:0] ap_reg_ppstg_tmp_7_reg_708_pp0_it1;
reg   [9:0] Buffer_val_1_addr_reg_715;
reg   [9:0] ap_reg_ppstg_Buffer_val_1_addr_reg_715_pp0_it1;
wire   [0:0] tmp9_fu_282_p2;
reg   [0:0] tmp9_reg_726;
reg   [0:0] tmp_21_reg_731;
wire   [0:0] or_cond4_fu_301_p2;
reg   [0:0] ap_reg_ppstg_or_cond4_reg_736_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond4_reg_736_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond4_reg_736_pp0_it3;
wire   [15:0] Buffer_val_0_q0;
reg   [15:0] temp1_reg_740;
wire   [0:0] or_cond2_fu_321_p2;
reg   [0:0] or_cond2_reg_745;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_745_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_745_pp0_it3;
wire   [5:0] tmp_12_fu_386_p1;
reg   [5:0] tmp_12_reg_750;
wire   [0:0] sel_tmp2_fu_414_p2;
reg   [0:0] sel_tmp2_reg_755;
reg   [7:0] tmp_11_reg_761;
wire   [7:0] tmp_27_fu_468_p3;
reg   [7:0] tmp_27_reg_766;
reg   [7:0] tmp_13_reg_771;
wire   [7:0] tmp_32_fu_524_p3;
reg   [7:0] tmp_32_reg_776;
wire   [7:0] out_pixel_val_2_fu_571_p3;
reg   [7:0] out_pixel_val_2_reg_781;
wire   [0:0] tmp_14_fu_588_p2;
reg   [0:0] tmp_14_reg_786;
wire   [0:0] tmp_15_fu_594_p2;
reg   [0:0] tmp_15_reg_791;
wire   [7:0] tmp_33_fu_611_p3;
reg   [7:0] tmp_33_reg_796;
wire   [9:0] Buffer_val_0_address0;
reg    Buffer_val_0_ce0;
wire   [9:0] Buffer_val_0_address1;
reg    Buffer_val_0_ce1;
reg    Buffer_val_0_we1;
wire   [15:0] Buffer_val_0_d1;
wire   [9:0] Buffer_val_1_address0;
reg    Buffer_val_1_ce0;
wire   [15:0] Buffer_val_1_q0;
wire   [9:0] Buffer_val_1_address1;
reg    Buffer_val_1_ce1;
reg    Buffer_val_1_we1;
wire   [15:0] Buffer_val_1_d1;
reg   [10:0] p_s_reg_168;
reg    ap_sig_bdd_197;
reg   [10:0] ap_reg_phibuf_p_s_reg_168;
reg   [2:0] ap_NS_fsm;
reg    ap_sig_nseq_ST_st2_fsm_1;
reg    ap_sig_bdd_207;
reg   [10:0] p_1_phi_fu_184_p4;
wire   [63:0] tmp_8_fu_260_p1;
wire   [63:0] tmp_9_fu_329_p1;
reg   [15:0] temp1_s_fu_76;
reg   [15:0] temp2_s_fu_80;
reg   [15:0] pixel_value_s_fu_84;
reg   [15:0] Win_val_0_1_fu_88;
wire   [15:0] Win_val_0_0_0_Win_val_0_0_1_fu_375_p3;
reg   [15:0] Win_val_0_1_1_fu_92;
reg   [15:0] Win_val_1_1_fu_96;
wire   [15:0] Win_val_1_0_0_Win_val_1_0_1_fu_368_p3;
reg   [15:0] Win_val_1_1_1_fu_100;
reg   [15:0] Win_val_2_1_fu_104;
wire   [15:0] Win_val_2_0_0_Win_val_2_0_1_fu_361_p3;
reg   [15:0] Win_val_2_1_1_fu_108;
wire   [9:0] tmp_fu_204_p4;
wire   [10:0] tmp_4_fu_238_p2;
wire   [9:0] tmp_20_fu_266_p4;
wire   [0:0] icmp1_fu_276_p2;
wire   [0:0] tmp_16_fu_295_p2;
wire   [1:0] current_dir_fu_382_p1;
wire   [0:0] tmp_s_fu_390_p2;
wire   [0:0] tmp_5_fu_396_p2;
wire   [0:0] sel_tmp1_fu_408_p2;
wire   [0:0] tmp_10_fu_402_p2;
wire   [7:0] tmp_24_fu_440_p4;
wire   [7:0] tmp_25_fu_450_p4;
wire   [7:0] tmp_22_fu_430_p4;
wire   [7:0] tmp_26_fu_460_p3;
wire   [7:0] tmp_29_fu_496_p4;
wire   [7:0] tmp_30_fu_506_p4;
wire   [7:0] tmp_28_fu_486_p4;
wire   [7:0] tmp_31_fu_516_p3;
wire   [7:0] ga_fu_583_p3;
wire   [7:0] gb_fu_578_p3;
wire   [0:0] or_cond3_fu_600_p2;
wire   [7:0] out_pixel_val_fu_604_p3;


canny_nonmax_supression_Buffer_val_0 #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
Buffer_val_0_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( Buffer_val_0_address0 ),
    .ce0( Buffer_val_0_ce0 ),
    .q0( Buffer_val_0_q0 ),
    .address1( Buffer_val_0_address1 ),
    .ce1( Buffer_val_0_ce1 ),
    .we1( Buffer_val_0_we1 ),
    .d1( Buffer_val_0_d1 )
);

canny_nonmax_supression_Buffer_val_0 #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
Buffer_val_1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( Buffer_val_1_address0 ),
    .ce0( Buffer_val_1_ce0 ),
    .q0( Buffer_val_1_q0 ),
    .address1( Buffer_val_1_address1 ),
    .ce1( Buffer_val_1_ce1 ),
    .we1( Buffer_val_1_we1 ),
    .d1( Buffer_val_1_d1 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ap_const_lv1_0 == exitcond1_fu_192_p2))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_lv1_0 == exitcond_fu_226_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv1_0 == exitcond1_fu_192_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == exitcond_fu_226_p2))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv1_0 == exitcond1_fu_192_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_lv1_0 == exitcond_fu_226_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv1_0 == exitcond1_fu_192_p2))) begin
            ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == exitcond_reg_695))) begin
        p_1_reg_180 <= j_V_reg_699;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv1_0 == exitcond1_fu_192_p2))) begin
        p_1_reg_180 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_lv1_0 == exitcond_fu_226_p2) & (ap_const_logic_1 == ap_sig_nseq_ST_st2_fsm_1))) begin
        p_s_reg_168 <= i_V_reg_680;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & (ap_const_logic_1 == ap_sig_nseq_ST_st2_fsm_1))) begin
        p_s_reg_168 <= ap_reg_phibuf_p_s_reg_168;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_197)) begin
        p_s_reg_168 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == exitcond_fu_226_p2) & (ap_const_lv1_0 == tmp_7_fu_252_p3))) begin
        Buffer_val_1_addr_reg_715 <= tmp_8_fu_260_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_695_pp0_it1))) begin
        Win_val_0_1_1_fu_92 <= Win_val_0_1_fu_88;
        Win_val_0_1_fu_88 <= Win_val_0_0_0_Win_val_0_0_1_fu_375_p3;
        Win_val_1_1_1_fu_100 <= Win_val_1_1_fu_96;
        Win_val_1_1_fu_96 <= Win_val_1_0_0_Win_val_1_0_1_fu_368_p3;
        Win_val_2_1_1_fu_108 <= Win_val_2_1_fu_104;
        Win_val_2_1_fu_104 <= Win_val_2_0_0_Win_val_2_0_1_fu_361_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_lv1_0 == exitcond_fu_226_p2))) begin
        ap_reg_phibuf_p_s_reg_168 <= i_V_reg_680;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        ap_reg_ppstg_Buffer_val_1_addr_reg_715_pp0_it1 <= Buffer_val_1_addr_reg_715;
        ap_reg_ppstg_exitcond_reg_695_pp0_it1 <= exitcond_reg_695;
        ap_reg_ppstg_or_cond4_reg_736_pp0_it1 <= or_cond4_reg_736;
        ap_reg_ppstg_p_1_reg_180_pp0_it1 <= p_1_reg_180;
        ap_reg_ppstg_tmp_3_reg_704_pp0_it1 <= tmp_3_reg_704;
        ap_reg_ppstg_tmp_7_reg_708_pp0_it1 <= tmp_7_reg_708;
        exitcond_reg_695 <= exitcond_fu_226_p2;
        or_cond2_reg_745 <= or_cond2_fu_321_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
        ap_reg_ppstg_or_cond2_reg_745_pp0_it2 <= or_cond2_reg_745;
        ap_reg_ppstg_or_cond2_reg_745_pp0_it3 <= ap_reg_ppstg_or_cond2_reg_745_pp0_it2;
        ap_reg_ppstg_or_cond4_reg_736_pp0_it2 <= ap_reg_ppstg_or_cond4_reg_736_pp0_it1;
        ap_reg_ppstg_or_cond4_reg_736_pp0_it3 <= ap_reg_ppstg_or_cond4_reg_736_pp0_it2;
        ap_reg_ppstg_or_cond4_reg_736_pp0_it4 <= ap_reg_ppstg_or_cond4_reg_736_pp0_it3;
        tmp_33_reg_796[7 : 2] <= tmp_33_fu_611_p3[7 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        i_V_reg_680 <= i_V_fu_198_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv1_0 == exitcond1_fu_192_p2))) begin
        icmp_reg_685 <= icmp_fu_214_p2;
        tmp_2_reg_690 <= tmp_2_fu_220_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        j_V_reg_699 <= j_V_fu_232_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == exitcond_fu_226_p2))) begin
        or_cond4_reg_736 <= or_cond4_fu_301_p2;
        tmp9_reg_726 <= tmp9_fu_282_p2;
        tmp_21_reg_731 <= tmp_4_fu_238_p2[ap_const_lv32_A];
        tmp_3_reg_704 <= tmp_4_fu_238_p2[ap_const_lv32_A];
        tmp_7_reg_708 <= p_1_phi_fu_184_p4[ap_const_lv32_A];
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_745_pp0_it2))) begin
        out_pixel_val_2_reg_781[7 : 2] <= out_pixel_val_2_fu_571_p3[7 : 2];
        tmp_14_reg_786 <= tmp_14_fu_588_p2;
        tmp_15_reg_791 <= tmp_15_fu_594_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (tmp_3_reg_704 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        pixel_value_s_fu_84 <= grad_out_data_stream_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == or_cond2_reg_745))) begin
        sel_tmp2_reg_755 <= sel_tmp2_fu_414_p2;
        tmp_11_reg_761 <= {{Win_val_0_1_1_fu_92[ap_const_lv32_9 : ap_const_lv32_2]}};
        tmp_12_reg_750 <= tmp_12_fu_386_p1;
        tmp_13_reg_771 <= {{Win_val_2_0_0_Win_val_2_0_1_fu_361_p3[ap_const_lv32_9 : ap_const_lv32_2]}};
        tmp_27_reg_766 <= tmp_27_fu_468_p3;
        tmp_32_reg_776 <= tmp_32_fu_524_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == tmp_7_reg_708))) begin
        temp1_reg_740 <= Buffer_val_0_q0;
        temp1_s_fu_76 <= Buffer_val_0_q0;
        temp2_s_fu_80 <= Buffer_val_1_q0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_54 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_69 or ap_reg_ppiten_pp0_it5) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        Buffer_val_0_ce0 = ap_const_logic_1;
    end else begin
        Buffer_val_0_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_54 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_69 or ap_reg_ppiten_pp0_it5) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        Buffer_val_0_ce1 = ap_const_logic_1;
    end else begin
        Buffer_val_0_ce1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_54 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_69 or ap_reg_ppiten_pp0_it5 or ap_reg_ppstg_tmp_3_reg_704_pp0_it1) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_3_reg_704_pp0_it1))) begin
        Buffer_val_0_we1 = ap_const_logic_1;
    end else begin
        Buffer_val_0_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_54 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_69 or ap_reg_ppiten_pp0_it5) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        Buffer_val_1_ce0 = ap_const_logic_1;
    end else begin
        Buffer_val_1_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_54 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_69 or ap_reg_ppiten_pp0_it5) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        Buffer_val_1_ce1 = ap_const_logic_1;
    end else begin
        Buffer_val_1_ce1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_54 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_69 or ap_reg_ppiten_pp0_it5 or ap_reg_ppstg_tmp_7_reg_708_pp0_it1) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_7_reg_708_pp0_it1))) begin
        Buffer_val_1_we1 = ap_const_logic_1;
    end else begin
        Buffer_val_1_we1 = ap_const_logic_0;
    end
end

always @ (ap_done_reg or exitcond1_fu_192_p2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ap_const_lv1_0 == exitcond1_fu_192_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (exitcond1_fu_192_p2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ap_const_lv1_0 == exitcond1_fu_192_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_45) begin
    if (ap_sig_bdd_45) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_22) begin
    if (ap_sig_bdd_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_83) begin
    if (ap_sig_bdd_83) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_207) begin
    if (ap_sig_bdd_207) begin
        ap_sig_nseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_nseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or tmp_3_reg_704 or ap_sig_bdd_54 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_69 or ap_reg_ppiten_pp0_it5) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (tmp_3_reg_704 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        grad_out_data_stream_V_read = ap_const_logic_1;
    end else begin
        grad_out_data_stream_V_read = ap_const_logic_0;
    end
end

always @ (p_1_reg_180 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it1 or exitcond_reg_695 or j_V_reg_699) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_lv1_0 == exitcond_reg_695))) begin
        p_1_phi_fu_184_p4 = j_V_reg_699;
    end else begin
        p_1_phi_fu_184_p4 = p_1_reg_180;
    end
end

always @ (ap_sig_bdd_54 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_or_cond4_reg_736_pp0_it4 or ap_sig_bdd_69 or ap_reg_ppiten_pp0_it5) begin
    if (((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_736_pp0_it4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        supressed_data_stream_V_write = ap_const_logic_1;
    end else begin
        supressed_data_stream_V_write = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_54 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_69 or ap_reg_ppiten_pp0_it5 or exitcond1_fu_192_p2 or exitcond_fu_226_p2 or ap_sig_bdd_197) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_197) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(ap_const_lv1_0 == exitcond1_fu_192_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_lv1_0 == exitcond_fu_226_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_54 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_69 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_lv1_0 == exitcond_fu_226_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign Buffer_val_0_address0 = tmp_8_fu_260_p1;

assign Buffer_val_0_address1 = tmp_9_fu_329_p1;

assign Buffer_val_0_d1 = pixel_value_s_fu_84;

assign Buffer_val_1_address0 = tmp_8_fu_260_p1;

assign Buffer_val_1_address1 = ap_reg_ppstg_Buffer_val_1_addr_reg_715_pp0_it1;

assign Buffer_val_1_d1 = temp1_reg_740;

assign Win_val_0_0_0_Win_val_0_0_1_fu_375_p3 = ((ap_reg_ppstg_tmp_7_reg_708_pp0_it1[0:0] === 1'b1) ? Win_val_0_1_fu_88 : pixel_value_s_fu_84);

assign Win_val_1_0_0_Win_val_1_0_1_fu_368_p3 = ((ap_reg_ppstg_tmp_7_reg_708_pp0_it1[0:0] === 1'b1) ? Win_val_1_1_fu_96 : temp1_s_fu_76);

assign Win_val_2_0_0_Win_val_2_0_1_fu_361_p3 = ((ap_reg_ppstg_tmp_7_reg_708_pp0_it1[0:0] === 1'b1) ? Win_val_2_1_fu_104 : temp2_s_fu_80);


always @ (ap_start or ap_done_reg) begin
    ap_sig_bdd_197 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end


always @ (ap_NS_fsm) begin
    ap_sig_bdd_207 = (ap_const_lv1_1 == ap_NS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_22 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_45 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (grad_out_data_stream_V_empty_n or tmp_3_reg_704) begin
    ap_sig_bdd_54 = ((grad_out_data_stream_V_empty_n == ap_const_logic_0) & (tmp_3_reg_704 == ap_const_lv1_0));
end


always @ (supressed_data_stream_V_full_n or ap_reg_ppstg_or_cond4_reg_736_pp0_it4) begin
    ap_sig_bdd_69 = ((supressed_data_stream_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_736_pp0_it4));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_83 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

assign current_dir_fu_382_p1 = Win_val_1_1_fu_96[1:0];

assign exitcond1_fu_192_p2 = (p_s_reg_168 == ap_const_lv11_401? 1'b1: 1'b0);

assign exitcond_fu_226_p2 = (p_1_phi_fu_184_p4 == ap_const_lv11_401? 1'b1: 1'b0);

assign ga_fu_583_p3 = ((sel_tmp2_reg_755[0:0] === 1'b1) ? tmp_13_reg_771 : tmp_32_reg_776);

assign gb_fu_578_p3 = ((sel_tmp2_reg_755[0:0] === 1'b1) ? tmp_11_reg_761 : tmp_27_reg_766);

assign i_V_fu_198_p2 = (p_s_reg_168 + ap_const_lv11_1);

assign icmp1_fu_276_p2 = (tmp_20_fu_266_p4 == ap_const_lv10_0? 1'b1: 1'b0);

assign icmp_fu_214_p2 = (tmp_fu_204_p4 == ap_const_lv10_0? 1'b1: 1'b0);

assign j_V_fu_232_p2 = (p_1_phi_fu_184_p4 + ap_const_lv11_1);

assign or_cond2_fu_321_p2 = (tmp_21_reg_731 | tmp9_reg_726);

assign or_cond3_fu_600_p2 = (tmp_14_reg_786 & tmp_15_reg_791);

assign or_cond4_fu_301_p2 = (tmp_2_reg_690 | tmp_16_fu_295_p2);

assign out_pixel_val_2_fu_571_p3 = {{tmp_12_reg_750}, {ap_const_lv2_0}};

assign out_pixel_val_fu_604_p3 = ((or_cond3_fu_600_p2[0:0] === 1'b1) ? out_pixel_val_2_reg_781 : ap_const_lv8_0);

assign sel_tmp1_fu_408_p2 = (tmp_s_fu_390_p2 ^ ap_const_lv1_1);

assign sel_tmp2_fu_414_p2 = (tmp_5_fu_396_p2 & sel_tmp1_fu_408_p2);

assign supressed_data_stream_V_din = tmp_33_reg_796;

assign tmp9_fu_282_p2 = (icmp_reg_685 | icmp1_fu_276_p2);

assign tmp_10_fu_402_p2 = (current_dir_fu_382_p1 == ap_const_lv2_2? 1'b1: 1'b0);

assign tmp_12_fu_386_p1 = Win_val_1_1_fu_96[5:0];

assign tmp_14_fu_588_p2 = (out_pixel_val_2_fu_571_p3 > ga_fu_583_p3? 1'b1: 1'b0);

assign tmp_15_fu_594_p2 = (out_pixel_val_2_fu_571_p3 > gb_fu_578_p3? 1'b1: 1'b0);

assign tmp_16_fu_295_p2 = (p_1_phi_fu_184_p4 == ap_const_lv11_0? 1'b1: 1'b0);

assign tmp_20_fu_266_p4 = {{p_1_phi_fu_184_p4[ap_const_lv32_A : ap_const_lv32_1]}};

assign tmp_22_fu_430_p4 = {{Win_val_1_1_1_fu_100[ap_const_lv32_9 : ap_const_lv32_2]}};

assign tmp_24_fu_440_p4 = {{Win_val_2_1_fu_104[ap_const_lv32_9 : ap_const_lv32_2]}};

assign tmp_25_fu_450_p4 = {{Win_val_0_0_0_Win_val_0_0_1_fu_375_p3[ap_const_lv32_9 : ap_const_lv32_2]}};

assign tmp_26_fu_460_p3 = ((tmp_10_fu_402_p2[0:0] === 1'b1) ? tmp_24_fu_440_p4 : tmp_25_fu_450_p4);

assign tmp_27_fu_468_p3 = ((tmp_s_fu_390_p2[0:0] === 1'b1) ? tmp_22_fu_430_p4 : tmp_26_fu_460_p3);

assign tmp_28_fu_486_p4 = {{Win_val_1_0_0_Win_val_1_0_1_fu_368_p3[ap_const_lv32_9 : ap_const_lv32_2]}};

assign tmp_29_fu_496_p4 = {{Win_val_0_1_fu_88[ap_const_lv32_9 : ap_const_lv32_2]}};

assign tmp_2_fu_220_p2 = (p_s_reg_168 == ap_const_lv11_0? 1'b1: 1'b0);

assign tmp_30_fu_506_p4 = {{Win_val_2_1_1_fu_108[ap_const_lv32_9 : ap_const_lv32_2]}};

assign tmp_31_fu_516_p3 = ((tmp_10_fu_402_p2[0:0] === 1'b1) ? tmp_29_fu_496_p4 : tmp_30_fu_506_p4);

assign tmp_32_fu_524_p3 = ((tmp_s_fu_390_p2[0:0] === 1'b1) ? tmp_28_fu_486_p4 : tmp_31_fu_516_p3);

assign tmp_33_fu_611_p3 = ((ap_reg_ppstg_or_cond2_reg_745_pp0_it3[0:0] === 1'b1) ? ap_const_lv8_0 : out_pixel_val_fu_604_p3);

assign tmp_4_fu_238_p2 = (p_1_phi_fu_184_p4 | p_s_reg_168);

assign tmp_5_fu_396_p2 = (current_dir_fu_382_p1 == ap_const_lv2_1? 1'b1: 1'b0);

assign tmp_7_fu_252_p3 = p_1_phi_fu_184_p4[ap_const_lv32_A];

assign tmp_8_fu_260_p1 = p_1_phi_fu_184_p4;

assign tmp_9_fu_329_p1 = ap_reg_ppstg_p_1_reg_180_pp0_it1;

assign tmp_fu_204_p4 = {{p_s_reg_168[ap_const_lv32_A : ap_const_lv32_1]}};

assign tmp_s_fu_390_p2 = (current_dir_fu_382_p1 == ap_const_lv2_0? 1'b1: 1'b0);
always @ (posedge ap_clk) begin
    out_pixel_val_2_reg_781[1:0] <= 2'b00;
    tmp_33_reg_796[1:0] <= 2'b00;
end



endmodule //canny_nonmax_supression

