// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module canny_grad_computation (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        grad_x_data_stream_V_dout,
        grad_x_data_stream_V_empty_n,
        grad_x_data_stream_V_read,
        grad_y_data_stream_V_dout,
        grad_y_data_stream_V_empty_n,
        grad_y_data_stream_V_read,
        grad_out_data_stream_V_din,
        grad_out_data_stream_V_full_n,
        grad_out_data_stream_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 3'b1;
parameter    ap_ST_st2_fsm_1 = 3'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 3'b100;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv11_400 = 11'b10000000000;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] grad_x_data_stream_V_dout;
input   grad_x_data_stream_V_empty_n;
output   grad_x_data_stream_V_read;
input  [7:0] grad_y_data_stream_V_dout;
input   grad_y_data_stream_V_empty_n;
output   grad_y_data_stream_V_read;
output  [15:0] grad_out_data_stream_V_din;
input   grad_out_data_stream_V_full_n;
output   grad_out_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg grad_x_data_stream_V_read;
reg grad_y_data_stream_V_read;
reg grad_out_data_stream_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm = 3'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_22;
reg   [10:0] p_8_reg_94;
wire   [0:0] exitcond4_fu_105_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_50;
wire   [10:0] i_V_fu_111_p2;
reg   [10:0] i_V_reg_373;
wire   [0:0] exitcond_fu_117_p2;
reg   [0:0] exitcond_reg_378;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_bdd_61;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_sig_bdd_72;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_378_pp0_it3;
reg    ap_sig_bdd_84;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_378_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_378_pp0_it2;
wire   [10:0] j_V_fu_123_p2;
wire   [0:0] abscond_i_fu_135_p2;
reg   [0:0] abscond_i_reg_387;
reg   [0:0] ap_reg_ppstg_abscond_i_reg_387_pp0_it2;
wire   [7:0] abs_gx_fu_141_p3;
reg   [7:0] abs_gx_reg_392;
wire   [7:0] abs_gy_fu_161_p3;
reg   [7:0] abs_gy_reg_401;
wire   [8:0] element_grad_fu_177_p2;
reg   [8:0] element_grad_reg_410;
reg   [8:0] ap_reg_ppstg_element_grad_reg_410_pp0_it2;
reg   [8:0] ap_reg_ppstg_element_grad_reg_410_pp0_it3;
wire   [0:0] tmp_36_fu_183_p2;
reg   [0:0] tmp_36_reg_415;
reg   [0:0] ap_reg_ppstg_tmp_36_reg_415_pp0_it2;
wire   [0:0] tmp_38_fu_189_p2;
reg   [0:0] tmp_38_reg_421;
reg   [0:0] ap_reg_ppstg_tmp_38_reg_421_pp0_it2;
wire   [0:0] ult_fu_195_p2;
reg   [0:0] ult_reg_427;
wire   [0:0] tmp8_fu_203_p2;
reg   [0:0] tmp8_reg_432;
wire   [0:0] ult1_fu_221_p2;
reg   [0:0] ult1_reg_437;
wire   [0:0] rev1_fu_231_p2;
reg   [0:0] rev1_reg_442;
wire   [0:0] tmp_41_fu_244_p2;
reg   [0:0] tmp_41_reg_447;
wire   [0:0] ult3_fu_250_p2;
reg   [0:0] ult3_reg_453;
wire   [0:0] or_cond7_fu_261_p2;
reg   [0:0] or_cond7_reg_458;
wire   [1:0] dir_g_1_fu_288_p3;
reg   [1:0] dir_g_1_reg_463;
wire   [0:0] rev2_fu_295_p2;
reg   [0:0] rev2_reg_468;
wire   [1:0] sel_tmp1_fu_307_p3;
reg   [1:0] sel_tmp1_reg_473;
wire   [0:0] sel_tmp3_fu_321_p2;
reg   [0:0] sel_tmp3_reg_478;
wire   [0:0] tmp10_fu_327_p2;
reg   [0:0] tmp10_reg_483;
reg   [10:0] p_s_reg_83;
reg    ap_sig_bdd_161;
wire   [7:0] neg_i_fu_129_p2;
wire   [0:0] abscond_i1_fu_155_p2;
wire   [7:0] neg_i1_fu_149_p2;
wire   [8:0] tmp_132_cast_fu_173_p1;
wire   [8:0] tmp_131_cast_fu_169_p1;
wire   [0:0] tmp_37_fu_199_p2;
wire   [8:0] tmp_39_fu_214_p3;
wire   [8:0] tmp_136_cast_fu_208_p1;
wire   [0:0] ult2_fu_227_p2;
wire   [8:0] tmp_137_cast_fu_211_p1;
wire   [8:0] tmp_40_fu_237_p3;
wire   [0:0] rev9_fu_256_p2;
wire   [0:0] rev_fu_270_p2;
wire   [0:0] tmp9_fu_279_p2;
wire   [1:0] dir_g_2_fu_300_p3;
wire   [1:0] dir_g_cast_fu_275_p1;
wire   [0:0] or_cond_fu_266_p2;
wire   [0:0] sel_tmp2_fu_315_p2;
wire   [0:0] or_cond8_fu_283_p2;
wire   [0:0] sel_tmp6_fu_345_p2;
wire   [1:0] dir_g_3_cast_fu_333_p3;
wire   [1:0] sel_tmp4_fu_340_p3;
wire   [1:0] dir_g_6_fu_349_p3;
wire   [10:0] element_final_fu_357_p3;
reg   [2:0] ap_NS_fsm;




always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond4_fu_105_p2 == ap_const_lv1_0))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(exitcond_fu_117_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond4_fu_105_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (exitcond_fu_117_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond4_fu_105_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(exitcond_fu_117_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond4_fu_105_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond4_fu_105_p2 == ap_const_lv1_0))) begin
        p_8_reg_94 <= ap_const_lv11_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (exitcond_fu_117_p2 == ap_const_lv1_0))) begin
        p_8_reg_94 <= j_V_fu_123_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(exitcond_fu_117_p2 == ap_const_lv1_0))) begin
        p_s_reg_83 <= i_V_reg_373;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_161)) begin
        p_s_reg_83 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_reg_378 == ap_const_lv1_0) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        abs_gx_reg_392 <= abs_gx_fu_141_p3;
        abs_gy_reg_401 <= abs_gy_fu_161_p3;
        abscond_i_reg_387 <= abscond_i_fu_135_p2;
        element_grad_reg_410 <= element_grad_fu_177_p2;
        tmp_36_reg_415 <= tmp_36_fu_183_p2;
        tmp_38_reg_421 <= tmp_38_fu_189_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
        ap_reg_ppstg_abscond_i_reg_387_pp0_it2 <= abscond_i_reg_387;
        ap_reg_ppstg_element_grad_reg_410_pp0_it2 <= element_grad_reg_410;
        ap_reg_ppstg_element_grad_reg_410_pp0_it3 <= ap_reg_ppstg_element_grad_reg_410_pp0_it2;
        ap_reg_ppstg_exitcond_reg_378_pp0_it2 <= ap_reg_ppstg_exitcond_reg_378_pp0_it1;
        ap_reg_ppstg_exitcond_reg_378_pp0_it3 <= ap_reg_ppstg_exitcond_reg_378_pp0_it2;
        ap_reg_ppstg_tmp_36_reg_415_pp0_it2 <= tmp_36_reg_415;
        ap_reg_ppstg_tmp_38_reg_421_pp0_it2 <= tmp_38_reg_421;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        ap_reg_ppstg_exitcond_reg_378_pp0_it1 <= exitcond_reg_378;
        exitcond_reg_378 <= exitcond_fu_117_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_378_pp0_it2))) begin
        dir_g_1_reg_463 <= dir_g_1_fu_288_p3;
        or_cond7_reg_458 <= or_cond7_fu_261_p2;
        rev2_reg_468 <= rev2_fu_295_p2;
        sel_tmp1_reg_473 <= sel_tmp1_fu_307_p3;
        sel_tmp3_reg_478 <= sel_tmp3_fu_321_p2;
        tmp10_reg_483 <= tmp10_fu_327_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        i_V_reg_373 <= i_V_fu_111_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_378_pp0_it1))) begin
        rev1_reg_442 <= rev1_fu_231_p2;
        tmp8_reg_432 <= tmp8_fu_203_p2;
        tmp_41_reg_447 <= tmp_41_fu_244_p2;
        ult1_reg_437 <= ult1_fu_221_p2;
        ult3_reg_453 <= ult3_fu_250_p2;
        ult_reg_427 <= ult_fu_195_p2;
    end
end

always @ (ap_done_reg or exitcond4_fu_105_p2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond4_fu_105_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (exitcond4_fu_105_p2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond4_fu_105_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_61) begin
    if (ap_sig_bdd_61) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_22) begin
    if (ap_sig_bdd_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_50) begin
    if (ap_sig_bdd_50) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_72 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_378_pp0_it3 or ap_sig_bdd_84 or ap_reg_ppiten_pp0_it4) begin
    if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_378_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        grad_out_data_stream_V_write = ap_const_logic_1;
    end else begin
        grad_out_data_stream_V_write = ap_const_logic_0;
    end
end

always @ (exitcond_reg_378 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_84 or ap_reg_ppiten_pp0_it4) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_reg_378 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        grad_x_data_stream_V_read = ap_const_logic_1;
    end else begin
        grad_x_data_stream_V_read = ap_const_logic_0;
    end
end

always @ (exitcond_reg_378 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_84 or ap_reg_ppiten_pp0_it4) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_reg_378 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        grad_y_data_stream_V_read = ap_const_logic_1;
    end else begin
        grad_y_data_stream_V_read = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or exitcond4_fu_105_p2 or exitcond_fu_117_p2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_84 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_161) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_161) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(exitcond4_fu_105_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(exitcond_fu_117_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_84 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(exitcond_fu_117_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign abs_gx_fu_141_p3 = ((abscond_i_fu_135_p2[0:0] === 1'b1) ? grad_x_data_stream_V_dout : neg_i_fu_129_p2);

assign abs_gy_fu_161_p3 = ((abscond_i1_fu_155_p2[0:0] === 1'b1) ? grad_y_data_stream_V_dout : neg_i1_fu_149_p2);

assign abscond_i1_fu_155_p2 = (grad_y_data_stream_V_dout != ap_const_lv8_0? 1'b1: 1'b0);

assign abscond_i_fu_135_p2 = (grad_x_data_stream_V_dout != ap_const_lv8_0? 1'b1: 1'b0);


always @ (ap_start or ap_done_reg) begin
    ap_sig_bdd_161 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_22 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_50 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_61 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (grad_x_data_stream_V_empty_n or grad_y_data_stream_V_empty_n or exitcond_reg_378) begin
    ap_sig_bdd_72 = (((grad_x_data_stream_V_empty_n == ap_const_logic_0) & (exitcond_reg_378 == ap_const_lv1_0)) | ((exitcond_reg_378 == ap_const_lv1_0) & (grad_y_data_stream_V_empty_n == ap_const_logic_0)));
end


always @ (grad_out_data_stream_V_full_n or ap_reg_ppstg_exitcond_reg_378_pp0_it3) begin
    ap_sig_bdd_84 = ((grad_out_data_stream_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_378_pp0_it3));
end

assign dir_g_1_fu_288_p3 = ((tmp_41_reg_447[0:0] === 1'b1) ? ap_const_lv2_2 : ap_const_lv2_1);

assign dir_g_2_fu_300_p3 = ((tmp_41_reg_447[0:0] === 1'b1) ? ap_const_lv2_2 : ap_const_lv2_3);

assign dir_g_3_cast_fu_333_p3 = ((rev2_reg_468[0:0] === 1'b1) ? ap_const_lv2_3 : ap_const_lv2_0);

assign dir_g_6_fu_349_p3 = ((sel_tmp6_fu_345_p2[0:0] === 1'b1) ? dir_g_3_cast_fu_333_p3 : sel_tmp4_fu_340_p3);

assign dir_g_cast_fu_275_p1 = rev_fu_270_p2;

assign element_final_fu_357_p3 = {{ap_reg_ppstg_element_grad_reg_410_pp0_it3}, {dir_g_6_fu_349_p3}};

assign element_grad_fu_177_p2 = (tmp_132_cast_fu_173_p1 + tmp_131_cast_fu_169_p1);

assign exitcond4_fu_105_p2 = (p_s_reg_83 == ap_const_lv11_400? 1'b1: 1'b0);

assign exitcond_fu_117_p2 = (p_8_reg_94 == ap_const_lv11_400? 1'b1: 1'b0);

assign grad_out_data_stream_V_din = element_final_fu_357_p3;

assign i_V_fu_111_p2 = (p_s_reg_83 + ap_const_lv11_1);

assign j_V_fu_123_p2 = (p_8_reg_94 + ap_const_lv11_1);

assign neg_i1_fu_149_p2 = (ap_const_lv8_0 - grad_y_data_stream_V_dout);

assign neg_i_fu_129_p2 = (ap_const_lv8_0 - grad_x_data_stream_V_dout);

assign or_cond7_fu_261_p2 = (rev9_fu_256_p2 | ap_reg_ppstg_tmp_36_reg_415_pp0_it2);

assign or_cond8_fu_283_p2 = (tmp9_fu_279_p2 | ap_reg_ppstg_abscond_i_reg_387_pp0_it2);

assign or_cond_fu_266_p2 = (tmp8_reg_432 | ap_reg_ppstg_tmp_36_reg_415_pp0_it2);

assign rev1_fu_231_p2 = (ult2_fu_227_p2 ^ ap_const_lv1_1);

assign rev2_fu_295_p2 = (ult3_reg_453 ^ ap_const_lv1_1);

assign rev9_fu_256_p2 = (ult_reg_427 ^ ap_const_lv1_1);

assign rev_fu_270_p2 = (ult1_reg_437 ^ ap_const_lv1_1);

assign sel_tmp1_fu_307_p3 = ((or_cond7_fu_261_p2[0:0] === 1'b1) ? dir_g_2_fu_300_p3 : dir_g_cast_fu_275_p1);

assign sel_tmp2_fu_315_p2 = (or_cond_fu_266_p2 ^ ap_const_lv1_1);

assign sel_tmp3_fu_321_p2 = (or_cond7_fu_261_p2 & sel_tmp2_fu_315_p2);

assign sel_tmp4_fu_340_p3 = ((sel_tmp3_reg_478[0:0] === 1'b1) ? dir_g_1_reg_463 : sel_tmp1_reg_473);

assign sel_tmp6_fu_345_p2 = (tmp10_reg_483 & or_cond7_reg_458);

assign tmp10_fu_327_p2 = (or_cond_fu_266_p2 & or_cond8_fu_283_p2);

assign tmp8_fu_203_p2 = (tmp_38_reg_421 | tmp_37_fu_199_p2);

assign tmp9_fu_279_p2 = (rev1_reg_442 | ap_reg_ppstg_tmp_38_reg_421_pp0_it2);

assign tmp_131_cast_fu_169_p1 = grad_x_data_stream_V_dout;

assign tmp_132_cast_fu_173_p1 = grad_y_data_stream_V_dout;

assign tmp_136_cast_fu_208_p1 = abs_gx_reg_392;

assign tmp_137_cast_fu_211_p1 = abs_gy_reg_401;

assign tmp_36_fu_183_p2 = (grad_x_data_stream_V_dout == ap_const_lv8_0? 1'b1: 1'b0);

assign tmp_37_fu_199_p2 = (abs_gx_reg_392 > abs_gy_reg_401? 1'b1: 1'b0);

assign tmp_38_fu_189_p2 = (grad_y_data_stream_V_dout == ap_const_lv8_0? 1'b1: 1'b0);

assign tmp_39_fu_214_p3 = {{abs_gy_reg_401}, {ap_const_lv1_0}};

assign tmp_40_fu_237_p3 = {{abs_gx_reg_392}, {ap_const_lv1_0}};

assign tmp_41_fu_244_p2 = (tmp_137_cast_fu_211_p1 > tmp_40_fu_237_p3? 1'b1: 1'b0);

assign ult1_fu_221_p2 = (tmp_39_fu_214_p3 < tmp_136_cast_fu_208_p1? 1'b1: 1'b0);

assign ult2_fu_227_p2 = (abs_gx_reg_392 < abs_gy_reg_401? 1'b1: 1'b0);

assign ult3_fu_250_p2 = (tmp_40_fu_237_p3 < tmp_137_cast_fu_211_p1? 1'b1: 1'b0);

assign ult_fu_195_p2 = (abs_gy_reg_401 < abs_gx_reg_392? 1'b1: 1'b0);


endmodule //canny_grad_computation

