// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _canny_hysterisis_HH_
#define _canny_hysterisis_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "canny_Filter2D_1_k_buf_0_val_3.h"

namespace ap_rtl {

struct canny_hysterisis : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > supressed_data_stream_V_dout;
    sc_in< sc_logic > supressed_data_stream_V_empty_n;
    sc_out< sc_logic > supressed_data_stream_V_read;
    sc_out< sc_lv<8> > hysterisis_Image_data_stream_V_din;
    sc_in< sc_logic > hysterisis_Image_data_stream_V_full_n;
    sc_out< sc_logic > hysterisis_Image_data_stream_V_write;


    // Module declarations
    canny_hysterisis(sc_module_name name);
    SC_HAS_PROCESS(canny_hysterisis);

    ~canny_hysterisis();

    sc_trace_file* mVcdFile;

    canny_Filter2D_1_k_buf_0_val_3* Buffer_val_0_U;
    canny_Filter2D_1_k_buf_0_val_3* Buffer_val_1_U;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_22;
    sc_signal< sc_lv<11> > p_2_reg_153;
    sc_signal< sc_lv<1> > exitcond2_fu_164_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_46;
    sc_signal< sc_lv<11> > i_V_fu_170_p2;
    sc_signal< sc_lv<11> > i_V_reg_491;
    sc_signal< sc_lv<1> > icmp_fu_186_p2;
    sc_signal< sc_lv<1> > icmp_reg_496;
    sc_signal< sc_lv<1> > notlhs_fu_192_p2;
    sc_signal< sc_lv<1> > notlhs_reg_501;
    sc_signal< sc_lv<1> > tmp_s_fu_198_p2;
    sc_signal< sc_lv<1> > tmp_s_reg_506;
    sc_signal< sc_lv<1> > exitcond_fu_204_p2;
    sc_signal< sc_lv<1> > exitcond_reg_511;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_2;
    sc_signal< bool > ap_sig_bdd_66;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it3;
    sc_signal< sc_lv<1> > or_cond6_reg_583;
    sc_signal< sc_lv<1> > ap_reg_ppstg_or_cond6_reg_583_pp0_it3;
    sc_signal< bool > ap_sig_bdd_84;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it4;
    sc_signal< sc_lv<11> > j_V_fu_210_p2;
    sc_signal< sc_lv<10> > Buffer_val_1_addr_reg_520;
    sc_signal< sc_lv<10> > ap_reg_ppstg_Buffer_val_1_addr_reg_520_pp0_it1;
    sc_signal< sc_lv<10> > Buffer_val_0_addr_reg_526;
    sc_signal< sc_lv<1> > icmp2_fu_232_p2;
    sc_signal< sc_lv<1> > icmp2_reg_532;
    sc_signal< sc_lv<1> > tmp9_fu_250_p2;
    sc_signal< sc_lv<1> > tmp9_reg_537;
    sc_signal< sc_lv<1> > tmp10_fu_255_p2;
    sc_signal< sc_lv<1> > tmp10_reg_542;
    sc_signal< sc_lv<8> > Buffer_val_1_q0;
    sc_signal< sc_lv<8> > temp2_reg_547;
    sc_signal< sc_lv<8> > Buffer_val_0_q0;
    sc_signal< sc_lv<8> > temp1_reg_552;
    sc_signal< sc_lv<1> > tmp1_fu_284_p2;
    sc_signal< sc_lv<1> > tmp1_reg_558;
    sc_signal< sc_lv<1> > tmp_27_fu_313_p2;
    sc_signal< sc_lv<1> > tmp_27_reg_563;
    sc_signal< sc_lv<1> > tmp3_fu_331_p2;
    sc_signal< sc_lv<1> > tmp3_reg_568;
    sc_signal< sc_lv<1> > tmp4_fu_337_p2;
    sc_signal< sc_lv<1> > tmp4_reg_573;
    sc_signal< sc_lv<1> > tmp8_fu_343_p2;
    sc_signal< sc_lv<1> > tmp8_reg_578;
    sc_signal< sc_lv<1> > or_cond6_fu_349_p2;
    sc_signal< sc_lv<1> > ap_reg_ppstg_or_cond6_reg_583_pp0_it2;
    sc_signal< sc_lv<1> > or_cond8_fu_392_p2;
    sc_signal< sc_lv<1> > or_cond8_reg_587;
    sc_signal< sc_lv<1> > tmp2_fu_406_p2;
    sc_signal< sc_lv<1> > tmp2_reg_592;
    sc_signal< sc_lv<1> > tmp6_fu_410_p2;
    sc_signal< sc_lv<1> > tmp6_reg_597;
    sc_signal< sc_lv<1> > tmp7_fu_415_p2;
    sc_signal< sc_lv<1> > tmp7_reg_602;
    sc_signal< sc_lv<1> > tmp_31_fu_434_p2;
    sc_signal< sc_lv<1> > tmp_31_reg_607;
    sc_signal< sc_lv<10> > Buffer_val_0_address0;
    sc_signal< sc_logic > Buffer_val_0_ce0;
    sc_signal< sc_lv<10> > Buffer_val_0_address1;
    sc_signal< sc_logic > Buffer_val_0_ce1;
    sc_signal< sc_logic > Buffer_val_0_we1;
    sc_signal< sc_lv<8> > Buffer_val_0_d1;
    sc_signal< sc_lv<10> > Buffer_val_1_address0;
    sc_signal< sc_logic > Buffer_val_1_ce0;
    sc_signal< sc_lv<10> > Buffer_val_1_address1;
    sc_signal< sc_logic > Buffer_val_1_ce1;
    sc_signal< sc_logic > Buffer_val_1_we1;
    sc_signal< sc_lv<8> > Buffer_val_1_d1;
    sc_signal< sc_lv<11> > p_s_reg_142;
    sc_signal< bool > ap_sig_bdd_172;
    sc_signal< sc_lv<64> > tmp_20_fu_216_p1;
    sc_signal< sc_lv<8> > Win_val_0_1_fu_68;
    sc_signal< sc_lv<8> > Win_val_0_1_2_fu_72;
    sc_signal< sc_lv<8> > Win_val_1_1_fu_76;
    sc_signal< sc_lv<8> > Win_val_1_1_2_fu_80;
    sc_signal< sc_lv<8> > Win_val_2_1_fu_84;
    sc_signal< sc_lv<8> > Win_val_2_1_2_fu_88;
    sc_signal< sc_lv<10> > tmp_fu_176_p4;
    sc_signal< sc_lv<10> > tmp_37_fu_222_p4;
    sc_signal< sc_lv<1> > notrhs_fu_238_p2;
    sc_signal< sc_lv<1> > tmp_32_fu_244_p2;
    sc_signal< sc_lv<1> > tmp_21_fu_278_p2;
    sc_signal< sc_lv<1> > tmp_22_fu_289_p2;
    sc_signal< sc_lv<1> > tmp_23_fu_295_p2;
    sc_signal< sc_lv<1> > tmp_24_fu_301_p2;
    sc_signal< sc_lv<1> > tmp_25_fu_307_p2;
    sc_signal< sc_lv<1> > tmp_29_fu_319_p2;
    sc_signal< sc_lv<1> > tmp_30_fu_325_p2;
    sc_signal< sc_lv<1> > tmp_26_fu_396_p2;
    sc_signal< sc_lv<1> > tmp_28_fu_401_p2;
    sc_signal< sc_lv<1> > tmp5_fu_420_p2;
    sc_signal< sc_lv<1> > or_cond_fu_424_p2;
    sc_signal< sc_lv<1> > not_or_cond8_fu_429_p2;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_st1_fsm_0;
    static const sc_lv<3> ap_ST_st2_fsm_1;
    static const sc_lv<3> ap_ST_pp0_stg0_fsm_2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<11> ap_const_lv11_400;
    static const sc_lv<11> ap_const_lv11_1;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<11> ap_const_lv11_3FF;
    static const sc_lv<8> ap_const_lv8_A0;
    static const sc_lv<8> ap_const_lv8_DC;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<8> ap_const_lv8_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_Buffer_val_0_address0();
    void thread_Buffer_val_0_address1();
    void thread_Buffer_val_0_ce0();
    void thread_Buffer_val_0_ce1();
    void thread_Buffer_val_0_d1();
    void thread_Buffer_val_0_we1();
    void thread_Buffer_val_1_address0();
    void thread_Buffer_val_1_address1();
    void thread_Buffer_val_1_ce0();
    void thread_Buffer_val_1_ce1();
    void thread_Buffer_val_1_d1();
    void thread_Buffer_val_1_we1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_172();
    void thread_ap_sig_bdd_22();
    void thread_ap_sig_bdd_46();
    void thread_ap_sig_bdd_66();
    void thread_ap_sig_bdd_84();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_2();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_exitcond2_fu_164_p2();
    void thread_exitcond_fu_204_p2();
    void thread_hysterisis_Image_data_stream_V_din();
    void thread_hysterisis_Image_data_stream_V_write();
    void thread_i_V_fu_170_p2();
    void thread_icmp2_fu_232_p2();
    void thread_icmp_fu_186_p2();
    void thread_j_V_fu_210_p2();
    void thread_not_or_cond8_fu_429_p2();
    void thread_notlhs_fu_192_p2();
    void thread_notrhs_fu_238_p2();
    void thread_or_cond6_fu_349_p2();
    void thread_or_cond8_fu_392_p2();
    void thread_or_cond_fu_424_p2();
    void thread_supressed_data_stream_V_read();
    void thread_tmp10_fu_255_p2();
    void thread_tmp1_fu_284_p2();
    void thread_tmp2_fu_406_p2();
    void thread_tmp3_fu_331_p2();
    void thread_tmp4_fu_337_p2();
    void thread_tmp5_fu_420_p2();
    void thread_tmp6_fu_410_p2();
    void thread_tmp7_fu_415_p2();
    void thread_tmp8_fu_343_p2();
    void thread_tmp9_fu_250_p2();
    void thread_tmp_20_fu_216_p1();
    void thread_tmp_21_fu_278_p2();
    void thread_tmp_22_fu_289_p2();
    void thread_tmp_23_fu_295_p2();
    void thread_tmp_24_fu_301_p2();
    void thread_tmp_25_fu_307_p2();
    void thread_tmp_26_fu_396_p2();
    void thread_tmp_27_fu_313_p2();
    void thread_tmp_28_fu_401_p2();
    void thread_tmp_29_fu_319_p2();
    void thread_tmp_30_fu_325_p2();
    void thread_tmp_31_fu_434_p2();
    void thread_tmp_32_fu_244_p2();
    void thread_tmp_37_fu_222_p4();
    void thread_tmp_fu_176_p4();
    void thread_tmp_s_fu_198_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
