// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "canny_hysterisis.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic canny_hysterisis::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic canny_hysterisis::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> canny_hysterisis::ap_ST_st1_fsm_0 = "1";
const sc_lv<3> canny_hysterisis::ap_ST_st2_fsm_1 = "10";
const sc_lv<3> canny_hysterisis::ap_ST_pp0_stg0_fsm_2 = "100";
const sc_lv<32> canny_hysterisis::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> canny_hysterisis::ap_const_lv1_1 = "1";
const sc_lv<32> canny_hysterisis::ap_const_lv32_1 = "1";
const sc_lv<1> canny_hysterisis::ap_const_lv1_0 = "0";
const sc_lv<32> canny_hysterisis::ap_const_lv32_2 = "10";
const sc_lv<11> canny_hysterisis::ap_const_lv11_0 = "00000000000";
const sc_lv<11> canny_hysterisis::ap_const_lv11_400 = "10000000000";
const sc_lv<11> canny_hysterisis::ap_const_lv11_1 = "1";
const sc_lv<32> canny_hysterisis::ap_const_lv32_A = "1010";
const sc_lv<10> canny_hysterisis::ap_const_lv10_0 = "0000000000";
const sc_lv<11> canny_hysterisis::ap_const_lv11_3FF = "1111111111";
const sc_lv<8> canny_hysterisis::ap_const_lv8_A0 = "10100000";
const sc_lv<8> canny_hysterisis::ap_const_lv8_DC = "11011100";
const sc_lv<8> canny_hysterisis::ap_const_lv8_FF = "11111111";
const sc_lv<8> canny_hysterisis::ap_const_lv8_0 = "00000000";

canny_hysterisis::canny_hysterisis(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Buffer_val_0_U = new canny_Filter2D_1_k_buf_0_val_3("Buffer_val_0_U");
    Buffer_val_0_U->clk(ap_clk);
    Buffer_val_0_U->reset(ap_rst);
    Buffer_val_0_U->address0(Buffer_val_0_address0);
    Buffer_val_0_U->ce0(Buffer_val_0_ce0);
    Buffer_val_0_U->q0(Buffer_val_0_q0);
    Buffer_val_0_U->address1(Buffer_val_0_address1);
    Buffer_val_0_U->ce1(Buffer_val_0_ce1);
    Buffer_val_0_U->we1(Buffer_val_0_we1);
    Buffer_val_0_U->d1(Buffer_val_0_d1);
    Buffer_val_1_U = new canny_Filter2D_1_k_buf_0_val_3("Buffer_val_1_U");
    Buffer_val_1_U->clk(ap_clk);
    Buffer_val_1_U->reset(ap_rst);
    Buffer_val_1_U->address0(Buffer_val_1_address0);
    Buffer_val_1_U->ce0(Buffer_val_1_ce0);
    Buffer_val_1_U->q0(Buffer_val_1_q0);
    Buffer_val_1_U->address1(Buffer_val_1_address1);
    Buffer_val_1_U->ce1(Buffer_val_1_ce1);
    Buffer_val_1_U->we1(Buffer_val_1_we1);
    Buffer_val_1_U->d1(Buffer_val_1_d1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Buffer_val_0_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_20_fu_216_p1 );

    SC_METHOD(thread_Buffer_val_0_address1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( Buffer_val_0_addr_reg_526 );

    SC_METHOD(thread_Buffer_val_0_ce0);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_Buffer_val_0_ce1);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_Buffer_val_0_d1);
    sensitive << ( supressed_data_stream_V_dout );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_Buffer_val_0_we1);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_Buffer_val_1_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_20_fu_216_p1 );

    SC_METHOD(thread_Buffer_val_1_address1);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_Buffer_val_1_addr_reg_520_pp0_it1 );

    SC_METHOD(thread_Buffer_val_1_ce0);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_Buffer_val_1_ce1);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_Buffer_val_1_d1);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( temp1_reg_552 );

    SC_METHOD(thread_Buffer_val_1_we1);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond2_fu_164_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond2_fu_164_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_bdd_172);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_46);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_66);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_84);
    sensitive << ( hysterisis_Image_data_stream_V_full_n );
    sensitive << ( ap_reg_ppstg_or_cond6_reg_583_pp0_it3 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_2);
    sensitive << ( ap_sig_bdd_66 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_22 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_46 );

    SC_METHOD(thread_exitcond2_fu_164_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( p_s_reg_142 );

    SC_METHOD(thread_exitcond_fu_204_p2);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( p_2_reg_153 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_hysterisis_Image_data_stream_V_din);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_or_cond6_reg_583_pp0_it3 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( tmp_31_reg_607 );

    SC_METHOD(thread_hysterisis_Image_data_stream_V_write);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_or_cond6_reg_583_pp0_it3 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_i_V_fu_170_p2);
    sensitive << ( p_s_reg_142 );

    SC_METHOD(thread_icmp2_fu_232_p2);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( exitcond_fu_204_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( tmp_37_fu_222_p4 );

    SC_METHOD(thread_icmp_fu_186_p2);
    sensitive << ( exitcond2_fu_164_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_fu_176_p4 );

    SC_METHOD(thread_j_V_fu_210_p2);
    sensitive << ( p_2_reg_153 );

    SC_METHOD(thread_not_or_cond8_fu_429_p2);
    sensitive << ( or_cond8_reg_587 );

    SC_METHOD(thread_notlhs_fu_192_p2);
    sensitive << ( exitcond2_fu_164_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( p_s_reg_142 );

    SC_METHOD(thread_notrhs_fu_238_p2);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( p_2_reg_153 );
    sensitive << ( exitcond_fu_204_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_or_cond6_fu_349_p2);
    sensitive << ( tmp9_reg_537 );
    sensitive << ( tmp10_reg_542 );

    SC_METHOD(thread_or_cond8_fu_392_p2);
    sensitive << ( icmp_reg_496 );
    sensitive << ( tmp1_reg_558 );

    SC_METHOD(thread_or_cond_fu_424_p2);
    sensitive << ( tmp2_reg_592 );
    sensitive << ( tmp5_fu_420_p2 );

    SC_METHOD(thread_supressed_data_stream_V_read);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_tmp10_fu_255_p2);
    sensitive << ( tmp_s_reg_506 );
    sensitive << ( tmp_32_fu_244_p2 );

    SC_METHOD(thread_tmp1_fu_284_p2);
    sensitive << ( icmp2_reg_532 );
    sensitive << ( tmp_21_fu_278_p2 );

    SC_METHOD(thread_tmp2_fu_406_p2);
    sensitive << ( tmp3_reg_568 );
    sensitive << ( tmp4_reg_573 );

    SC_METHOD(thread_tmp3_fu_331_p2);
    sensitive << ( tmp_22_fu_289_p2 );
    sensitive << ( tmp_23_fu_295_p2 );

    SC_METHOD(thread_tmp4_fu_337_p2);
    sensitive << ( tmp_24_fu_301_p2 );
    sensitive << ( tmp_25_fu_307_p2 );

    SC_METHOD(thread_tmp5_fu_420_p2);
    sensitive << ( tmp6_reg_597 );
    sensitive << ( tmp7_reg_602 );

    SC_METHOD(thread_tmp6_fu_410_p2);
    sensitive << ( tmp_27_reg_563 );
    sensitive << ( tmp_26_fu_396_p2 );

    SC_METHOD(thread_tmp7_fu_415_p2);
    sensitive << ( tmp8_reg_578 );
    sensitive << ( tmp_28_fu_401_p2 );

    SC_METHOD(thread_tmp8_fu_343_p2);
    sensitive << ( tmp_29_fu_319_p2 );
    sensitive << ( tmp_30_fu_325_p2 );

    SC_METHOD(thread_tmp9_fu_250_p2);
    sensitive << ( notlhs_reg_501 );
    sensitive << ( notrhs_fu_238_p2 );

    SC_METHOD(thread_tmp_20_fu_216_p1);
    sensitive << ( p_2_reg_153 );

    SC_METHOD(thread_tmp_21_fu_278_p2);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( Win_val_1_1_fu_76 );

    SC_METHOD(thread_tmp_22_fu_289_p2);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( Win_val_1_1_fu_76 );

    SC_METHOD(thread_tmp_23_fu_295_p2);
    sensitive << ( supressed_data_stream_V_dout );
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_tmp_24_fu_301_p2);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( Win_val_0_1_fu_68 );

    SC_METHOD(thread_tmp_25_fu_307_p2);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( Win_val_0_1_2_fu_72 );

    SC_METHOD(thread_tmp_26_fu_396_p2);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( temp1_reg_552 );

    SC_METHOD(thread_tmp_27_fu_313_p2);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( Win_val_1_1_2_fu_80 );

    SC_METHOD(thread_tmp_28_fu_401_p2);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( temp2_reg_547 );

    SC_METHOD(thread_tmp_29_fu_319_p2);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( Win_val_2_1_fu_84 );

    SC_METHOD(thread_tmp_30_fu_325_p2);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( Win_val_2_1_2_fu_88 );

    SC_METHOD(thread_tmp_31_fu_434_p2);
    sensitive << ( or_cond_fu_424_p2 );
    sensitive << ( not_or_cond8_fu_429_p2 );

    SC_METHOD(thread_tmp_32_fu_244_p2);
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( p_2_reg_153 );
    sensitive << ( exitcond_fu_204_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_tmp_37_fu_222_p4);
    sensitive << ( p_2_reg_153 );

    SC_METHOD(thread_tmp_fu_176_p4);
    sensitive << ( p_s_reg_142 );

    SC_METHOD(thread_tmp_s_fu_198_p2);
    sensitive << ( exitcond2_fu_164_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( p_s_reg_142 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( supressed_data_stream_V_empty_n );
    sensitive << ( exitcond2_fu_164_p2 );
    sensitive << ( exitcond_fu_204_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_sig_bdd_84 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_sig_bdd_172 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "canny_hysterisis_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, supressed_data_stream_V_dout, "(port)supressed_data_stream_V_dout");
    sc_trace(mVcdFile, supressed_data_stream_V_empty_n, "(port)supressed_data_stream_V_empty_n");
    sc_trace(mVcdFile, supressed_data_stream_V_read, "(port)supressed_data_stream_V_read");
    sc_trace(mVcdFile, hysterisis_Image_data_stream_V_din, "(port)hysterisis_Image_data_stream_V_din");
    sc_trace(mVcdFile, hysterisis_Image_data_stream_V_full_n, "(port)hysterisis_Image_data_stream_V_full_n");
    sc_trace(mVcdFile, hysterisis_Image_data_stream_V_write, "(port)hysterisis_Image_data_stream_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_22, "ap_sig_bdd_22");
    sc_trace(mVcdFile, p_2_reg_153, "p_2_reg_153");
    sc_trace(mVcdFile, exitcond2_fu_164_p2, "exitcond2_fu_164_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_46, "ap_sig_bdd_46");
    sc_trace(mVcdFile, i_V_fu_170_p2, "i_V_fu_170_p2");
    sc_trace(mVcdFile, i_V_reg_491, "i_V_reg_491");
    sc_trace(mVcdFile, icmp_fu_186_p2, "icmp_fu_186_p2");
    sc_trace(mVcdFile, icmp_reg_496, "icmp_reg_496");
    sc_trace(mVcdFile, notlhs_fu_192_p2, "notlhs_fu_192_p2");
    sc_trace(mVcdFile, notlhs_reg_501, "notlhs_reg_501");
    sc_trace(mVcdFile, tmp_s_fu_198_p2, "tmp_s_fu_198_p2");
    sc_trace(mVcdFile, tmp_s_reg_506, "tmp_s_reg_506");
    sc_trace(mVcdFile, exitcond_fu_204_p2, "exitcond_fu_204_p2");
    sc_trace(mVcdFile, exitcond_reg_511, "exitcond_reg_511");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_2, "ap_sig_cseq_ST_pp0_stg0_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_66, "ap_sig_bdd_66");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, or_cond6_reg_583, "or_cond6_reg_583");
    sc_trace(mVcdFile, ap_reg_ppstg_or_cond6_reg_583_pp0_it3, "ap_reg_ppstg_or_cond6_reg_583_pp0_it3");
    sc_trace(mVcdFile, ap_sig_bdd_84, "ap_sig_bdd_84");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, j_V_fu_210_p2, "j_V_fu_210_p2");
    sc_trace(mVcdFile, Buffer_val_1_addr_reg_520, "Buffer_val_1_addr_reg_520");
    sc_trace(mVcdFile, ap_reg_ppstg_Buffer_val_1_addr_reg_520_pp0_it1, "ap_reg_ppstg_Buffer_val_1_addr_reg_520_pp0_it1");
    sc_trace(mVcdFile, Buffer_val_0_addr_reg_526, "Buffer_val_0_addr_reg_526");
    sc_trace(mVcdFile, icmp2_fu_232_p2, "icmp2_fu_232_p2");
    sc_trace(mVcdFile, icmp2_reg_532, "icmp2_reg_532");
    sc_trace(mVcdFile, tmp9_fu_250_p2, "tmp9_fu_250_p2");
    sc_trace(mVcdFile, tmp9_reg_537, "tmp9_reg_537");
    sc_trace(mVcdFile, tmp10_fu_255_p2, "tmp10_fu_255_p2");
    sc_trace(mVcdFile, tmp10_reg_542, "tmp10_reg_542");
    sc_trace(mVcdFile, Buffer_val_1_q0, "Buffer_val_1_q0");
    sc_trace(mVcdFile, temp2_reg_547, "temp2_reg_547");
    sc_trace(mVcdFile, Buffer_val_0_q0, "Buffer_val_0_q0");
    sc_trace(mVcdFile, temp1_reg_552, "temp1_reg_552");
    sc_trace(mVcdFile, tmp1_fu_284_p2, "tmp1_fu_284_p2");
    sc_trace(mVcdFile, tmp1_reg_558, "tmp1_reg_558");
    sc_trace(mVcdFile, tmp_27_fu_313_p2, "tmp_27_fu_313_p2");
    sc_trace(mVcdFile, tmp_27_reg_563, "tmp_27_reg_563");
    sc_trace(mVcdFile, tmp3_fu_331_p2, "tmp3_fu_331_p2");
    sc_trace(mVcdFile, tmp3_reg_568, "tmp3_reg_568");
    sc_trace(mVcdFile, tmp4_fu_337_p2, "tmp4_fu_337_p2");
    sc_trace(mVcdFile, tmp4_reg_573, "tmp4_reg_573");
    sc_trace(mVcdFile, tmp8_fu_343_p2, "tmp8_fu_343_p2");
    sc_trace(mVcdFile, tmp8_reg_578, "tmp8_reg_578");
    sc_trace(mVcdFile, or_cond6_fu_349_p2, "or_cond6_fu_349_p2");
    sc_trace(mVcdFile, ap_reg_ppstg_or_cond6_reg_583_pp0_it2, "ap_reg_ppstg_or_cond6_reg_583_pp0_it2");
    sc_trace(mVcdFile, or_cond8_fu_392_p2, "or_cond8_fu_392_p2");
    sc_trace(mVcdFile, or_cond8_reg_587, "or_cond8_reg_587");
    sc_trace(mVcdFile, tmp2_fu_406_p2, "tmp2_fu_406_p2");
    sc_trace(mVcdFile, tmp2_reg_592, "tmp2_reg_592");
    sc_trace(mVcdFile, tmp6_fu_410_p2, "tmp6_fu_410_p2");
    sc_trace(mVcdFile, tmp6_reg_597, "tmp6_reg_597");
    sc_trace(mVcdFile, tmp7_fu_415_p2, "tmp7_fu_415_p2");
    sc_trace(mVcdFile, tmp7_reg_602, "tmp7_reg_602");
    sc_trace(mVcdFile, tmp_31_fu_434_p2, "tmp_31_fu_434_p2");
    sc_trace(mVcdFile, tmp_31_reg_607, "tmp_31_reg_607");
    sc_trace(mVcdFile, Buffer_val_0_address0, "Buffer_val_0_address0");
    sc_trace(mVcdFile, Buffer_val_0_ce0, "Buffer_val_0_ce0");
    sc_trace(mVcdFile, Buffer_val_0_address1, "Buffer_val_0_address1");
    sc_trace(mVcdFile, Buffer_val_0_ce1, "Buffer_val_0_ce1");
    sc_trace(mVcdFile, Buffer_val_0_we1, "Buffer_val_0_we1");
    sc_trace(mVcdFile, Buffer_val_0_d1, "Buffer_val_0_d1");
    sc_trace(mVcdFile, Buffer_val_1_address0, "Buffer_val_1_address0");
    sc_trace(mVcdFile, Buffer_val_1_ce0, "Buffer_val_1_ce0");
    sc_trace(mVcdFile, Buffer_val_1_address1, "Buffer_val_1_address1");
    sc_trace(mVcdFile, Buffer_val_1_ce1, "Buffer_val_1_ce1");
    sc_trace(mVcdFile, Buffer_val_1_we1, "Buffer_val_1_we1");
    sc_trace(mVcdFile, Buffer_val_1_d1, "Buffer_val_1_d1");
    sc_trace(mVcdFile, p_s_reg_142, "p_s_reg_142");
    sc_trace(mVcdFile, ap_sig_bdd_172, "ap_sig_bdd_172");
    sc_trace(mVcdFile, tmp_20_fu_216_p1, "tmp_20_fu_216_p1");
    sc_trace(mVcdFile, Win_val_0_1_fu_68, "Win_val_0_1_fu_68");
    sc_trace(mVcdFile, Win_val_0_1_2_fu_72, "Win_val_0_1_2_fu_72");
    sc_trace(mVcdFile, Win_val_1_1_fu_76, "Win_val_1_1_fu_76");
    sc_trace(mVcdFile, Win_val_1_1_2_fu_80, "Win_val_1_1_2_fu_80");
    sc_trace(mVcdFile, Win_val_2_1_fu_84, "Win_val_2_1_fu_84");
    sc_trace(mVcdFile, Win_val_2_1_2_fu_88, "Win_val_2_1_2_fu_88");
    sc_trace(mVcdFile, tmp_fu_176_p4, "tmp_fu_176_p4");
    sc_trace(mVcdFile, tmp_37_fu_222_p4, "tmp_37_fu_222_p4");
    sc_trace(mVcdFile, notrhs_fu_238_p2, "notrhs_fu_238_p2");
    sc_trace(mVcdFile, tmp_32_fu_244_p2, "tmp_32_fu_244_p2");
    sc_trace(mVcdFile, tmp_21_fu_278_p2, "tmp_21_fu_278_p2");
    sc_trace(mVcdFile, tmp_22_fu_289_p2, "tmp_22_fu_289_p2");
    sc_trace(mVcdFile, tmp_23_fu_295_p2, "tmp_23_fu_295_p2");
    sc_trace(mVcdFile, tmp_24_fu_301_p2, "tmp_24_fu_301_p2");
    sc_trace(mVcdFile, tmp_25_fu_307_p2, "tmp_25_fu_307_p2");
    sc_trace(mVcdFile, tmp_29_fu_319_p2, "tmp_29_fu_319_p2");
    sc_trace(mVcdFile, tmp_30_fu_325_p2, "tmp_30_fu_325_p2");
    sc_trace(mVcdFile, tmp_26_fu_396_p2, "tmp_26_fu_396_p2");
    sc_trace(mVcdFile, tmp_28_fu_401_p2, "tmp_28_fu_401_p2");
    sc_trace(mVcdFile, tmp5_fu_420_p2, "tmp5_fu_420_p2");
    sc_trace(mVcdFile, or_cond_fu_424_p2, "or_cond_fu_424_p2");
    sc_trace(mVcdFile, not_or_cond8_fu_429_p2, "not_or_cond8_fu_429_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

canny_hysterisis::~canny_hysterisis() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete Buffer_val_0_U;
    delete Buffer_val_1_U;
}

void canny_hysterisis::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(exitcond2_fu_164_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_204_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(exitcond2_fu_164_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_204_p2.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                     esl_seteq<1,1,1>(exitcond2_fu_164_p2.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_204_p2.read())))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (!((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read())))) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if (!((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read())))) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if (!((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read())))) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(exitcond2_fu_164_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_204_p2.read()))) {
        p_2_reg_153 = j_V_fu_210_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_164_p2.read(), ap_const_lv1_0))) {
        p_2_reg_153 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_204_p2.read()))) {
        p_s_reg_142 = i_V_reg_491.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_bdd_172.read())) {
        p_s_reg_142 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_204_p2.read()))) {
        Buffer_val_0_addr_reg_526 =  (sc_lv<10>) (tmp_20_fu_216_p1.read());
        Buffer_val_1_addr_reg_520 =  (sc_lv<10>) (tmp_20_fu_216_p1.read());
        icmp2_reg_532 = icmp2_fu_232_p2.read();
        tmp10_reg_542 = tmp10_fu_255_p2.read();
        tmp9_reg_537 = tmp9_fu_250_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_511.read()))) {
        Win_val_0_1_2_fu_72 = Win_val_0_1_fu_68.read();
        Win_val_0_1_fu_68 = supressed_data_stream_V_dout.read();
        Win_val_1_1_2_fu_80 = Win_val_1_1_fu_76.read();
        Win_val_1_1_fu_76 = Buffer_val_0_q0.read();
        Win_val_2_1_2_fu_88 = Win_val_2_1_fu_84.read();
        Win_val_2_1_fu_84 = Buffer_val_1_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        ap_reg_ppstg_Buffer_val_1_addr_reg_520_pp0_it1 = Buffer_val_1_addr_reg_520.read();
        exitcond_reg_511 = exitcond_fu_204_p2.read();
        or_cond6_reg_583 = or_cond6_fu_349_p2.read();
        tmp1_reg_558 = tmp1_fu_284_p2.read();
        tmp3_reg_568 = tmp3_fu_331_p2.read();
        tmp4_reg_573 = tmp4_fu_337_p2.read();
        tmp8_reg_578 = tmp8_fu_343_p2.read();
        tmp_27_reg_563 = tmp_27_fu_313_p2.read();
    }
    if (!((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read())))) {
        ap_reg_ppstg_or_cond6_reg_583_pp0_it2 = or_cond6_reg_583.read();
        ap_reg_ppstg_or_cond6_reg_583_pp0_it3 = ap_reg_ppstg_or_cond6_reg_583_pp0_it2.read();
        or_cond8_reg_587 = or_cond8_fu_392_p2.read();
        tmp2_reg_592 = tmp2_fu_406_p2.read();
        tmp6_reg_597 = tmp6_fu_410_p2.read();
        tmp7_reg_602 = tmp7_fu_415_p2.read();
        tmp_31_reg_607 = tmp_31_fu_434_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_V_reg_491 = i_V_fu_170_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond2_fu_164_p2.read(), ap_const_lv1_0))) {
        icmp_reg_496 = icmp_fu_186_p2.read();
        notlhs_reg_501 = notlhs_fu_192_p2.read();
        tmp_s_reg_506 = tmp_s_fu_198_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        temp1_reg_552 = Buffer_val_0_q0.read();
        temp2_reg_547 = Buffer_val_1_q0.read();
    }
}

void canny_hysterisis::thread_Buffer_val_0_address0() {
    Buffer_val_0_address0 =  (sc_lv<10>) (tmp_20_fu_216_p1.read());
}

void canny_hysterisis::thread_Buffer_val_0_address1() {
    Buffer_val_0_address1 = Buffer_val_0_addr_reg_526.read();
}

void canny_hysterisis::thread_Buffer_val_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        Buffer_val_0_ce0 = ap_const_logic_1;
    } else {
        Buffer_val_0_ce0 = ap_const_logic_0;
    }
}

void canny_hysterisis::thread_Buffer_val_0_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        Buffer_val_0_ce1 = ap_const_logic_1;
    } else {
        Buffer_val_0_ce1 = ap_const_logic_0;
    }
}

void canny_hysterisis::thread_Buffer_val_0_d1() {
    Buffer_val_0_d1 = supressed_data_stream_V_dout.read();
}

void canny_hysterisis::thread_Buffer_val_0_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read())))))) {
        Buffer_val_0_we1 = ap_const_logic_1;
    } else {
        Buffer_val_0_we1 = ap_const_logic_0;
    }
}

void canny_hysterisis::thread_Buffer_val_1_address0() {
    Buffer_val_1_address0 =  (sc_lv<10>) (tmp_20_fu_216_p1.read());
}

void canny_hysterisis::thread_Buffer_val_1_address1() {
    Buffer_val_1_address1 = ap_reg_ppstg_Buffer_val_1_addr_reg_520_pp0_it1.read();
}

void canny_hysterisis::thread_Buffer_val_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        Buffer_val_1_ce0 = ap_const_logic_1;
    } else {
        Buffer_val_1_ce0 = ap_const_logic_0;
    }
}

void canny_hysterisis::thread_Buffer_val_1_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
         !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        Buffer_val_1_ce1 = ap_const_logic_1;
    } else {
        Buffer_val_1_ce1 = ap_const_logic_0;
    }
}

void canny_hysterisis::thread_Buffer_val_1_d1() {
    Buffer_val_1_d1 = temp1_reg_552.read();
}

void canny_hysterisis::thread_Buffer_val_1_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
          !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read())))))) {
        Buffer_val_1_we1 = ap_const_logic_1;
    } else {
        Buffer_val_1_we1 = ap_const_logic_0;
    }
}

void canny_hysterisis::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond2_fu_164_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void canny_hysterisis::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void canny_hysterisis::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond2_fu_164_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void canny_hysterisis::thread_ap_sig_bdd_172() {
    ap_sig_bdd_172 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void canny_hysterisis::thread_ap_sig_bdd_22() {
    ap_sig_bdd_22 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void canny_hysterisis::thread_ap_sig_bdd_46() {
    ap_sig_bdd_46 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void canny_hysterisis::thread_ap_sig_bdd_66() {
    ap_sig_bdd_66 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void canny_hysterisis::thread_ap_sig_bdd_84() {
    ap_sig_bdd_84 = (esl_seteq<1,1,1>(hysterisis_Image_data_stream_V_full_n.read(), ap_const_logic_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond6_reg_583_pp0_it3.read()));
}

void canny_hysterisis::thread_ap_sig_cseq_ST_pp0_stg0_fsm_2() {
    if (ap_sig_bdd_66.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    }
}

void canny_hysterisis::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_22.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void canny_hysterisis::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_46.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void canny_hysterisis::thread_exitcond2_fu_164_p2() {
    exitcond2_fu_164_p2 = (!p_s_reg_142.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(p_s_reg_142.read() == ap_const_lv11_400);
}

void canny_hysterisis::thread_exitcond_fu_204_p2() {
    exitcond_fu_204_p2 = (!p_2_reg_153.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(p_2_reg_153.read() == ap_const_lv11_400);
}

void canny_hysterisis::thread_hysterisis_Image_data_stream_V_din() {
    hysterisis_Image_data_stream_V_din = (!tmp_31_reg_607.read()[0].is_01())? sc_lv<8>(): ((tmp_31_reg_607.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void canny_hysterisis::thread_hysterisis_Image_data_stream_V_write() {
    if ((!esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond6_reg_583_pp0_it3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
         !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        hysterisis_Image_data_stream_V_write = ap_const_logic_1;
    } else {
        hysterisis_Image_data_stream_V_write = ap_const_logic_0;
    }
}

void canny_hysterisis::thread_i_V_fu_170_p2() {
    i_V_fu_170_p2 = (!p_s_reg_142.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(p_s_reg_142.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void canny_hysterisis::thread_icmp2_fu_232_p2() {
    icmp2_fu_232_p2 = (!tmp_37_fu_222_p4.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_37_fu_222_p4.read() == ap_const_lv10_0);
}

void canny_hysterisis::thread_icmp_fu_186_p2() {
    icmp_fu_186_p2 = (!tmp_fu_176_p4.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_176_p4.read() == ap_const_lv10_0);
}

void canny_hysterisis::thread_j_V_fu_210_p2() {
    j_V_fu_210_p2 = (!p_2_reg_153.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(p_2_reg_153.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void canny_hysterisis::thread_not_or_cond8_fu_429_p2() {
    not_or_cond8_fu_429_p2 = (or_cond8_reg_587.read() ^ ap_const_lv1_1);
}

void canny_hysterisis::thread_notlhs_fu_192_p2() {
    notlhs_fu_192_p2 = (!p_s_reg_142.read().is_01() || !ap_const_lv11_0.is_01())? sc_lv<1>(): sc_lv<1>(p_s_reg_142.read() != ap_const_lv11_0);
}

void canny_hysterisis::thread_notrhs_fu_238_p2() {
    notrhs_fu_238_p2 = (!p_2_reg_153.read().is_01() || !ap_const_lv11_0.is_01())? sc_lv<1>(): sc_lv<1>(p_2_reg_153.read() != ap_const_lv11_0);
}

void canny_hysterisis::thread_or_cond6_fu_349_p2() {
    or_cond6_fu_349_p2 = (tmp10_reg_542.read() & tmp9_reg_537.read());
}

void canny_hysterisis::thread_or_cond8_fu_392_p2() {
    or_cond8_fu_392_p2 = (tmp1_reg_558.read() | icmp_reg_496.read());
}

void canny_hysterisis::thread_or_cond_fu_424_p2() {
    or_cond_fu_424_p2 = (tmp5_fu_420_p2.read() | tmp2_reg_592.read());
}

void canny_hysterisis::thread_supressed_data_stream_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))))) {
        supressed_data_stream_V_read = ap_const_logic_1;
    } else {
        supressed_data_stream_V_read = ap_const_logic_0;
    }
}

void canny_hysterisis::thread_tmp10_fu_255_p2() {
    tmp10_fu_255_p2 = (tmp_s_reg_506.read() & tmp_32_fu_244_p2.read());
}

void canny_hysterisis::thread_tmp1_fu_284_p2() {
    tmp1_fu_284_p2 = (icmp2_reg_532.read() | tmp_21_fu_278_p2.read());
}

void canny_hysterisis::thread_tmp2_fu_406_p2() {
    tmp2_fu_406_p2 = (tmp4_reg_573.read() | tmp3_reg_568.read());
}

void canny_hysterisis::thread_tmp3_fu_331_p2() {
    tmp3_fu_331_p2 = (tmp_22_fu_289_p2.read() | tmp_23_fu_295_p2.read());
}

void canny_hysterisis::thread_tmp4_fu_337_p2() {
    tmp4_fu_337_p2 = (tmp_24_fu_301_p2.read() | tmp_25_fu_307_p2.read());
}

void canny_hysterisis::thread_tmp5_fu_420_p2() {
    tmp5_fu_420_p2 = (tmp7_reg_602.read() | tmp6_reg_597.read());
}

void canny_hysterisis::thread_tmp6_fu_410_p2() {
    tmp6_fu_410_p2 = (tmp_26_fu_396_p2.read() | tmp_27_reg_563.read());
}

void canny_hysterisis::thread_tmp7_fu_415_p2() {
    tmp7_fu_415_p2 = (tmp8_reg_578.read() | tmp_28_fu_401_p2.read());
}

void canny_hysterisis::thread_tmp8_fu_343_p2() {
    tmp8_fu_343_p2 = (tmp_29_fu_319_p2.read() | tmp_30_fu_325_p2.read());
}

void canny_hysterisis::thread_tmp9_fu_250_p2() {
    tmp9_fu_250_p2 = (notrhs_fu_238_p2.read() & notlhs_reg_501.read());
}

void canny_hysterisis::thread_tmp_20_fu_216_p1() {
    tmp_20_fu_216_p1 = esl_zext<64,11>(p_2_reg_153.read());
}

void canny_hysterisis::thread_tmp_21_fu_278_p2() {
    tmp_21_fu_278_p2 = (!Win_val_1_1_fu_76.read().is_01() || !ap_const_lv8_A0.is_01())? sc_lv<1>(): (sc_biguint<8>(Win_val_1_1_fu_76.read()) < sc_biguint<8>(ap_const_lv8_A0));
}

void canny_hysterisis::thread_tmp_22_fu_289_p2() {
    tmp_22_fu_289_p2 = (!Win_val_1_1_fu_76.read().is_01() || !ap_const_lv8_DC.is_01())? sc_lv<1>(): (sc_biguint<8>(Win_val_1_1_fu_76.read()) > sc_biguint<8>(ap_const_lv8_DC));
}

void canny_hysterisis::thread_tmp_23_fu_295_p2() {
    tmp_23_fu_295_p2 = (!supressed_data_stream_V_dout.read().is_01() || !ap_const_lv8_DC.is_01())? sc_lv<1>(): (sc_biguint<8>(supressed_data_stream_V_dout.read()) > sc_biguint<8>(ap_const_lv8_DC));
}

void canny_hysterisis::thread_tmp_24_fu_301_p2() {
    tmp_24_fu_301_p2 = (!Win_val_0_1_fu_68.read().is_01() || !ap_const_lv8_DC.is_01())? sc_lv<1>(): (sc_biguint<8>(Win_val_0_1_fu_68.read()) > sc_biguint<8>(ap_const_lv8_DC));
}

void canny_hysterisis::thread_tmp_25_fu_307_p2() {
    tmp_25_fu_307_p2 = (!Win_val_0_1_2_fu_72.read().is_01() || !ap_const_lv8_DC.is_01())? sc_lv<1>(): (sc_biguint<8>(Win_val_0_1_2_fu_72.read()) > sc_biguint<8>(ap_const_lv8_DC));
}

void canny_hysterisis::thread_tmp_26_fu_396_p2() {
    tmp_26_fu_396_p2 = (!temp1_reg_552.read().is_01() || !ap_const_lv8_DC.is_01())? sc_lv<1>(): (sc_biguint<8>(temp1_reg_552.read()) > sc_biguint<8>(ap_const_lv8_DC));
}

void canny_hysterisis::thread_tmp_27_fu_313_p2() {
    tmp_27_fu_313_p2 = (!Win_val_1_1_2_fu_80.read().is_01() || !ap_const_lv8_DC.is_01())? sc_lv<1>(): (sc_biguint<8>(Win_val_1_1_2_fu_80.read()) > sc_biguint<8>(ap_const_lv8_DC));
}

void canny_hysterisis::thread_tmp_28_fu_401_p2() {
    tmp_28_fu_401_p2 = (!temp2_reg_547.read().is_01() || !ap_const_lv8_DC.is_01())? sc_lv<1>(): (sc_biguint<8>(temp2_reg_547.read()) > sc_biguint<8>(ap_const_lv8_DC));
}

void canny_hysterisis::thread_tmp_29_fu_319_p2() {
    tmp_29_fu_319_p2 = (!Win_val_2_1_fu_84.read().is_01() || !ap_const_lv8_DC.is_01())? sc_lv<1>(): (sc_biguint<8>(Win_val_2_1_fu_84.read()) > sc_biguint<8>(ap_const_lv8_DC));
}

void canny_hysterisis::thread_tmp_30_fu_325_p2() {
    tmp_30_fu_325_p2 = (!Win_val_2_1_2_fu_88.read().is_01() || !ap_const_lv8_DC.is_01())? sc_lv<1>(): (sc_biguint<8>(Win_val_2_1_2_fu_88.read()) > sc_biguint<8>(ap_const_lv8_DC));
}

void canny_hysterisis::thread_tmp_31_fu_434_p2() {
    tmp_31_fu_434_p2 = (or_cond_fu_424_p2.read() & not_or_cond8_fu_429_p2.read());
}

void canny_hysterisis::thread_tmp_32_fu_244_p2() {
    tmp_32_fu_244_p2 = (!p_2_reg_153.read().is_01() || !ap_const_lv11_3FF.is_01())? sc_lv<1>(): (sc_biguint<11>(p_2_reg_153.read()) < sc_biguint<11>(ap_const_lv11_3FF));
}

void canny_hysterisis::thread_tmp_37_fu_222_p4() {
    tmp_37_fu_222_p4 = p_2_reg_153.read().range(10, 1);
}

void canny_hysterisis::thread_tmp_fu_176_p4() {
    tmp_fu_176_p4 = p_s_reg_142.read().range(10, 1);
}

void canny_hysterisis::thread_tmp_s_fu_198_p2() {
    tmp_s_fu_198_p2 = (!p_s_reg_142.read().is_01() || !ap_const_lv11_3FF.is_01())? sc_lv<1>(): (sc_biguint<11>(p_s_reg_142.read()) < sc_biguint<11>(ap_const_lv11_3FF));
}

void canny_hysterisis::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_172.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond2_fu_164_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_204_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  !((esl_seteq<1,1,1>(supressed_data_stream_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_84.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_204_p2.read()) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

