// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _canny_grad_computation_HH_
#define _canny_grad_computation_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct canny_grad_computation : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > grad_x_data_stream_V_dout;
    sc_in< sc_logic > grad_x_data_stream_V_empty_n;
    sc_out< sc_logic > grad_x_data_stream_V_read;
    sc_in< sc_lv<8> > grad_y_data_stream_V_dout;
    sc_in< sc_logic > grad_y_data_stream_V_empty_n;
    sc_out< sc_logic > grad_y_data_stream_V_read;
    sc_out< sc_lv<16> > grad_out_data_stream_V_din;
    sc_in< sc_logic > grad_out_data_stream_V_full_n;
    sc_out< sc_logic > grad_out_data_stream_V_write;


    // Module declarations
    canny_grad_computation(sc_module_name name);
    SC_HAS_PROCESS(canny_grad_computation);

    ~canny_grad_computation();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_22;
    sc_signal< sc_lv<11> > p_8_reg_94;
    sc_signal< sc_lv<1> > exitcond4_fu_105_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_50;
    sc_signal< sc_lv<11> > i_V_fu_111_p2;
    sc_signal< sc_lv<11> > i_V_reg_373;
    sc_signal< sc_lv<1> > exitcond_fu_117_p2;
    sc_signal< sc_lv<1> > exitcond_reg_378;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_2;
    sc_signal< bool > ap_sig_bdd_61;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< bool > ap_sig_bdd_72;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it3;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_reg_378_pp0_it3;
    sc_signal< bool > ap_sig_bdd_84;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it4;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_reg_378_pp0_it1;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_reg_378_pp0_it2;
    sc_signal< sc_lv<11> > j_V_fu_123_p2;
    sc_signal< sc_lv<1> > abscond_i_fu_135_p2;
    sc_signal< sc_lv<1> > abscond_i_reg_387;
    sc_signal< sc_lv<1> > ap_reg_ppstg_abscond_i_reg_387_pp0_it2;
    sc_signal< sc_lv<8> > abs_gx_fu_141_p3;
    sc_signal< sc_lv<8> > abs_gx_reg_392;
    sc_signal< sc_lv<8> > abs_gy_fu_161_p3;
    sc_signal< sc_lv<8> > abs_gy_reg_401;
    sc_signal< sc_lv<9> > element_grad_fu_177_p2;
    sc_signal< sc_lv<9> > element_grad_reg_410;
    sc_signal< sc_lv<9> > ap_reg_ppstg_element_grad_reg_410_pp0_it2;
    sc_signal< sc_lv<9> > ap_reg_ppstg_element_grad_reg_410_pp0_it3;
    sc_signal< sc_lv<1> > tmp_36_fu_183_p2;
    sc_signal< sc_lv<1> > tmp_36_reg_415;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_36_reg_415_pp0_it2;
    sc_signal< sc_lv<1> > tmp_38_fu_189_p2;
    sc_signal< sc_lv<1> > tmp_38_reg_421;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_38_reg_421_pp0_it2;
    sc_signal< sc_lv<1> > ult_fu_195_p2;
    sc_signal< sc_lv<1> > ult_reg_427;
    sc_signal< sc_lv<1> > tmp8_fu_203_p2;
    sc_signal< sc_lv<1> > tmp8_reg_432;
    sc_signal< sc_lv<1> > ult1_fu_221_p2;
    sc_signal< sc_lv<1> > ult1_reg_437;
    sc_signal< sc_lv<1> > rev1_fu_231_p2;
    sc_signal< sc_lv<1> > rev1_reg_442;
    sc_signal< sc_lv<1> > tmp_41_fu_244_p2;
    sc_signal< sc_lv<1> > tmp_41_reg_447;
    sc_signal< sc_lv<1> > ult3_fu_250_p2;
    sc_signal< sc_lv<1> > ult3_reg_453;
    sc_signal< sc_lv<1> > or_cond7_fu_261_p2;
    sc_signal< sc_lv<1> > or_cond7_reg_458;
    sc_signal< sc_lv<2> > dir_g_1_fu_288_p3;
    sc_signal< sc_lv<2> > dir_g_1_reg_463;
    sc_signal< sc_lv<1> > rev2_fu_295_p2;
    sc_signal< sc_lv<1> > rev2_reg_468;
    sc_signal< sc_lv<2> > sel_tmp1_fu_307_p3;
    sc_signal< sc_lv<2> > sel_tmp1_reg_473;
    sc_signal< sc_lv<1> > sel_tmp3_fu_321_p2;
    sc_signal< sc_lv<1> > sel_tmp3_reg_478;
    sc_signal< sc_lv<1> > tmp10_fu_327_p2;
    sc_signal< sc_lv<1> > tmp10_reg_483;
    sc_signal< sc_lv<11> > p_s_reg_83;
    sc_signal< bool > ap_sig_bdd_161;
    sc_signal< sc_lv<8> > neg_i_fu_129_p2;
    sc_signal< sc_lv<1> > abscond_i1_fu_155_p2;
    sc_signal< sc_lv<8> > neg_i1_fu_149_p2;
    sc_signal< sc_lv<9> > tmp_132_cast_fu_173_p1;
    sc_signal< sc_lv<9> > tmp_131_cast_fu_169_p1;
    sc_signal< sc_lv<1> > tmp_37_fu_199_p2;
    sc_signal< sc_lv<9> > tmp_39_fu_214_p3;
    sc_signal< sc_lv<9> > tmp_136_cast_fu_208_p1;
    sc_signal< sc_lv<1> > ult2_fu_227_p2;
    sc_signal< sc_lv<9> > tmp_137_cast_fu_211_p1;
    sc_signal< sc_lv<9> > tmp_40_fu_237_p3;
    sc_signal< sc_lv<1> > rev9_fu_256_p2;
    sc_signal< sc_lv<1> > rev_fu_270_p2;
    sc_signal< sc_lv<1> > tmp9_fu_279_p2;
    sc_signal< sc_lv<2> > dir_g_2_fu_300_p3;
    sc_signal< sc_lv<2> > dir_g_cast_fu_275_p1;
    sc_signal< sc_lv<1> > or_cond_fu_266_p2;
    sc_signal< sc_lv<1> > sel_tmp2_fu_315_p2;
    sc_signal< sc_lv<1> > or_cond8_fu_283_p2;
    sc_signal< sc_lv<1> > sel_tmp6_fu_345_p2;
    sc_signal< sc_lv<2> > dir_g_3_cast_fu_333_p3;
    sc_signal< sc_lv<2> > sel_tmp4_fu_340_p3;
    sc_signal< sc_lv<2> > dir_g_6_fu_349_p3;
    sc_signal< sc_lv<11> > element_final_fu_357_p3;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_st1_fsm_0;
    static const sc_lv<3> ap_ST_st2_fsm_1;
    static const sc_lv<3> ap_ST_pp0_stg0_fsm_2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<11> ap_const_lv11_400;
    static const sc_lv<11> ap_const_lv11_1;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_abs_gx_fu_141_p3();
    void thread_abs_gy_fu_161_p3();
    void thread_abscond_i1_fu_155_p2();
    void thread_abscond_i_fu_135_p2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_161();
    void thread_ap_sig_bdd_22();
    void thread_ap_sig_bdd_50();
    void thread_ap_sig_bdd_61();
    void thread_ap_sig_bdd_72();
    void thread_ap_sig_bdd_84();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_2();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_dir_g_1_fu_288_p3();
    void thread_dir_g_2_fu_300_p3();
    void thread_dir_g_3_cast_fu_333_p3();
    void thread_dir_g_6_fu_349_p3();
    void thread_dir_g_cast_fu_275_p1();
    void thread_element_final_fu_357_p3();
    void thread_element_grad_fu_177_p2();
    void thread_exitcond4_fu_105_p2();
    void thread_exitcond_fu_117_p2();
    void thread_grad_out_data_stream_V_din();
    void thread_grad_out_data_stream_V_write();
    void thread_grad_x_data_stream_V_read();
    void thread_grad_y_data_stream_V_read();
    void thread_i_V_fu_111_p2();
    void thread_j_V_fu_123_p2();
    void thread_neg_i1_fu_149_p2();
    void thread_neg_i_fu_129_p2();
    void thread_or_cond7_fu_261_p2();
    void thread_or_cond8_fu_283_p2();
    void thread_or_cond_fu_266_p2();
    void thread_rev1_fu_231_p2();
    void thread_rev2_fu_295_p2();
    void thread_rev9_fu_256_p2();
    void thread_rev_fu_270_p2();
    void thread_sel_tmp1_fu_307_p3();
    void thread_sel_tmp2_fu_315_p2();
    void thread_sel_tmp3_fu_321_p2();
    void thread_sel_tmp4_fu_340_p3();
    void thread_sel_tmp6_fu_345_p2();
    void thread_tmp10_fu_327_p2();
    void thread_tmp8_fu_203_p2();
    void thread_tmp9_fu_279_p2();
    void thread_tmp_131_cast_fu_169_p1();
    void thread_tmp_132_cast_fu_173_p1();
    void thread_tmp_136_cast_fu_208_p1();
    void thread_tmp_137_cast_fu_211_p1();
    void thread_tmp_36_fu_183_p2();
    void thread_tmp_37_fu_199_p2();
    void thread_tmp_38_fu_189_p2();
    void thread_tmp_39_fu_214_p3();
    void thread_tmp_40_fu_237_p3();
    void thread_tmp_41_fu_244_p2();
    void thread_ult1_fu_221_p2();
    void thread_ult2_fu_227_p2();
    void thread_ult3_fu_250_p2();
    void thread_ult_fu_195_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
