// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _canny_Block_proc_HH_
#define _canny_Block_proc_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct canny_Block_proc : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<12> > img_0_rows_V_out_din;
    sc_in< sc_logic > img_0_rows_V_out_full_n;
    sc_out< sc_logic > img_0_rows_V_out_write;
    sc_out< sc_lv<12> > img_0_cols_V_out_din;
    sc_in< sc_logic > img_0_cols_V_out_full_n;
    sc_out< sc_logic > img_0_cols_V_out_write;


    // Module declarations
    canny_Block_proc(sc_module_name name);
    SC_HAS_PROCESS(canny_Block_proc);

    ~canny_Block_proc();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_20;
    sc_signal< bool > ap_sig_bdd_43;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_st1_fsm_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<12> ap_const_lv12_400;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_20();
    void thread_ap_sig_bdd_43();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_img_0_cols_V_out_din();
    void thread_img_0_cols_V_out_write();
    void thread_img_0_rows_V_out_din();
    void thread_img_0_rows_V_out_write();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
